/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */

/**
 * An ad to be displayed on the homepage
 */
export interface HomepageAd {
	/** The URL that the ad should link to when clicked */
	url: string;
	/** The source URL of the image to be displayed in the ad */
	imgSrc: string;
	/** Optional background color for the ad, in hex format (e.g., #FFFFFF) */
	background?: string;
}
