/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */

/**
 * The email associated with the message
 */
export type InboxMessageEmail = {
	/** The content of the email */
	content: string | null;
} | null;
