/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */

/**
 * A record of a judge's decision. used in paradigm details
 */
export interface JudgeRecord {
	/** Tournament name */
	tournName: string;
	/** Date of the round */
	roundDate: string;
	/** Label for the round (e.g., R2) */
	roundLabel: string;
	/** Event abbreviation (e.g., PF) */
	eventAbbr: string;
	/** Affirmative team name */
	affTeam: string;
	/** Affirmative label (e.g., Pro) */
	affLabel: string;
	/** Negative team name */
	negTeam: string;
	/** Negative label (e.g., Con) */
	negLabel: string;
	/** This judge's vote (e.g., Con) */
	vote: string;
	/** Panel majority vote (e.g., Con) */
	panelVote: string;
	/** Win-loss record for the round (e.g., 0-1) */
	record: string;
}
