/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */
import type { PersonOutput } from './personOutput';

/**
 * A user session
 */
export interface Session {
	/**
	 * @maximum 9007199254740991
	 * @exclusiveMinimum 0
	 */
	id: number;
	/**
	 * @maximum 9007199254740991
	 * @exclusiveMinimum 0
	 */
	person: number;
	su: number | null;
	Su: PersonOutput | null;
	Person: PersonOutput;
}
