/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */
import type { Problem } from './problem';

/**
 * Unauthorized - authentication failed or was not provided.
 */
export type UnauthorizedResponse = Problem;
