<script lang="ts">

	import '../app.css';
	import Header from '$lib/layouts/Header.svelte';
	import Footer from '$lib/layouts/Footer.svelte';

	import { browser } from '$app/environment';
	import { QueryClient } from '@tanstack/svelte-query';
	import { SvelteQueryDevtools } from '@tanstack/svelte-query-devtools';
	import { PersistQueryClientProvider } from '@tanstack/svelte-query-persist-client';
	import { createAsyncStoragePersister } from '@tanstack/query-async-storage-persister';

	import { initPersonContext } from '$lib/context/PersonContext.svelte';

	import type { LayoutProps } from './$types';

	const { children, data }: LayoutProps = $props();
	//TODO: statically type this once we have the type generated by orval
	// eslint-disable-next-line @typescript-eslint/no-explicit-any
	const mapSessionToPerson = (sessionData: any) => {
		if (!sessionData || !sessionData.Person) return null;
		return {
			id       : sessionData.Person.id,
			name     : sessionData.Person.firstName + ' ' + sessionData.Person.lastName,
			email    : sessionData.Person.email,
			tz       : sessionData.Person.tz || 'UTC',
		};
	};
	const personState = initPersonContext(mapSessionToPerson(data.sessionData));
	// Update person context when data changes
	$effect(() => {
		personState.current = mapSessionToPerson(data.sessionData);
	});

	const queryClient = new QueryClient({
		defaultOptions: {
			queries: {
				enabled   : browser,
				staleTime : 60 * 100,
			},
		},
	});

	const persister = createAsyncStoragePersister({
		storage: browser ? window.localStorage : null,
	});

</script>

<PersistQueryClientProvider
	client         = {queryClient}
	persistOptions = {{ persister }}
>
	<Header />
	<main class= 'bg-linear-to-b from-primary-800 to-primary-500 px-6'>
		<div class='
			min-h-[80vh]
			border-warning-500
			border-x-2
			border-t-2
			rounded-t-md
			bg-back-200
		'>
			<div class='flex w-full'>
				{@render children()}
			</div>
		</div>
	</main>
	<SvelteQueryDevtools />
	<Footer />
</PersistQueryClientProvider>
