
export interface TournData {
	id             : string,
	tournId        : number,
	webname        : number,
	name           : string,
	tz             : string,
	location       : string,
	district       : string,
	state          : string,
	country        : string,
	start          : string,
	end            : string,
	regEnd         : string,
	regStart       : string,
	special?       : string,
	closed?        : boolean,
	schoolCount    : number,
	year           : number,
	week           : number,
	events         : string,
	circuits       : string,
	eventTypes     : string,
	nsdaCategories : string,
	signup         : string | undefined,
	online         : number,
	inPerson       : number,
	hybrid         : number,
	sortnumeric    : number,
	weekendName?   : string,
	weekendId?     : number,
	districts?     : number,
};
