/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */

export type AuthSuBody = {
	/**
	 * @maximum 9007199254740991
	 * @exclusiveMinimum 0
	 */
	suId: number;
};
