/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */

/**
 * The scope of the backup
 */
export type BackupRequestScopeType =
	(typeof BackupRequestScopeType)[keyof typeof BackupRequestScopeType];

export const BackupRequestScopeType = {
	tournament: 'tournament',
	category: 'category',
	event: 'event',
	school: 'school',
} as const;
