/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */

/**
 * Optional flags that affect how the backup is generated
 */
export type BackupRequestOptions = {
	/** Exclude comments from the backup */
	ignoreComments?: boolean;
	/** Exclude ballots from the backup */
	ignoreBallots?: boolean;
};
