/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */
import type { BackupRequestOptions } from './backupRequestOptions';
import type { BackupRequestScope } from './backupRequestScope';

/**
 * A request to create a backup for a tournament or part of a tournament
 */
export interface BackupRequest {
	/** Defines what part of the tournament to back up */
	scope: BackupRequestScope;
	/** Optional flags that affect how the backup is generated */
	options?: BackupRequestOptions;
}
