/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */
import type { BackupRequestScopeType } from './backupRequestScopeType';

/**
 * Defines what part of the tournament to back up
 */
export type BackupRequestScope = {
	/** The scope of the backup */
	type: BackupRequestScopeType;
	/** The ID of the category, event, or school being backed up (required when scope type is not "tournament") */
	id?: number;
};
