/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */
import type { Problem } from './problem';

/**
 * BadRequest - the request was invalid or cannot be otherwise served.
 */
export type BadRequestResponse = Problem;
