/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */

export interface CaselistLink {
  person_id?: number;
  slug?: string | null;
  caselist_key?: string | null;
  eventcode?: number | null;
}
