/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */
import type { CategorySettingsItem } from './categorySettingsItem';

export interface Category {
  id?: number;
  name?: string;
  abbr?: string;
  tournId?: number;
  patternId?: number | null;
  settings?: CategorySettingsItem[];
  createdAt?: string;
  updatedAt?: string;
}
