/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */
import type { CategorySettingsItem } from './categorySettingsItem';
import type { Event } from './event';

export interface Category {
	id: number;
	name: string;
	abbr: string;
	tournId: number;
	pattern?: number | null;
	settings?: CategorySettingsItem[];
	createdAt?: string;
	updatedAt?: string;
	Events?: Event[];
	Judges?: Event[];
}
