/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */

export interface Chapter {
	/**
	 * Unique identifier for the chapter
	 * @maximum 9007199254740991
	 * @exclusiveMinimum 0
	 */
	id: number;
	/** Name of the chapter */
	name: string;
	formal?: string | null;
	street?: string | null;
	city?: string | null;
	state?: string | null;
	zip?: number | null;
	postal?: string | null;
	country?: string | null;
	coaches?: string | null;
	self_prefs?: boolean | null;
	level?: string | null;
	nsda?: number | null;
	district?: number | null;
	naudl?: boolean | null;
	ipeds?: string | null;
	nces?: string | null;
	ceeb?: string | null;
	timestamp?: string | null;
	created_at?: string | null;
}
