/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */

export interface ChapterOutput {
	/**
	 * Unique identifier for the chapter
	 * @maximum 9007199254740991
	 * @exclusiveMinimum 0
	 */
	id: number;
	/** Name of the chapter */
	name: string;
	formal?: string | null;
	street?: string | null;
	city?: string | null;
	state?: string | null;
	zip?: number | null;
	postal?: string | null;
	country?: string | null;
	coaches?: string | null;
	selfPrefs?: boolean | null;
	level?: string | null;
	nsdaId?: number | null;
	districtId?: number | null;
	naudl?: boolean | null;
	ipeds?: string | null;
	nces?: string | null;
	ceeb?: string | null;
	timestamp?: string | null;
	createdAt?: string | null;
}
