/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */
import type { ContactMetadata } from './contactMetadata';
import type { ContactSettings } from './contactSettings';
import type { Person } from './person';
import type { School } from './school';

/**
 * A tournament contact for a school
 */
export interface Contact {
	id: number;
	schoolId: number;
	personId: number;
	/** True if the contact is a designated official contact for the school */
	official?: boolean;
	/** True if the contact will be physically present at the tournament */
	onsite?: boolean;
	/** True if the contact should get mass emails for the school */
	email?: boolean;
	/** True if the contact should appear in the Nationals TBook */
	book?: boolean;
	/** NSDA ID number of the contact if they are a coach */
	nsda?: number;
	firstName?: string;
	middleName?: string | null;
	lastName?: string;
	state?: string;
	country?: string;
	tz?: string;
	/** Creation timestamp */
	readonly createdAt?: string;
	settings?: ContactSettings;
	metadata?: ContactMetadata;
	Person?: Person;
	School?: School;
}
