/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */
import type { CurrentBallotEventSettings } from './currentBallotEventSettings';
import type { CurrentBallotEventType } from './currentBallotEventType';

export type CurrentBallotEvent = {
	type: CurrentBallotEventType;
	settings: CurrentBallotEventSettings;
};
