/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */

export type CurrentBallotFlipStatus =
	| (typeof CurrentBallotFlipStatus)[keyof typeof CurrentBallotFlipStatus]
	| null;

export const CurrentBallotFlipStatus = {
	done: 'done',
	winner: 'winner',
	second: 'second',
	anyone: 'anyone',
} as const;
