/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */

export type CurrentBallotStatus =
	(typeof CurrentBallotStatus)[keyof typeof CurrentBallotStatus];

export const CurrentBallotStatus = {
	not_started: 'not_started',
	started: 'started',
	scored: 'scored',
} as const;
