/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */

export type CurrentBallotEventType =
	(typeof CurrentBallotEventType)[keyof typeof CurrentBallotEventType];

export const CurrentBallotEventType = {
	debate: 'debate',
	speech: 'speech',
	mock_trial: 'mock_trial',
	congress: 'congress',
	wsdc: 'wsdc',
	wudc: 'wudc',
	attendee: 'attendee',
	academic: 'academic',
} as const;
