/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */
import type { Person } from './person';
import type { Tourn } from './tourn';

/**
 * An email sent to a tournament
 */
export interface Email {
	/** The unique identifier */
	readonly id: number;
	subject: string;
	content: string;
	metadata: string;
	sentTo?: string;
	hidden?: boolean;
	senderRaw?: string;
	readonly sentAt?: string;
	readonly createdAt?: string;
	tournId?: number;
	personId?: number;
	senderId?: number;
	Tourn?: Tourn;
	Person?: Person;
	Sender?: Person;
}
