/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */
import type { EntryMetadata } from './entryMetadata';
import type { EntrySettings } from './entrySettings';
import type { Event } from './event';
import type { Person } from './person';
import type { School } from './school';
import type { Student } from './student';

/**
 * An entry
 */
export interface Entry {
	id: number;
	code: string;
	name?: string;
	ada?: boolean;
	active?: boolean;
	dropped?: boolean;
	waitlist?: boolean;
	unconfirmed?: boolean;
	eventId: number;
	schoolId?: number;
	registeredById?: number;
	RegisteredBy?: Person;
	Event?: Event;
	School?: School;
	Students?: Student[];
	settings?: EntrySettings;
	metadata?: EntryMetadata;
	/** Creation timestamp */
	readonly createdAt?: string;
}
