/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */

export type EventInviteType =
	(typeof EventInviteType)[keyof typeof EventInviteType];

export const EventInviteType = {
	debate: 'debate',
	speech: 'speech',
	mock_trial: 'mock_trial',
	congress: 'congress',
	wsdc: 'wsdc',
	wudc: 'wudc',
	attendee: 'attendee',
	academic: 'academic',
} as const;
