/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */
import type { ResultSetEventOutput } from './resultSetEventOutput';

export interface EventResultSets {
	/**
	 * @maximum 9007199254740991
	 * @exclusiveMinimum 0
	 */
	id: number;
	/**
	 * @maximum 9007199254740991
	 * @exclusiveMinimum 0
	 */
	nsdacategory: number;
	name: string;
	abbr: string;
	level: string;
	type: string;
	ResultSets: ResultSetEventOutput[];
}
