/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */
import type { EventInviteType } from './eventInviteType';

/**
 * An event associated with a tournament invite
 */
export interface EventInvite {
	id: number;
	abbr: string;
	name: string;
	fee?: number;
	type: EventInviteType;
	categoryId?: number;
	categoryName?: string;
	categoryAbbr?: string;
	judgeFieldReport?: string;
	cap?: number | null;
	schoolCap?: number | null;
	topicSource?: string | null;
	topicEventType?: string | null;
	topicTag?: string | null;
	topicText?: string | null;
	fieldReport?: string | null;
	anonymousPublic?: boolean | null;
	liveUpdates?: string;
	description?: string | null;
	currency?: string;
	entryCount?: number;
	nsdaCategory?: number;
	nsdaName?: string;
}
