/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */

export type EventLevel = (typeof EventLevel)[keyof typeof EventLevel];

export const EventLevel = {
	open: 'open',
	jv: 'jv',
	novice: 'novice',
	champ: 'champ',
	'es-open': 'es-open',
	'es-novice': 'es-novice',
	middle: 'middle',
} as const;
