/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */

export type EventType = (typeof EventType)[keyof typeof EventType];

export const EventType = {
	debate: 'debate',
	speech: 'speech',
	mockTrial: 'mockTrial',
	congress: 'congress',
	wsdc: 'wsdc',
	wudc: 'wudc',
	attendee: 'attendee',
	academic: 'academic',
} as const;
