/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */
import type { Category } from './category';
import type { Entry } from './entry';
import type { EventMetadata } from './eventMetadata';
import type { EventSettings } from './eventSettings';
import type { EventType } from './eventType';
import type { NSDACategory } from './nSDACategory';
import type { Topic } from './topic';

/**
 * An event
 */
export interface Event {
	id: number;
	abbr: string;
	name: string;
	fee?: number;
	type: EventType;
	categoryId: number;
	settings?: EventSettings;
	metadata?: EventMetadata;
	Tourn?: Category;
	Category?: Category;
	Topic?: Topic;
	Entries?: Entry[];
	nsdaCategoryId?: number | null;
	NSDACategory?: NSDACategory;
}
