/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */
import type { GetParadigmByPersonId200CertificationsItem } from './getParadigmByPersonId200CertificationsItem';
import type { GetParadigmByPersonId200RecordItem } from './getParadigmByPersonId200RecordItem';

export type GetParadigmByPersonId200 = {
	id?: number;
	/** Full name */
	name?: string;
	/** Last reviewed timestamp */
	lastReviewed?: string;
	/** Paradigm content */
	paradigm?: string;
	record?: GetParadigmByPersonId200RecordItem[];
	certifications?: GetParadigmByPersonId200CertificationsItem[];
};
