/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */
import type { EventResultSets } from './eventResultSets';

export type GetTournResultSets200 = { [key: string]: EventResultSets };
