/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */

/**
 * The sender of the message
 */
export type InboxMessageSender = {
	/** The name of the sender */
	name: string | null;
	/** The email of the sender */
	email: string | null;
} | null;
