/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */
import type { InboxMessageEmail } from './inboxMessageEmail';
import type { InboxMessageSender } from './inboxMessageSender';
import type { InboxMessageTourn } from './inboxMessageTourn';

export interface InboxMessage {
	/**
	 * The unique identifier for the message
	 * @maximum 9007199254740991
	 * @exclusiveMinimum 0
	 */
	id: number;
	/** The subject of the message */
	subject: string | null;
	/** The body of the message */
	body: string | null;
	/** The URL associated with the message */
	url: string | null;
	/** The timestamp when the message became visible */
	visibleAt: string | null;
	/** The timestamp when the message was read */
	readAt: string | null;
	/** The tournament associated with the message */
	Tourn: InboxMessageTourn;
	/** The sender of the message */
	Sender: InboxMessageSender;
	/** The email associated with the message */
	Email: InboxMessageEmail;
}
