/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */

/**
 * The tournament associated with the message
 */
export type InboxMessageTourn = {
	/**
	 * The unique identifier for the tournament
	 * @maximum 9007199254740991
	 * @exclusiveMinimum 0
	 */
	id: number;
	/** The name of the tournament */
	name: string | null;
	/** The web name of the tournament */
	webname: string | null;
} | null;
