/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */

export * from './ad';
export * from './backupRequest';
export * from './backupRequestOptions';
export * from './backupRequestScope';
export * from './backupRequestScopeType';
export * from './caselistLink';
export * from './category';
export * from './categorySettingsItem';
export * from './chapter';
export * from './createSchool';
export * from './createSchoolSettings';
export * from './errorResponseResponse';
export * from './event';
export * from './eventInvite';
export * from './eventLevel';
export * from './eventType';
export * from './file';
export * from './invite';
export * from './loginRequest';
export * from './notFoundResponse';
export * from './person';
export * from './problem';
export * from './publicAd';
export * from './registerRequest';
export * from './round';
export * from './school';
export * from './schoolSettings';
export * from './search';
export * from './share';
export * from './siteResponse';
export * from './student';
export * from './timeslotRequest';
export * from './timeslotResponse';
export * from './tourn';
export * from './tournContact';
export * from './tournInvite';
export * from './tournRequest';
export * from './unauthorizedResponse';
export * from './updateSchool';
export * from './updateSchoolSettings';
export * from './webPage';
