/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */

export * from './ad';
export * from './backupRequest';
export * from './backupRequestOptions';
export * from './backupRequestScope';
export * from './backupRequestScopeType';
export * from './caselistLink';
export * from './category';
export * from './categorySettingsItem';
export * from './chapter';
export * from './contact';
export * from './contactMetadata';
export * from './contactSettings';
export * from './createSchool';
export * from './createSchoolSettings';
export * from './email';
export * from './entry';
export * from './entryMetadata';
export * from './entrySettings';
export * from './errorResponseResponse';
export * from './event';
export * from './eventInvite';
export * from './eventMetadata';
export * from './eventSettings';
export * from './eventType';
export * from './file';
export * from './invite';
export * from './judge';
export * from './judgeRecord';
export * from './loginRequest';
export * from './loginResponse';
export * from './loginResponsePerson';
export * from './notFoundResponse';
export * from './nSDACategory';
export * from './paradigmDetails';
export * from './paradigmDetailsCertificationsItem';
export * from './paradigmDetailsCertificationsItemBadge';
export * from './person';
export * from './personMetadata';
export * from './personSettings';
export * from './problem';
export * from './publicAd';
export * from './registerRequest';
export * from './restAds200Item';
export * from './restCircuit';
export * from './restCircuitsActive200Item';
export * from './restCircuitsActiveParams';
export * from './restParadigms200Item';
export * from './restParadigms200ItemSchoolsItem';
export * from './restParadigmsParams';
export * from './restTournsParams';
export * from './round';
export * from './school';
export * from './schoolMetadata';
export * from './schoolSettings';
export * from './search';
export * from './session';
export * from './share';
export * from './siteResponse';
export * from './student';
export * from './studentMetadata';
export * from './studentSettings';
export * from './timeslotRequest';
export * from './timeslotResponse';
export * from './topic';
export * from './topicSource';
export * from './tourn';
export * from './tournContact';
export * from './tournInvite';
export * from './tournMetadata';
export * from './tournRequest';
export * from './tournSettings';
export * from './unauthorizedResponse';
export * from './updateSchool';
export * from './updateSchoolSettings';
export * from './userInboxUnread200';
export * from './webpage';
