/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */

export interface Invite {
	name?: string | null;
}
