/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */
import type { JudgeHistoryTourn } from './judgeHistoryTourn';

/**
 * A person's history of judging
 */
export interface JudgeHistory {
	/** Tournament details */
	Tourn: JudgeHistoryTourn;
	/** Division name (e.g., Open, JV) */
	division: string;
	/**
	 * Number of rounds judged at the tournament
	 * @minimum 0
	 * @maximum 9007199254740991
	 */
	roundsJudged: number;
	/**
	 * Number of rounds obligated at the tournament
	 * @minimum 0
	 * @maximum 9007199254740991
	 */
	roundsObligated: number;
}
