/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */

export type LoginResponsePerson = {
	/**
	 * @minimum -9007199254740991
	 * @maximum 9007199254740991
	 */
	id: number;
	email: string;
};
