/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */

/**
 * A request to log in a user
 */
export interface LoginRequest {
  /** the username of the user */
  username: string;
  /** The hashed user password */
  password: string;
}
