/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */

/**
 * A request to log in a user
 */
export interface LoginRequest {
	/** The username of the user */
	username: string;
	/** The password of the user */
	password: string;
}
