/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */

export type ParadigmDetailsCertificationsItemBadge = {
	altText?: string;
	link?: string;
	imageUrl?: string;
};
