/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */
import type { ParadigmDetailsCertificationsItemBadge } from './paradigmDetailsCertificationsItemBadge';

export type ParadigmDetailsCertificationsItem = {
	/** The title of the certification */
	title: string;
	/** The description of the certification */
	description: string;
	/**
	 * The last updated timestamp of the certification
	 * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$
	 */
	updatedAt: string;
	/** The badge associated with the certification */
	badge?: ParadigmDetailsCertificationsItemBadge;
};
