/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */
import type { ParadigmDetailsCertificationsItem } from './paradigmDetailsCertificationsItem';

export interface ParadigmDetails {
	id: number;
	/** Full name */
	name: string;
	/** Last reviewed timestamp */
	lastReviewed: string;
	/** Paradigm content */
	paradigm: string;
	certifications: ParadigmDetailsCertificationsItem[];
}
