/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */
import type { ParadigmDetailsCertificationsItemBadge } from './paradigmDetailsCertificationsItemBadge';

export type ParadigmDetailsCertificationsItem = {
	title?: string;
	description?: string;
	updatedAt?: string;
	badge?: ParadigmDetailsCertificationsItemBadge;
};
