/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */
import type { PersonMetadata } from './personMetadata';
import type { PersonSettings } from './personSettings';

/**
 * A person (user) in tabroom
 */
export interface Person {
	id: number;
	email: string;
	firstName: string;
	middleName?: string | null;
	lastName: string;
	state?: string;
	country?: string;
	tz?: string;
	/** Creation timestamp */
	readonly createdAt?: string;
	settings?: PersonSettings;
	metadata?: PersonMetadata;
}
