/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */

/**
 * A person (user) in tabroom
 */
export interface Person {
	id?: number;
	email?: string;
}
