/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */

export type PostUserJudgesParadigmBody = {
	/**
	 * The new paradigm for the user
	 * @maxLength 65535
	 */
	paradigm: string;
};
