/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */

export interface Problem {
  /** A URI reference that identifies the problem type. */
  type: string;
  /** A short, human-readable summary of the problem type. */
  title: string;
  /** The HTTP status code. */
  status: number;
  /** Human-readable explanation of the error. */
  detail?: string;
  /** A URI reference to the specific occurrence. */
  instance?: string;
  [key: string]: unknown;
}
