/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */

/**
 * A public representation of the ads displayed on the homepage
 */
export interface PublicAd {
	/** the Id of the Ad */
	readonly id?: number;
	/** The Image filename */
	filename?: string;
	/** The link to follow when the ad is clicked */
	url?: string;
}
