/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */
import type { PersonQuizOutput } from './personQuizOutput';
import type { QuizBadgeOutput } from './quizBadgeOutput';

export interface QuizOutput {
	/**
	 * @maximum 9007199254740991
	 * @exclusiveMinimum 0
	 */
	id: number;
	tag: string | null;
	label: string | null;
	description: string | null;
	sitewide: boolean;
	hidden: boolean;
	approval: boolean;
	show_answers: boolean;
	admin_only: boolean;
	circuit: number | null;
	Badge: QuizBadgeOutput;
	PersonQuizzes?: PersonQuizOutput[];
}
