/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */

/**
 * The badge associated with the certification
 */
export interface QuizBadgeOutput {
	/** The alt text for the badge image */
	altText: string | null;
	/** The link to the badge */
	link: string | null;
	/** The URL of the badge image */
	imageUrl: string | null;
}
