/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */

/**
 * A request to register a new user
 */
export interface RegisterRequest {
	/** The email address of the new user */
	email: string;
	/** The password for the new user */
	password: string;
	/** The first name of the new user */
	firstName: string;
	/** The middle name of the new user */
	middleName?: string;
	/** The last name of the new user */
	lastName: string;
	/** The phone number of the new user */
	phoneNumber?: string;
	/** The 2 letter state code of the new user */
	state?: string;
	/** The 2 letter country code of the new user */
	country?: string;
	/** The IANA timezone of the new user */
	tz?: string;
}
