/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */

export type RestCircuitsActiveParams = {
	/**
	 * 2-character state code to filter circuits
	 * @maxLength 2
	 */
	state?: string;
	/**
	 * 2-character country code to filter circuits
	 * @maxLength 2
	 */
	country?: string;
};
