/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */
import type { RestParadigms200ItemSchoolsItem } from './restParadigms200ItemSchoolsItem';

export type RestParadigms200Item = {
	/**
	 * @maximum 9007199254740991
	 * @exclusiveMinimum 0
	 */
	id: number;
	/** Full name */
	name: string;
	/**
	 * Number of tournaments judged
	 * @maximum 9007199254740991
	 * @exclusiveMinimum 0
	 */
	tournJudged: number;
	schools: RestParadigms200ItemSchoolsItem[];
};
