/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */

export type RestTournsParams = {
	/**
	 * Filter tournaments to those approved in this circuit.
	 */
	circuit?: number;
	/**
	 * Return tournaments with start date after this UTC timestamp.
	 */
	startAfter?: string;
	/**
	 * Return tournaments with start date before this UTC timestamp.
	 */
	startBefore?: string;
	/**
	 * Comma-separated tournament fields. Example: id,name,start
	 */
	fields?: string;
	/**
	 * Comma-separated event fields to include when requesting events.
	 */
	'fields[events]'?: string;
};
