/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */

export type RestQuizzesParams = {
	/**
	 * Number of quizzes to return
	 */
	limit?: number;
	/**
	 * Number of quizzes to skip
	 */
	offset?: number;
};
