/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */

export type RestCircuitsActiveParams = {
	/**
	 * 2-character state code to filter circuits
	 * @maxLength 2
	 */
	state?: string;
	/**
	 * 2-character country code to filter circuits
	 * @maxLength 2
	 */
	country?: string;
	/**
	 * Maximum number of circuits to return
	 * @minimum 1
	 * @maximum 100
	 */
	limit?: number;
	/**
	 * Number of circuits to skip before starting to return results
	 * @minimum 0
	 */
	offset?: number;
};
