/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */

export type RestTournsParams = {
	/**
	 * Maximum number of tournaments to return. Default: 50, Max: 250.
	 * @minimum 0
	 * @maximum 250
	 */
	limit?: number;
	/**
	 * Number of tournaments to skip. Must be a non-negative number.
	 * @minimum 0
	 */
	offset?: number;
	/**
	 * Filter tournaments to those approved in this circuit.
	 */
	circuit?: number;
	/**
	 * Return tournaments with start date after this UTC timestamp.
	 * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$
	 */
	startAfter?: string;
	/**
	 * Return tournaments with start date before this UTC timestamp.
	 * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$
	 */
	startBefore?: string;
	/**
	 * Comma-separated tournament fields. Example: id,name,start
	 */
	fields?: string;
	/**
	 * Comma-separated event fields to include when requesting events.
	 */
	'fields[events]'?: string;
	/**
	 * Filter tournaments to those with published results.
	 */
	publishedResults?: boolean;
};
