/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */

export type RestJudgesUnlinkedSearchParams = {
	/**
	 * Maximum number of results to return
	 */
	limit?: number;
	/**
	 * Number of results to skip for pagination
	 */
	offset?: number;
	/**
	 * First name to search for
	 */
	first?: string;
	/**
	 * Last name to search for
	 */
	last?: string;
};
