/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */

export interface RestCircuit {
	/** @exclusiveMinimum 0 */
	readonly id: number;
	name?: string | null;
	abbr?: string | null;
	tz?: string | null;
	active?: boolean | null;
	state?: string | null;
	country?: string | null;
	webname?: string | null;
}
