/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */

export type RestCircuitsActive200Item = {
	id?: number;
	abbr?: string;
	name?: string;
	state?: string;
	country?: string;
	tournCount?: number;
};
