/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */
import type { ResultSetHeadersProtocol } from './resultSetHeadersProtocol';

export type ResultSetHeaders = {
	[key: string]: {
		tag: string;
		description: string;
		no_sort: boolean;
		sort_desc: boolean;
		Protocol?: ResultSetHeadersProtocol;
	};
};
