/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */
import type { Chapter } from './chapter';
import type { Entry } from './entry';
import type { Judge } from './judge';
import type { SchoolMetadata } from './schoolMetadata';
import type { SchoolSettings } from './schoolSettings';

export interface School {
	/** Unique identifier for the school */
	readonly id?: number;
	/** Name of the school */
	name?: string;
	/** School code */
	code?: string;
	/** Whether the school is onsite */
	onsite?: boolean;
	/** Tournament ID */
	tournId?: number;
	/** Chapter ID */
	chapterId?: number;
	/** State abbreviation */
	state?: string;
	/** Region ID */
	regionId?: number;
	/** District ID */
	districtId?: number;
	/** Last modified timestamp */
	readonly updatedAt?: string;
	/** Creation timestamp */
	readonly createdAt?: string;
	Chapter?: Chapter;
	Entries?: Entry[];
	Judges?: Judge[];
	settings?: SchoolSettings;
	metadata?: SchoolMetadata;
}
