/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */

export type SearchParadigmsParams = {
	/**
	 * Search query for paradigms
	 */
	search: string;
	/**
	 * Maximum number of paradigms to return
	 * @minimum 1
	 * @maximum 100
	 */
	limit?: number;
	/**
	 * Number of paradigms to skip before starting to return results
	 * @minimum 0
	 */
	offset?: number;
};
