/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */
import type { SearchParadigms200ItemSchoolsItem } from './searchParadigms200ItemSchoolsItem';

export type SearchParadigms200Item = {
	id?: number;
	/** Full name */
	name?: string;
	/** Number of tournaments judged */
	tournJudged?: number;
	schools?: SearchParadigms200ItemSchoolsItem[];
};
