/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */

export type SearchParadigms200ItemChaptersItem = {
	id?: number;
	name?: string;
};
