/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */
import type { Person } from './person';

/**
 * A user session
 */
export interface Session {
	id?: number;
	personId?: number;
	suId?: number | null;
	Su?: Person | null;
	Person?: Person;
}
