/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */

export interface Share {
	panels?: unknown[] | null;
	files?: unknown[] | null;
	from?: string | null;
}
