/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */

export interface SiteResponse {
	readonly id?: number;
	name?: string;
	online?: boolean;
	directions?: string | null;
	dropoff?: string | null;
	hostId?: number | null;
	circuitId?: number | null;
	readonly createdAt?: string;
	readonly updatedAt?: string;
}
