/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */

/**
 * Additional metadata for the student
 */
export type StudentMetadata = { [key: string]: unknown };
