/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */
import type { Chapter } from './chapter';
import type { PersonOutput } from './personOutput';
import type { StudentMetadata } from './studentMetadata';
import type { StudentSettings } from './studentSettings';

export interface Student {
	/**
	 * Unique identifier for the student
	 * @maximum 9007199254740991
	 * @exclusiveMinimum 0
	 */
	readonly id: number;
	/** First name of the student */
	first?: string | null;
	/** Middle name of the student */
	middle?: string | null;
	/** Last name of the student */
	last?: string | null;
	/** Pronunciation guide */
	phonetic?: string | null;
	/** Full Year of student graduation */
	gradYear?: number | null;
	/** Whether the student is a novice */
	novice?: boolean;
	/** Whether the student is retired */
	retired?: boolean;
	/** Student gender */
	gender?: string | null;
	/** NSDA Member ID Number */
	nsda?: number | null;
	/**
	 * Chapter School that the student belongs to
	 * @maximum 9007199254740991
	 * @exclusiveMinimum 0
	 */
	chapterId: number;
	/** Tabroom Person the student is linked to */
	personId?: number | null;
	Chapter?: Chapter;
	Person?: PersonOutput;
	/** Creation timestamp */
	readonly createdAt: string;
	/** Custom settings for the student */
	settings?: StudentSettings;
	/** Additional metadata for the student */
	metadata?: StudentMetadata;
}
