/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */
import type { Chapter } from './chapter';
import type { Person } from './person';
import type { StudentMetadata } from './studentMetadata';
import type { StudentSettings } from './studentSettings';

export interface Student {
	/** Unique identifier for the student */
	readonly id: number;
	/** First name of the student */
	firstName: string;
	/** Middle name of the student */
	middleName?: string;
	/** Last name of the student */
	lastName: string;
	/** Pronunciation guide */
	phonetic?: string;
	/** Full Year of student graduation */
	gradYear?: number;
	novice?: boolean;
	retired?: boolean;
	gender?: string;
	/** NSDA Member ID Number */
	nsda?: number;
	/** Chapter School that the student belongs to */
	chapterId: number;
	/** Tabroom Person the student is linked to */
	personId?: number;
	Chapter?: Chapter;
	Person?: Person;
	/** Creation timestamp */
	readonly createdAt?: string;
	settings?: StudentSettings;
	metadata?: StudentMetadata;
}
