/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */

export type StudentSettings = { [key: string]: string | number | boolean };
