/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */

export interface Student {
  id?: number;
  first?: string | null;
  middle?: string | null;
  last?: string | null;
  phonetic?: string | null;
  grad_year?: number | null;
  novice?: boolean;
  retired?: boolean;
  gender?: string | null;
  diet?: string | null;
  /** @pattern ^([0-9]{2,4})-([0-1][0-9])-([0-3][0-9])(?:( [0-2][0-9]):([0-5][0-9]):([0-5][0-9]))?$ */
  birthdate?: string | null;
  school_sid?: string | null;
  race?: string | null;
  nsda?: number | null;
  chapter?: number | null;
  person?: number | null;
  person_request?: number | null;
  /** @pattern ^([0-9]{2,4})-([0-1][0-9])-([0-3][0-9])(?:( [0-2][0-9]):([0-5][0-9]):([0-5][0-9]))?$ */
  timestamp?: string | null;
}
