/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */

export interface TimeslotResponse {
	id?: number;
	name?: string;
	start?: string;
	end?: string;
	tournId?: number;
	updatedAt?: string;
	createdAt?: string;
}
