/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */

export type TopicSource = (typeof TopicSource)[keyof typeof TopicSource];

export const TopicSource = {
	NSDA: 'NSDA',
	NCFL: 'NCFL',
	CEDA: 'CEDA',
	NFHS: 'NFHS',
	CPFL: 'CPFL',
	NFA: 'NFA',
	AFA: 'AFA',
} as const;
