/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */
import type { Event } from './event';
import type { Person } from './person';
import type { TopicSource } from './topicSource';

export interface Topic {
	id: number;
	tag: string;
	source: TopicSource;
	schoolYear: number;
	eventType?: string;
	pattern?: string;
	topicText: string;
	createdAt?: string;
	createdBy?: Person;
	Events?: Event[];
}
