/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */
import type { Category } from './category';
import type { Contact } from './contact';
import type { Email } from './email';
import type { Event } from './event';
import type { File } from './file';
import type { School } from './school';
import type { TournMetadata } from './tournMetadata';
import type { TournSettings } from './tournSettings';
import type { Webpage } from './webpage';

/**
 * A tournament
 */
export interface Tourn {
	/** The unique identifier for the tournament */
	readonly id: number;
	/** The name of the tournament */
	name: string;
	/** The city where the tournament is held */
	city?: string;
	/** The state where the tournament is held */
	state?: string;
	/** The country where the tournament is held */
	country?: string;
	/** The IANA timezone of the tournament location */
	tz: string;
	/** The web name of the tournament */
	webname: string;
	/** The start date and time of the tournament */
	start: string;
	/** The end date and time of the tournament */
	end: string;
	/** The registration start date and time of the tournament */
	regStart?: string;
	/** The registration end date and time of the tournament */
	regEnd?: string;
	Contacts?: Contact[];
	Categories?: Category[];
	Events?: Event[];
	Schools?: School[];
	Webpages?: Webpage[];
	Files?: File[];
	Emails?: Email[];
	/** Creation timestamp */
	readonly createdAt?: string;
	settings?: TournSettings;
	metadata?: TournMetadata;
}
