/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */

/**
 * A tournament contact person
 */
export interface TournContact {
  /** The unique identifier for the contact person */
  readonly id?: number;
  /** The first name of the contact person */
  first?: string;
  /** The middle name of the contact person */
  middle?: string | null;
  /** The last name of the contact person */
  last?: string;
  /** The email address of the contact person */
  email?: string;
}
