/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */
import type { EventInvite } from './eventInvite';
import type { File } from './file';
import type { Tourn } from './tourn';
import type { TournContact } from './tournContact';
import type { Webpage } from './webpage';

export type TournInvite = Tourn & {
	Webpages?: Webpage[];
	Files?: File[];
	Events?: EventInvite[];
	Contacts?: TournContact[];
};
