/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */

/**
 * A tournament
 */
export interface Tourn {
	/** The unique identifier for the tournament */
	readonly id?: number;
	/** The name of the tournament */
	name?: string;
	/** The city where the tournament is held */
	city?: string;
	/** The state where the tournament is held */
	state?: string;
	/** The country where the tournament is held */
	country?: string;
	/** The IANA timezone of the tournament location */
	tz?: string;
	/** The web name of the tournament */
	webName?: string;
	/** The start date and time of the tournament */
	start?: string;
	/** The end date and time of the tournament */
	end?: string;
	/** The registration start date and time of the tournament */
	regStart?: string;
	/** The registration end date and time of the tournament */
	regEnd?: string;
}
