/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */
import type { EventInvite } from './eventInvite';
import type { File } from './file';
import type { Tourn } from './tourn';
import type { TournContact } from './tournContact';
import type { WebPage } from './webPage';

export type TournInvite = Tourn & {
  webpages?: WebPage[];
  files?: File[];
  events?: EventInvite[];
  contacts?: TournContact[];
};
