/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */
import type { UnlinkedStudentChapter } from './unlinkedStudentChapter';

export interface UnlinkedStudent {
	/**
	 * @maximum 9007199254740991
	 * @exclusiveMinimum 0
	 */
	id: number;
	first: string | null;
	last: string | null;
	Chapter: UnlinkedStudentChapter;
	tournCount: number | null;
}
