/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */

export type UnlinkedStudentChapter = {
	name: string | null;
	/**
	 * Two letter state code for the chapter
	 * @pattern ^[A-Z]{2}$
	 */
	state: string;
} | null;
