/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */

export type UnlinkedJudgeType =
	(typeof UnlinkedJudgeType)[keyof typeof UnlinkedJudgeType];

export const UnlinkedJudgeType = {
	judge: 'judge',
	chapter_judge: 'chapter_judge',
} as const;
