/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */

export type UnlinkedStudentSearchChapter = {
	name: string | null;
	state: string | null;
} | null;
