/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */
import type { UnlinkedStudentSearchChapter } from './unlinkedStudentSearchChapter';

export interface UnlinkedStudentSearch {
	/**
	 * @maximum 9007199254740991
	 * @exclusiveMinimum 0
	 */
	id: number;
	first: string | null;
	middle?: string | null;
	last: string | null;
	gradYear?: number | null;
	Chapter: UnlinkedStudentSearchChapter;
	tournCount: number | null;
}
