/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */
import type { UnlinkedJudgeType } from './unlinkedJudgeType';

export interface UnlinkedJudge {
	/**
	 * @maximum 9007199254740991
	 * @exclusiveMinimum 0
	 */
	id: number;
	type: UnlinkedJudgeType;
	first: string | null;
	last: string | null;
	schoolName?: string | null;
	tournName?: string | null;
	/**
	 * @minimum 0
	 * @maximum 9007199254740991
	 */
	tournCount?: number;
}
