/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */
import type { UpdateSchoolSettings } from './updateSchoolSettings';

export interface UpdateSchool {
	/** Name of the school */
	name?: string;
	/** School code */
	code?: string;
	/** Whether the school is onsite */
	onsite?: boolean;
	/** State abbreviation */
	state?: string;
	/** Region ID */
	regionId?: number;
	/** School settings object */
	settings?: UpdateSchoolSettings;
}
