/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */

export type UserJudgesClaimParams = {
	/**
	 * ID of the judge to claim (if claiming a judge)
	 * @maximum 9007199254740991
	 * @exclusiveMinimum 0
	 */
	judgeId?: number;
	/**
	 * ID of the chapter judge to claim (if claiming a chapter judge)
	 * @maximum 9007199254740991
	 * @exclusiveMinimum 0
	 */
	chapterJudgeId?: number;
};
