/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */

export type UserJudgesHistoryParams = {
	/**
	 * The number of results to return.
	 * @maximum 9007199254740991
	 * @exclusiveMinimum 0
	 */
	limit?: number;
	/**
	 * The number of results to skip when returning.
	 * @maximum 9007199254740991
	 * @exclusiveMinimum 0
	 */
	offset?: number;
};
