/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */

export type UserStudentsClaim200 = {
	/** A message indicating the claim request was submitted */
	message: string;
	/** Additional details about the claim request submission */
	detail: string;
};
