/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */

/**
 * A webpage
 */
export interface Webpage {
	/** Unique identifier */
	readonly id?: number;
	/**
	 * Title of the page
	 * @maxLength 63
	 * @nullable
	 */
	title?: string | null;
	/**
	 * Page content
	 * @nullable
	 */
	content?: string | null;
	/** Whether the page is published */
	published?: boolean;
	/** Whether the page is visible sitewide */
	sitewide?: boolean;
	/**
	 * Special page identifier or mode
	 * @maxLength 15
	 * @nullable
	 */
	special?: string | null;
	/**
	 * page slug
	 * @maxLength 63
	 * @nullable
	 */
	slug?: string | null;
	/**
	 * Ordering value for page display
	 * @nullable
	 */
	pageOrder?: number | null;
	/**
	 * Parent page ID (for hierarchical pages)
	 * @nullable
	 */
	parentId?: number | null;
	/** Timestamp when the page was last modified */
	readonly updatedAt?: string;
}
