/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */
import { faker } from '@faker-js/faker';

import type {
	ActiveCircuitsResponse,
	CurrentBallot,
	Fine,
	GetTournResultSets200,
	HomepageAd,
	InboxMessage,
	JudgeHistory,
	JudgeRecord,
	LoginResponse,
	ParadigmDetails,
	PersonTournSummary,
	QuizOutput,
	RestCircuit,
	RestParadigms200Item,
	ResultSet,
	Session,
	Student,
	Tourn,
	UnlinkedJudge,
	UnlinkedStudentSearch,
	UserChapter,
	UserInboxUnread200,
	UserJudgesClaim200,
	UserJudgesLiveDocs200Item,
	UserJudgesParadigm200,
	UserStudentsClaim200,
} from './schemas';

export const getRestAdsResponseMock = (): HomepageAd[] =>
	Array.from(
		{ length: faker.number.int({ min: 1, max: 10 }) },
		(_, i) => i + 1,
	).map(() => ({
		url: faker.internet.url(),
		imgSrc: faker.internet.url(),
		background: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			undefined,
		]),
	}));

export const getRestCircuitsActiveResponseMock = (): ActiveCircuitsResponse =>
	Array.from(
		{ length: faker.number.int({ min: 1, max: 10 }) },
		(_, i) => i + 1,
	).map(() => ({
		id: faker.number.int({ min: 0, max: 9007199254740991 }),
		name: faker.string.alpha({ length: { min: 10, max: 63 } }),
		abbr: faker.string.alpha({ length: { min: 10, max: 15 } }),
		state: faker.helpers.arrayElement([
			faker.helpers.fromRegExp('^[A-Z]{2}$'),
			null,
		]),
		country: faker.helpers.arrayElement([
			faker.helpers.fromRegExp('^[A-Z]{2}$'),
			null,
		]),
		tournCount: faker.number.int({ min: 0, max: 9007199254740991 }),
	}));

export const getRestCircuitResponseMock = (
	overrideResponse: Partial<Extract<RestCircuit, object>> = {},
): RestCircuit => ({
	id: faker.number.int({ min: 0, max: 9007199254740991 }),
	name: faker.helpers.arrayElement([
		faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 63 } }),
			null,
		]),
		undefined,
	]),
	abbr: faker.helpers.arrayElement([
		faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 15 } }),
			null,
		]),
		undefined,
	]),
	tz: faker.helpers.arrayElement([
		faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 63 } }),
			null,
		]),
		undefined,
	]),
	active: faker.helpers.arrayElement([
		faker.helpers.arrayElement([faker.datatype.boolean(), null]),
		undefined,
	]),
	state: faker.helpers.arrayElement([
		faker.helpers.arrayElement([
			faker.helpers.fromRegExp('^[A-Z]{2}$'),
			null,
		]),
		undefined,
	]),
	country: faker.helpers.arrayElement([
		faker.helpers.arrayElement([
			faker.helpers.fromRegExp('^[A-Z]{2}$'),
			null,
		]),
		undefined,
	]),
	webname: faker.helpers.arrayElement([
		faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 31 } }),
			null,
		]),
		undefined,
	]),
	...overrideResponse,
});

export const getRestJudgesUnlinkedSearchResponseMock = (): UnlinkedJudge[] =>
	Array.from(
		{ length: faker.number.int({ min: 1, max: 10 }) },
		(_, i) => i + 1,
	).map(() => ({
		id: faker.number.int({ min: 0, max: 9007199254740991 }),
		type: faker.helpers.arrayElement(['judge', 'chapter_judge'] as const),
		first: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			null,
		]),
		last: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			null,
		]),
		schoolName: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				null,
			]),
			undefined,
		]),
		tournName: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				null,
			]),
			undefined,
		]),
		tournCount: faker.helpers.arrayElement([
			faker.number.int({ min: 0, max: 9007199254740991 }),
			undefined,
		]),
	}));

export const getRestTournsResponseMock = (): Tourn[] =>
	Array.from(
		{ length: faker.number.int({ min: 1, max: 10 }) },
		(_, i) => i + 1,
	).map(() => ({
		id: faker.number.int({ min: 0, max: 9007199254740991 }),
		name: faker.string.alpha({ length: { min: 10, max: 63 } }),
		city: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 31 } }),
			null,
		]),
		state: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 6, max: 6 } }),
			null,
		]),
		country: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 4, max: 4 } }),
			null,
		]),
		tz: faker.string.alpha({ length: { min: 10, max: 31 } }),
		webname: faker.string.alpha({ length: { min: 10, max: 20 } }),
		hidden: faker.datatype.boolean(),
		start: faker.date.past().toISOString().slice(0, 19) + 'Z',
		end: faker.date.past().toISOString().slice(0, 19) + 'Z',
		regStart: faker.date.past().toISOString().slice(0, 19) + 'Z',
		regEnd: faker.date.past().toISOString().slice(0, 19) + 'Z',
	}));

export const getGetTournResultSetsResponseMock = (): GetTournResultSets200 => ({
	[faker.string.alphanumeric(5)]: {
		id: faker.number.int({ min: 0, max: 9007199254740991 }),
		nsdacategory: faker.number.int({ min: 0, max: 9007199254740991 }),
		name: faker.string.alpha({ length: { min: 10, max: 20 } }),
		abbr: faker.string.alpha({ length: { min: 10, max: 20 } }),
		level: faker.string.alpha({ length: { min: 10, max: 20 } }),
		type: faker.string.alpha({ length: { min: 10, max: 20 } }),
		ResultSets: Array.from(
			{ length: faker.number.int({ min: 1, max: 10 }) },
			(_, i) => i + 1,
		).map(() => ({
			id: faker.number.int({ min: 0, max: 9007199254740991 }),
			tag: faker.string.alpha({ length: { min: 10, max: 20 } }),
			label: faker.string.alpha({ length: { min: 10, max: 20 } }),
			entity: faker.string.alpha({ length: { min: 10, max: 20 } }),
			createdAt: faker.date.past().toISOString().slice(0, 19) + 'Z',
		})),
	},
});

export const getGetResultSetResponseMock = (): ResultSet[] =>
	Array.from(
		{ length: faker.number.int({ min: 1, max: 10 }) },
		(_, i) => i + 1,
	).map(() => ({
		id: faker.number.int({ min: 0, max: 9007199254740991 }),
		tag: faker.string.alpha({ length: { min: 10, max: 20 } }),
		label: faker.string.alpha({ length: { min: 10, max: 20 } }),
		entity: faker.string.alpha({ length: { min: 10, max: 20 } }),
		createdAt: faker.date.past().toISOString().slice(0, 19) + 'Z',
		noPlacement: faker.helpers.arrayElement([
			faker.datatype.boolean(),
			undefined,
		]),
		headers: {
			[faker.string.alphanumeric(5)]: {
				tag: faker.string.alpha({ length: { min: 10, max: 20 } }),
				description: faker.string.alpha({
					length: { min: 10, max: 20 },
				}),
				no_sort: faker.datatype.boolean(),
				sort_desc: faker.datatype.boolean(),
				Protocol: faker.helpers.arrayElement([
					{
						id: faker.number.int({ min: 0, max: 9007199254740991 }),
						name: faker.string.alpha({
							length: { min: 10, max: 20 },
						}),
					},
					undefined,
				]),
			},
		},
		Event: {
			id: faker.number.int({ min: 0, max: 9007199254740991 }),
			abbr: faker.string.alpha({ length: { min: 10, max: 20 } }),
			level: faker.string.alpha({ length: { min: 10, max: 20 } }),
			name: faker.string.alpha({ length: { min: 10, max: 20 } }),
			nsdacategory: faker.number.int({ min: 0, max: 9007199254740991 }),
			type: faker.string.alpha({ length: { min: 10, max: 20 } }),
		},
		results: Array.from(
			{ length: faker.number.int({ min: 1, max: 10 }) },
			(_, i) => i + 1,
		).map(() => ({})),
	}));

export const getRestParadigmsResponseMock = (): RestParadigms200Item[] =>
	Array.from(
		{ length: faker.number.int({ min: 1, max: 10 }) },
		(_, i) => i + 1,
	).map(() => ({
		id: faker.number.int({ min: 0, max: 9007199254740991 }),
		name: faker.string.alpha({ length: { min: 10, max: 20 } }),
		tournJudged: faker.number.int({ min: 0, max: 9007199254740991 }),
		schools: Array.from(
			{ length: faker.number.int({ min: 1, max: 10 }) },
			(_, i) => i + 1,
		).map(() => ({
			id: faker.number.int({ min: 0, max: 9007199254740991 }),
			name: faker.string.alpha({ length: { min: 10, max: 20 } }),
		})),
	}));

export const getRestParadigmResponseMock = (
	overrideResponse: Partial<Extract<ParadigmDetails, object>> = {},
): ParadigmDetails => ({
	id: faker.number.int({ min: 0, max: 9007199254740991 }),
	name: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		null,
	]),
	lastReviewed: faker.helpers.arrayElement([
		faker.date.past().toISOString().slice(0, 19) + 'Z',
		null,
	]),
	paradigm: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		null,
	]),
	certifications: faker.helpers.arrayElement([
		Array.from(
			{ length: faker.number.int({ min: 1, max: 10 }) },
			(_, i) => i + 1,
		).map(() => ({
			id: faker.number.int({ min: 0, max: 9007199254740991 }),
			tag: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 63 } }),
				null,
			]),
			label: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 255 } }),
				null,
			]),
			description: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 511 } }),
				null,
			]),
			sitewide: faker.datatype.boolean(),
			hidden: faker.datatype.boolean(),
			approval: faker.datatype.boolean(),
			show_answers: faker.datatype.boolean(),
			admin_only: faker.datatype.boolean(),
			circuit: faker.helpers.arrayElement([
				faker.number.int({ min: 0, max: 9007199254740991 }),
				null,
			]),
			Badge: {
				altText: faker.helpers.arrayElement([
					faker.string.alpha({ length: { min: 10, max: 20 } }),
					null,
				]),
				link: faker.helpers.arrayElement([faker.internet.url(), null]),
				imageUrl: faker.helpers.arrayElement([
					faker.internet.url(),
					null,
				]),
			},
			PersonQuizzes: faker.helpers.arrayElement([
				Array.from(
					{ length: faker.number.int({ min: 1, max: 10 }) },
					(_, i) => i + 1,
				).map(() => ({
					id: faker.number.int({ min: 0, max: 9007199254740991 }),
					person: faker.number.int({ min: 0, max: 9007199254740991 }),
					quiz: faker.number.int({ min: 0, max: 9007199254740991 }),
					approvedBy: faker.helpers.arrayElement([
						faker.number.int({ min: 0, max: 9007199254740991 }),
						null,
					]),
					pending: faker.datatype.boolean(),
					updatedAt:
						faker.date.past().toISOString().slice(0, 19) + 'Z',
				})),
				undefined,
			]),
		})),
		undefined,
	]),
	...overrideResponse,
});

export const getRestParadigmsRecordResponseMock = (): JudgeRecord[] =>
	Array.from(
		{ length: faker.number.int({ min: 1, max: 10 }) },
		(_, i) => i + 1,
	).map(() => ({
		Tourn: {
			id: faker.number.int({ min: 0, max: 9007199254740991 }),
			name: faker.string.alpha({ length: { min: 10, max: 20 } }),
		},
		roundDate: faker.date.past().toISOString().slice(0, 19) + 'Z',
		roundLabel: faker.string.alpha({ length: { min: 10, max: 20 } }),
		eventAbbr: faker.string.alpha({ length: { min: 10, max: 20 } }),
		affTeam: faker.string.alpha({ length: { min: 10, max: 20 } }),
		affLabel: faker.string.alpha({ length: { min: 10, max: 20 } }),
		negTeam: faker.string.alpha({ length: { min: 10, max: 20 } }),
		negLabel: faker.string.alpha({ length: { min: 10, max: 20 } }),
		vote: faker.string.alpha({ length: { min: 10, max: 20 } }),
		panelVote: faker.string.alpha({ length: { min: 10, max: 20 } }),
		record: faker.string.alpha({ length: { min: 10, max: 20 } }),
	}));

export const getRestQuizzesResponseMock = (): QuizOutput[] =>
	Array.from(
		{ length: faker.number.int({ min: 1, max: 10 }) },
		(_, i) => i + 1,
	).map(() => ({
		id: faker.number.int({ min: 0, max: 9007199254740991 }),
		tag: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 63 } }),
			null,
		]),
		label: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 255 } }),
			null,
		]),
		description: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 511 } }),
			null,
		]),
		sitewide: faker.datatype.boolean(),
		hidden: faker.datatype.boolean(),
		approval: faker.datatype.boolean(),
		show_answers: faker.datatype.boolean(),
		admin_only: faker.datatype.boolean(),
		circuit: faker.helpers.arrayElement([
			faker.number.int({ min: 0, max: 9007199254740991 }),
			null,
		]),
		Badge: {
			altText: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				null,
			]),
			link: faker.helpers.arrayElement([faker.internet.url(), null]),
			imageUrl: faker.helpers.arrayElement([faker.internet.url(), null]),
		},
		PersonQuizzes: faker.helpers.arrayElement([
			Array.from(
				{ length: faker.number.int({ min: 1, max: 10 }) },
				(_, i) => i + 1,
			).map(() => ({
				id: faker.number.int({ min: 0, max: 9007199254740991 }),
				person: faker.number.int({ min: 0, max: 9007199254740991 }),
				quiz: faker.number.int({ min: 0, max: 9007199254740991 }),
				approvedBy: faker.helpers.arrayElement([
					faker.number.int({ min: 0, max: 9007199254740991 }),
					null,
				]),
				pending: faker.datatype.boolean(),
				updatedAt: faker.date.past().toISOString().slice(0, 19) + 'Z',
			})),
			undefined,
		]),
	}));

export const getRestStudentsUnlinkedSearchResponseMock =
	(): UnlinkedStudentSearch[] =>
		Array.from(
			{ length: faker.number.int({ min: 1, max: 10 }) },
			(_, i) => i + 1,
		).map(() => ({
			id: faker.number.int({ min: 0, max: 9007199254740991 }),
			first: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				null,
			]),
			middle: faker.helpers.arrayElement([
				faker.helpers.arrayElement([
					faker.string.alpha({ length: { min: 10, max: 20 } }),
					null,
				]),
				undefined,
			]),
			last: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				null,
			]),
			gradYear: faker.helpers.arrayElement([
				faker.helpers.arrayElement([
					faker.number.float({ fractionDigits: 2 }),
					null,
				]),
				undefined,
			]),
			Chapter: faker.helpers.arrayElement([
				{
					name: faker.helpers.arrayElement([
						faker.string.alpha({ length: { min: 10, max: 20 } }),
						null,
					]),
					state: faker.helpers.arrayElement([
						faker.string.alpha({ length: { min: 10, max: 20 } }),
						null,
					]),
				},
				null,
			]),
			tournCount: faker.helpers.arrayElement([
				faker.number.float({ fractionDigits: 2 }),
				null,
			]),
		}));

export const getAuthLoginResponseMock = (
	overrideResponse: Partial<Extract<LoginResponse, object>> = {},
): LoginResponse => ({
	token: faker.string.alpha({ length: { min: 10, max: 20 } }),
	Person: {
		id: faker.number.int({ min: -9007199254740991, max: 9007199254740991 }),
		email: faker.string.alpha({ length: { min: 10, max: 20 } }),
	},
	...overrideResponse,
});

export const getUserTournsResponseMock = (): Tourn[] =>
	Array.from(
		{ length: faker.number.int({ min: 1, max: 10 }) },
		(_, i) => i + 1,
	).map(() => ({
		id: faker.number.int({ min: 0, max: 9007199254740991 }),
		name: faker.string.alpha({ length: { min: 10, max: 63 } }),
		city: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 31 } }),
			null,
		]),
		state: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 6, max: 6 } }),
			null,
		]),
		country: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 4, max: 4 } }),
			null,
		]),
		tz: faker.string.alpha({ length: { min: 10, max: 31 } }),
		webname: faker.string.alpha({ length: { min: 10, max: 20 } }),
		hidden: faker.datatype.boolean(),
		start: faker.date.past().toISOString().slice(0, 19) + 'Z',
		end: faker.date.past().toISOString().slice(0, 19) + 'Z',
		regStart: faker.date.past().toISOString().slice(0, 19) + 'Z',
		regEnd: faker.date.past().toISOString().slice(0, 19) + 'Z',
	}));

export const getUserTournsSummaryResponseMock = (
	overrideResponse: Partial<Extract<PersonTournSummary, object>> = {},
): PersonTournSummary => ({
	id: faker.number.int({ min: 0, max: 9007199254740991 }),
	name: faker.string.alpha({ length: { min: 10, max: 63 } }),
	webname: faker.string.alpha({ length: { min: 10, max: 20 } }),
	start: faker.date.past().toISOString().slice(0, 19) + 'Z',
	end: faker.date.past().toISOString().slice(0, 19) + 'Z',
	tz: faker.string.alpha({ length: { min: 10, max: 31 } }),
	roles: faker.helpers.arrayElements(['student', 'coach', 'judge'] as const),
	livedoc: faker.helpers.arrayElement([
		{
			url: faker.string.alpha({ length: { min: 10, max: 20 } }),
			caption: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				null,
			]),
		},
		null,
	]),
	Judge: faker.helpers.arrayElement([
		{
			categoryName: faker.string.alpha({ length: { min: 10, max: 20 } }),
			schoolName: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				null,
			]),
		},
		null,
	]),
	...overrideResponse,
});

export const getUserTournsFinesResponseMock = (): Fine[] =>
	Array.from(
		{ length: faker.number.int({ min: 1, max: 10 }) },
		(_, i) => i + 1,
	).map(() => ({
		id: faker.number.int({ min: 0, max: 9007199254740991 }),
		reason: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 255 } }),
			null,
		]),
		amount: faker.helpers.arrayElement([
			faker.number.float({ fractionDigits: 2 }),
			null,
		]),
		school: faker.number.int({ min: 0, max: 9007199254740991 }),
		leviedAt: faker.date.past().toISOString().slice(0, 19) + 'Z',
	}));

export const getUserTournsBallotsResponseMock = (): CurrentBallot[] =>
	Array.from(
		{ length: faker.number.int({ min: 1, max: 10 }) },
		(_, i) => i + 1,
	).map(() => ({
		id: faker.number.int({ min: 0, max: 9007199254740991 }),
		flipStatus: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			null,
		]),
		flight: faker.helpers.arrayElement([
			faker.number.int({ min: 0, max: 9007199254740991 }),
			null,
		]),
		startText: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			null,
		]),
		show_async: faker.datatype.boolean(),
		legion: faker.datatype.boolean(),
		start: faker.date.past().toISOString().slice(0, 19) + 'Z',
		end: faker.date.past().toISOString().slice(0, 19) + 'Z',
		roomId: faker.helpers.arrayElement([
			faker.number.int({ min: 0, max: 9007199254740991 }),
			null,
		]),
		roomUrl: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 255 } }),
				null,
			]),
			null,
		]),
		roomNotes: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 63 } }),
				null,
			]),
			null,
		]),
		Judge: {
			id: faker.number.int({ min: 0, max: 9007199254740991 }),
			code: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 8, max: 8 } }),
				null,
			]),
			first: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 63 } }),
				null,
			]),
			last: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 63 } }),
				null,
			]),
		},
		Tourn: {
			id: faker.number.int({ min: 0, max: 9007199254740991 }),
			name: faker.string.alpha({ length: { min: 10, max: 63 } }),
			tz: faker.string.alpha({ length: { min: 10, max: 31 } }),
		},
		Category: {
			id: faker.number.int({ min: 0, max: 9007199254740991 }),
			name: faker.string.alpha({ length: { min: 10, max: 20 } }),
			abbr: faker.string.alpha({ length: { min: 10, max: 20 } }),
		},
		Event: {
			id: faker.number.int({ min: 0, max: 9007199254740991 }),
			name: faker.string.alpha({ length: { min: 10, max: 20 } }),
			abbr: faker.string.alpha({ length: { min: 10, max: 20 } }),
			type: faker.helpers.arrayElement([
				'debate',
				'speech',
				'mock_trial',
				'congress',
				'wsdc',
				'wudc',
				'attendee',
				'academic',
			] as const),
			settings: {
				flight_offset: faker.helpers.arrayElement([
					faker.number.int({
						min: -9007199254740991,
						max: 9007199254740991,
					}),
					null,
				]),
				online_mode: faker.helpers.arrayElement([
					faker.string.alpha({ length: { min: 10, max: 20 } }),
					null,
				]),
				online_ballots: faker.datatype.boolean(),
			},
		},
		Round: {
			id: faker.number.int({ min: 0, max: 9007199254740991 }),
			name: faker.helpers.arrayElement([
				faker.number.int({
					min: -9007199254740991,
					max: 9007199254740991,
				}),
				null,
			]),
			label: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 31 } }),
				null,
			]),
			flighted: faker.helpers.arrayElement([
				faker.datatype.boolean(),
				null,
			]),
		},
		Ballots: Array.from(
			{ length: faker.number.int({ min: 1, max: 10 }) },
			(_, i) => i + 1,
		).map(() => ({
			id: faker.number.int({ min: 0, max: 9007199254740991 }),
			side: faker.datatype.boolean(),
			speakerOrder: faker.number.int({ min: 0, max: 9007199254740991 }),
			chair: faker.datatype.boolean(),
		})),
		Entries: Array.from(
			{ length: faker.number.int({ min: 1, max: 10 }) },
			(_, i) => i + 1,
		).map(() => ({
			id: faker.number.int({ min: 0, max: 9007199254740991 }),
			code: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				null,
			]),
		})),
	}));

export const getUserInboxResponseMock = (): InboxMessage[] =>
	Array.from(
		{ length: faker.number.int({ min: 1, max: 10 }) },
		(_, i) => i + 1,
	).map(() => ({
		id: faker.number.int({ min: 0, max: 9007199254740991 }),
		subject: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 255 } }),
			null,
		]),
		body: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 65535 } }),
			null,
		]),
		url: faker.helpers.arrayElement([faker.internet.url(), null]),
		visibleAt: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			null,
		]),
		readAt: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			null,
		]),
		Tourn: faker.helpers.arrayElement([
			{
				id: faker.number.int({ min: 0, max: 9007199254740991 }),
				name: faker.helpers.arrayElement([
					faker.string.alpha({ length: { min: 10, max: 63 } }),
					null,
				]),
				webname: faker.helpers.arrayElement([
					faker.string.alpha({ length: { min: 10, max: 64 } }),
					null,
				]),
			},
			null,
		]),
		Sender: faker.helpers.arrayElement([
			{
				name: faker.helpers.arrayElement([
					faker.string.alpha({ length: { min: 10, max: 20 } }),
					null,
				]),
				email: faker.helpers.arrayElement([
					faker.string.alpha({ length: { min: 10, max: 127 } }),
					null,
				]),
			},
			null,
		]),
		Email: faker.helpers.arrayElement([
			{
				content: faker.helpers.arrayElement([
					faker.string.alpha({ length: { min: 10, max: 20 } }),
					null,
				]),
			},
			null,
		]),
	}));

export const getUserInboxUnreadResponseMock = (
	overrideResponse: Partial<Extract<UserInboxUnread200, object>> = {},
): UserInboxUnread200 => ({
	count: faker.helpers.arrayElement([faker.number.int(), undefined]),
	...overrideResponse,
});

export const getUserInboxGetMessageResponseMock = (
	overrideResponse: Partial<Extract<InboxMessage, object>> = {},
): InboxMessage => ({
	id: faker.number.int({ min: 0, max: 9007199254740991 }),
	subject: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 255 } }),
		null,
	]),
	body: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 65535 } }),
		null,
	]),
	url: faker.helpers.arrayElement([faker.internet.url(), null]),
	visibleAt: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		null,
	]),
	readAt: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		null,
	]),
	Tourn: faker.helpers.arrayElement([
		{
			id: faker.number.int({ min: 0, max: 9007199254740991 }),
			name: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 63 } }),
				null,
			]),
			webname: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 64 } }),
				null,
			]),
		},
		null,
	]),
	Sender: faker.helpers.arrayElement([
		{
			name: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				null,
			]),
			email: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 127 } }),
				null,
			]),
		},
		null,
	]),
	Email: faker.helpers.arrayElement([
		{
			content: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				null,
			]),
		},
		null,
	]),
	...overrideResponse,
});

export const getUserSessionResponseMock = (
	overrideResponse: Partial<Extract<Session, object>> = {},
): Session => ({
	id: faker.number.int({ min: 0, max: 9007199254740991 }),
	person: faker.number.int({ min: 0, max: 9007199254740991 }),
	su: faker.helpers.arrayElement([
		faker.number.int({ min: 0, max: 9007199254740991 }),
		null,
	]),
	Su: faker.helpers.arrayElement([
		{
			id: faker.number.int({ min: 0, max: 9007199254740991 }),
			email: faker.internet.email(),
			first: faker.string.alpha({ length: { min: 10, max: 20 } }),
			middle: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				null,
			]),
			last: faker.string.alpha({ length: { min: 10, max: 20 } }),
			state: faker.helpers.arrayElement([
				faker.helpers.arrayElement([
					faker.helpers.fromRegExp('^[A-Z]{2}$'),
					null,
				]),
				undefined,
			]),
			country: faker.helpers.arrayElement([
				faker.helpers.arrayElement([
					faker.string.alpha({ length: { min: 10, max: 20 } }),
					null,
				]),
				undefined,
			]),
			tz: faker.helpers.arrayElement([
				faker.helpers.arrayElement([
					faker.string.alpha({ length: { min: 10, max: 20 } }),
					null,
				]),
				undefined,
			]),
			createdAt: faker.date.past().toISOString().slice(0, 19) + 'Z',
			settings: faker.helpers.arrayElement([{}, undefined]),
			metadata: faker.helpers.arrayElement([{}, undefined]),
		},
		null,
	]),
	Person: {
		id: faker.number.int({ min: 0, max: 9007199254740991 }),
		email: faker.internet.email(),
		first: faker.string.alpha({ length: { min: 10, max: 20 } }),
		middle: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			null,
		]),
		last: faker.string.alpha({ length: { min: 10, max: 20 } }),
		state: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				faker.helpers.fromRegExp('^[A-Z]{2}$'),
				null,
			]),
			undefined,
		]),
		country: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				null,
			]),
			undefined,
		]),
		tz: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				null,
			]),
			undefined,
		]),
		createdAt: faker.date.past().toISOString().slice(0, 19) + 'Z',
		settings: faker.helpers.arrayElement([{}, undefined]),
		metadata: faker.helpers.arrayElement([{}, undefined]),
	},
	...overrideResponse,
});

export const getUserJudgesLinkRequestsResponseMock = (): UnlinkedJudge[] =>
	Array.from(
		{ length: faker.number.int({ min: 1, max: 10 }) },
		(_, i) => i + 1,
	).map(() => ({
		id: faker.number.int({ min: 0, max: 9007199254740991 }),
		type: faker.helpers.arrayElement(['judge', 'chapter_judge'] as const),
		first: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			null,
		]),
		last: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			null,
		]),
		schoolName: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				null,
			]),
			undefined,
		]),
		tournName: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				null,
			]),
			undefined,
		]),
		tournCount: faker.helpers.arrayElement([
			faker.number.int({ min: 0, max: 9007199254740991 }),
			undefined,
		]),
	}));

export const getUserJudgesClaimResponseMock = (
	overrideResponse: Partial<Extract<UserJudgesClaim200, object>> = {},
): UserJudgesClaim200 => ({
	message: faker.string.alpha({ length: { min: 10, max: 20 } }),
	detail: faker.string.alpha({ length: { min: 10, max: 20 } }),
	...overrideResponse,
});

export const getUserJudgesHistoryResponseMock = (
	overrideResponse: Partial<Extract<JudgeHistory, object>> = {},
): JudgeHistory => ({
	Tourn: {
		id: faker.number.int({ min: 0, max: 9007199254740991 }),
		name: faker.string.alpha({ length: { min: 10, max: 20 } }),
		start: faker.date.past().toISOString().slice(0, 19) + 'Z',
		end: faker.date.past().toISOString().slice(0, 19) + 'Z',
	},
	division: faker.string.alpha({ length: { min: 10, max: 20 } }),
	roundsJudged: faker.number.int({ min: 0, max: 9007199254740991 }),
	roundsObligated: faker.number.int({ min: 0, max: 9007199254740991 }),
	...overrideResponse,
});

export const getUserJudgesParadigmResponseMock = (
	overrideResponse: Partial<Extract<UserJudgesParadigm200, object>> = {},
): UserJudgesParadigm200 => ({
	paradigm: faker.string.alpha({ length: { min: 10, max: 20 } }),
	...overrideResponse,
});

export const getUserJudgesLiveDocsResponseMock =
	(): UserJudgesLiveDocs200Item[] =>
		Array.from(
			{ length: faker.number.int({ min: 1, max: 10 }) },
			(_, i) => i + 1,
		).map(() => ({
			judgeId: faker.number.int({ min: 0, max: 9007199254740991 }),
			categoryAbbr: faker.string.alpha({ length: { min: 10, max: 20 } }),
			tournName: faker.string.alpha({ length: { min: 10, max: 20 } }),
			tournEnd: faker.date.past().toISOString().slice(0, 19) + 'Z',
			tournTz: faker.string.alpha({ length: { min: 10, max: 20 } }),
			url: faker.string.alpha({ length: { min: 10, max: 20 } }),
			caption: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				null,
			]),
		}));

export const getUserStudentsLinkRequestsResponseMock = (): Student[] =>
	Array.from(
		{ length: faker.number.int({ min: 1, max: 10 }) },
		(_, i) => i + 1,
	).map(() => ({
		id: faker.number.int({ min: 0, max: 9007199254740991 }),
		first: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				null,
			]),
			undefined,
		]),
		middle: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				null,
			]),
			undefined,
		]),
		last: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				null,
			]),
			undefined,
		]),
		phonetic: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				null,
			]),
			undefined,
		]),
		gradYear: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				faker.number.float({ fractionDigits: 2 }),
				null,
			]),
			undefined,
		]),
		novice: faker.helpers.arrayElement([
			faker.datatype.boolean(),
			undefined,
		]),
		retired: faker.helpers.arrayElement([
			faker.datatype.boolean(),
			undefined,
		]),
		gender: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				null,
			]),
			undefined,
		]),
		nsda: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				faker.number.float({ fractionDigits: 2 }),
				null,
			]),
			undefined,
		]),
		chapterId: faker.number.int({ min: 0, max: 9007199254740991 }),
		personId: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				faker.number.int({ min: 0, max: 9007199254740991 }),
				null,
			]),
			undefined,
		]),
		Chapter: faker.helpers.arrayElement([
			{
				id: faker.number.int({ min: 0, max: 9007199254740991 }),
				name: faker.string.alpha({ length: { min: 10, max: 20 } }),
				formal: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						faker.string.alpha({ length: { min: 10, max: 20 } }),
						null,
					]),
					undefined,
				]),
				street: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						faker.string.alpha({ length: { min: 10, max: 20 } }),
						null,
					]),
					undefined,
				]),
				city: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						faker.string.alpha({ length: { min: 10, max: 20 } }),
						null,
					]),
					undefined,
				]),
				state: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						faker.string.alpha({ length: { min: 4, max: 4 } }),
						null,
					]),
					undefined,
				]),
				zip: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						faker.number.float({ fractionDigits: 2 }),
						null,
					]),
					undefined,
				]),
				postal: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						faker.string.alpha({ length: { min: 10, max: 15 } }),
						null,
					]),
					undefined,
				]),
				country: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						faker.string.alpha({ length: { min: 4, max: 4 } }),
						null,
					]),
					undefined,
				]),
				coaches: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						faker.string.alpha({ length: { min: 10, max: 20 } }),
						null,
					]),
					undefined,
				]),
				self_prefs: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						faker.datatype.boolean(),
						null,
					]),
					undefined,
				]),
				level: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						faker.string.alpha({ length: { min: 10, max: 20 } }),
						null,
					]),
					undefined,
				]),
				nsda: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						faker.number.float({ fractionDigits: 2 }),
						null,
					]),
					undefined,
				]),
				district: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						faker.number.float({ fractionDigits: 2 }),
						null,
					]),
					undefined,
				]),
				naudl: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						faker.datatype.boolean(),
						null,
					]),
					undefined,
				]),
				ipeds: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						faker.string.alpha({ length: { min: 10, max: 20 } }),
						null,
					]),
					undefined,
				]),
				nces: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						faker.string.alpha({ length: { min: 10, max: 20 } }),
						null,
					]),
					undefined,
				]),
				ceeb: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						faker.string.alpha({ length: { min: 10, max: 20 } }),
						null,
					]),
					undefined,
				]),
				timestamp: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						faker.string.alpha({ length: { min: 10, max: 20 } }),
						null,
					]),
					undefined,
				]),
				created_at: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						faker.string.alpha({ length: { min: 10, max: 20 } }),
						null,
					]),
					undefined,
				]),
			},
			undefined,
		]),
		Person: faker.helpers.arrayElement([
			{
				id: faker.number.int({ min: 0, max: 9007199254740991 }),
				email: faker.internet.email(),
				first: faker.string.alpha({ length: { min: 10, max: 20 } }),
				middle: faker.helpers.arrayElement([
					faker.string.alpha({ length: { min: 10, max: 20 } }),
					null,
				]),
				last: faker.string.alpha({ length: { min: 10, max: 20 } }),
				state: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						faker.helpers.fromRegExp('^[A-Z]{2}$'),
						null,
					]),
					undefined,
				]),
				country: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						faker.string.alpha({ length: { min: 10, max: 20 } }),
						null,
					]),
					undefined,
				]),
				tz: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						faker.string.alpha({ length: { min: 10, max: 20 } }),
						null,
					]),
					undefined,
				]),
				createdAt: faker.date.past().toISOString().slice(0, 19) + 'Z',
				settings: faker.helpers.arrayElement([{}, undefined]),
				metadata: faker.helpers.arrayElement([{}, undefined]),
			},
			undefined,
		]),
		createdAt: faker.string.alpha({ length: { min: 10, max: 20 } }),
		settings: faker.helpers.arrayElement([{}, undefined]),
		metadata: faker.helpers.arrayElement([{}, undefined]),
	}));

export const getUserStudentsClaimResponseMock = (
	overrideResponse: Partial<Extract<UserStudentsClaim200, object>> = {},
): UserStudentsClaim200 => ({
	message: faker.string.alpha({ length: { min: 10, max: 20 } }),
	detail: faker.string.alpha({ length: { min: 10, max: 20 } }),
	...overrideResponse,
});

export const getUserChaptersResponseMock = (): UserChapter[] =>
	Array.from(
		{ length: faker.number.int({ min: 1, max: 10 }) },
		(_, i) => i + 1,
	).map(() => ({
		id: faker.number.int({ min: 0, max: 9007199254740991 }),
		name: faker.string.alpha({ length: { min: 10, max: 20 } }),
		formal: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				null,
			]),
			undefined,
		]),
		street: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				null,
			]),
			undefined,
		]),
		city: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				null,
			]),
			undefined,
		]),
		state: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 4, max: 4 } }),
				null,
			]),
			undefined,
		]),
		zip: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				faker.number.float({ fractionDigits: 2 }),
				null,
			]),
			undefined,
		]),
		postal: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 15 } }),
				null,
			]),
			undefined,
		]),
		country: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 4, max: 4 } }),
				null,
			]),
			undefined,
		]),
		coaches: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				null,
			]),
			undefined,
		]),
		self_prefs: faker.helpers.arrayElement([
			faker.helpers.arrayElement([faker.datatype.boolean(), null]),
			undefined,
		]),
		level: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				null,
			]),
			undefined,
		]),
		nsda: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				faker.number.float({ fractionDigits: 2 }),
				null,
			]),
			undefined,
		]),
		district: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				faker.number.float({ fractionDigits: 2 }),
				null,
			]),
			undefined,
		]),
		naudl: faker.helpers.arrayElement([
			faker.helpers.arrayElement([faker.datatype.boolean(), null]),
			undefined,
		]),
		ipeds: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				null,
			]),
			undefined,
		]),
		nces: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				null,
			]),
			undefined,
		]),
		ceeb: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				null,
			]),
			undefined,
		]),
		timestamp: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				null,
			]),
			undefined,
		]),
		created_at: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				null,
			]),
			undefined,
		]),
		permission: faker.string.alpha({ length: { min: 10, max: 20 } }),
	}));
