/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */
import {
	createInfiniteQuery,
	createMutation,
	createQuery,
} from '@tanstack/svelte-query';
import type {
	CreateInfiniteQueryOptions,
	CreateInfiniteQueryResult,
	CreateMutationOptions,
	CreateMutationResult,
	CreateQueryOptions,
	CreateQueryResult,
	DataTag,
	InfiniteData,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
} from '@tanstack/svelte-query';

import type {
	AuthSuBody,
	BadRequestResponse,
	ErrorResponseResponse,
	JudgeRecord,
	LoginRequest,
	LoginResponse,
	NotFoundResponse,
	ParadigmDetails,
	RegisterRequest,
	RestAds200Item,
	RestCircuit,
	RestCircuitsActive200Item,
	RestCircuitsActiveParams,
	RestParadigms200Item,
	RestParadigmsParams,
	RestTournsParams,
	Session,
	Tourn,
	UnauthorizedResponse,
	UserInboxUnread200,
} from './schemas';

import { orvalMutator } from './utils';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export type HTTPStatusCode1xx = 100 | 101 | 102 | 103;
export type HTTPStatusCode2xx = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207;
export type HTTPStatusCode3xx = 300 | 301 | 302 | 303 | 304 | 305 | 307 | 308;
export type HTTPStatusCode4xx =
	| 400
	| 401
	| 402
	| 403
	| 404
	| 405
	| 406
	| 407
	| 408
	| 409
	| 410
	| 411
	| 412
	| 413
	| 414
	| 415
	| 416
	| 417
	| 418
	| 419
	| 420
	| 421
	| 422
	| 423
	| 424
	| 426
	| 428
	| 429
	| 431
	| 451;
export type HTTPStatusCode5xx = 500 | 501 | 502 | 503 | 504 | 505 | 507 | 511;
export type HTTPStatusCodes =
	| HTTPStatusCode1xx
	| HTTPStatusCode2xx
	| HTTPStatusCode3xx
	| HTTPStatusCode4xx
	| HTTPStatusCode5xx;

/**
 * Logs in a user and creates a session.
 * @summary Login
 */
export type authLoginResponse200 = {
	data: LoginResponse;
	status: 200;
};

export type authLoginResponse401 = {
	data: UnauthorizedResponse;
	status: 401;
};

export type authLoginResponse500 = {
	data: ErrorResponseResponse;
	status: 500;
};

export type authLoginResponseSuccess = authLoginResponse200 & {
	headers: Headers;
};
export type authLoginResponseError = (
	| authLoginResponse401
	| authLoginResponse500
) & {
	headers: Headers;
};

export type authLoginResponse =
	| authLoginResponseSuccess
	| authLoginResponseError;

export const getAuthLoginUrl = () => {
	return `/v1/auth/login`;
};

export const authLogin = async (
	loginRequest: LoginRequest,
	options?: RequestInit,
): Promise<authLoginResponse> => {
	return orvalMutator<authLoginResponse>(getAuthLoginUrl(), {
		credentials: 'include',
		...options,
		method: 'POST',
		headers: { 'Content-Type': 'application/json', ...options?.headers },
		body: JSON.stringify(loginRequest),
	});
};

export const getAuthLoginMutationOptions = <
	TError = UnauthorizedResponse | ErrorResponseResponse,
	TContext = unknown,
>(options?: {
	mutation?: CreateMutationOptions<
		Awaited<ReturnType<typeof authLogin>>,
		TError,
		{ data: LoginRequest },
		TContext
	>;
	request?: SecondParameter<typeof orvalMutator>;
}): CreateMutationOptions<
	Awaited<ReturnType<typeof authLogin>>,
	TError,
	{ data: LoginRequest },
	TContext
> => {
	const mutationKey = ['authLogin'];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			'mutationKey' in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof authLogin>>,
		{ data: LoginRequest }
	> = (props) => {
		const { data } = props ?? {};

		return authLogin(data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type AuthLoginMutationResult = NonNullable<
	Awaited<ReturnType<typeof authLogin>>
>;
export type AuthLoginMutationBody = LoginRequest;
export type AuthLoginMutationError =
	| UnauthorizedResponse
	| ErrorResponseResponse;

/**
 * @summary Login
 */
export const createAuthLogin = <
	TError = UnauthorizedResponse | ErrorResponseResponse,
	TContext = unknown,
>(
	options?: () => {
		mutation?: CreateMutationOptions<
			Awaited<ReturnType<typeof authLogin>>,
			TError,
			{ data: LoginRequest },
			TContext
		>;
		request?: SecondParameter<typeof orvalMutator>;
	},
	queryClient?: () => QueryClient,
): CreateMutationResult<
	Awaited<ReturnType<typeof authLogin>>,
	TError,
	{ data: LoginRequest },
	TContext
> => {
	return createMutation(
		() => ({ ...getAuthLoginMutationOptions(options?.()) }),
		queryClient,
	);
};

/**
 * Logs out the current user and invalidates the session.
 * @summary Logout
 */
export type authLogoutResponse204 = {
	data: void;
	status: 204;
};

export type authLogoutResponse401 = {
	data: UnauthorizedResponse;
	status: 401;
};

export type authLogoutResponse500 = {
	data: ErrorResponseResponse;
	status: 500;
};

export type authLogoutResponseSuccess = authLogoutResponse204 & {
	headers: Headers;
};
export type authLogoutResponseError = (
	| authLogoutResponse401
	| authLogoutResponse500
) & {
	headers: Headers;
};

export type authLogoutResponse =
	| authLogoutResponseSuccess
	| authLogoutResponseError;

export const getAuthLogoutUrl = () => {
	return `/v1/auth/logout`;
};

export const authLogout = async (
	options?: RequestInit,
): Promise<authLogoutResponse> => {
	return orvalMutator<authLogoutResponse>(getAuthLogoutUrl(), {
		credentials: 'include',
		...options,
		method: 'POST',
	});
};

export const getAuthLogoutMutationOptions = <
	TError = UnauthorizedResponse | ErrorResponseResponse,
	TContext = unknown,
>(options?: {
	mutation?: CreateMutationOptions<
		Awaited<ReturnType<typeof authLogout>>,
		TError,
		void,
		TContext
	>;
	request?: SecondParameter<typeof orvalMutator>;
}): CreateMutationOptions<
	Awaited<ReturnType<typeof authLogout>>,
	TError,
	void,
	TContext
> => {
	const mutationKey = ['authLogout'];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			'mutationKey' in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof authLogout>>,
		void
	> = () => {
		return authLogout(requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type AuthLogoutMutationResult = NonNullable<
	Awaited<ReturnType<typeof authLogout>>
>;

export type AuthLogoutMutationError =
	| UnauthorizedResponse
	| ErrorResponseResponse;

/**
 * @summary Logout
 */
export const createAuthLogout = <
	TError = UnauthorizedResponse | ErrorResponseResponse,
	TContext = unknown,
>(
	options?: () => {
		mutation?: CreateMutationOptions<
			Awaited<ReturnType<typeof authLogout>>,
			TError,
			void,
			TContext
		>;
		request?: SecondParameter<typeof orvalMutator>;
	},
	queryClient?: () => QueryClient,
): CreateMutationResult<
	Awaited<ReturnType<typeof authLogout>>,
	TError,
	void,
	TContext
> => {
	return createMutation(
		() => ({ ...getAuthLogoutMutationOptions(options?.()) }),
		queryClient,
	);
};

/**
 * POST /auth/su is undocumented. Need to add .openapi to handler
 * @summary Start Su session
 */
export type authSuResponse204 = {
	data: void;
	status: 204;
};

export type authSuResponse400 = {
	data: BadRequestResponse;
	status: 400;
};

export type authSuResponse401 = {
	data: UnauthorizedResponse;
	status: 401;
};

export type authSuResponse500 = {
	data: ErrorResponseResponse;
	status: 500;
};

export type authSuResponseSuccess = authSuResponse204 & {
	headers: Headers;
};
export type authSuResponseError = (
	| authSuResponse400
	| authSuResponse401
	| authSuResponse500
) & {
	headers: Headers;
};

export type authSuResponse = authSuResponseSuccess | authSuResponseError;

export const getAuthSuUrl = () => {
	return `/v1/auth/su`;
};

export const authSu = async (
	authSuBody: AuthSuBody,
	options?: RequestInit,
): Promise<authSuResponse> => {
	return orvalMutator<authSuResponse>(getAuthSuUrl(), {
		credentials: 'include',
		...options,
		method: 'POST',
		headers: { 'Content-Type': 'application/json', ...options?.headers },
		body: JSON.stringify(authSuBody),
	});
};

export const getAuthSuMutationOptions = <
	TError = BadRequestResponse | UnauthorizedResponse | ErrorResponseResponse,
	TContext = unknown,
>(options?: {
	mutation?: CreateMutationOptions<
		Awaited<ReturnType<typeof authSu>>,
		TError,
		{ data: AuthSuBody },
		TContext
	>;
	request?: SecondParameter<typeof orvalMutator>;
}): CreateMutationOptions<
	Awaited<ReturnType<typeof authSu>>,
	TError,
	{ data: AuthSuBody },
	TContext
> => {
	const mutationKey = ['authSu'];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			'mutationKey' in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof authSu>>,
		{ data: AuthSuBody }
	> = (props) => {
		const { data } = props ?? {};

		return authSu(data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type AuthSuMutationResult = NonNullable<
	Awaited<ReturnType<typeof authSu>>
>;
export type AuthSuMutationBody = AuthSuBody;
export type AuthSuMutationError =
	| BadRequestResponse
	| UnauthorizedResponse
	| ErrorResponseResponse;

/**
 * @summary Start Su session
 */
export const createAuthSu = <
	TError = BadRequestResponse | UnauthorizedResponse | ErrorResponseResponse,
	TContext = unknown,
>(
	options?: () => {
		mutation?: CreateMutationOptions<
			Awaited<ReturnType<typeof authSu>>,
			TError,
			{ data: AuthSuBody },
			TContext
		>;
		request?: SecondParameter<typeof orvalMutator>;
	},
	queryClient?: () => QueryClient,
): CreateMutationResult<
	Awaited<ReturnType<typeof authSu>>,
	TError,
	{ data: AuthSuBody },
	TContext
> => {
	return createMutation(
		() => ({ ...getAuthSuMutationOptions(options?.()) }),
		queryClient,
	);
};

/**
 * POST /auth/suend is undocumented. Need to add .openapi to handler
 * @summary End Su session
 */
export type authSuEndResponse204 = {
	data: void;
	status: 204;
};

export type authSuEndResponse400 = {
	data: BadRequestResponse;
	status: 400;
};

export type authSuEndResponse401 = {
	data: UnauthorizedResponse;
	status: 401;
};

export type authSuEndResponse500 = {
	data: ErrorResponseResponse;
	status: 500;
};

export type authSuEndResponseSuccess = authSuEndResponse204 & {
	headers: Headers;
};
export type authSuEndResponseError = (
	| authSuEndResponse400
	| authSuEndResponse401
	| authSuEndResponse500
) & {
	headers: Headers;
};

export type authSuEndResponse =
	| authSuEndResponseSuccess
	| authSuEndResponseError;

export const getAuthSuEndUrl = () => {
	return `/v1/auth/suend`;
};

export const authSuEnd = async (
	options?: RequestInit,
): Promise<authSuEndResponse> => {
	return orvalMutator<authSuEndResponse>(getAuthSuEndUrl(), {
		credentials: 'include',
		...options,
		method: 'POST',
	});
};

export const getAuthSuEndMutationOptions = <
	TError = BadRequestResponse | UnauthorizedResponse | ErrorResponseResponse,
	TContext = unknown,
>(options?: {
	mutation?: CreateMutationOptions<
		Awaited<ReturnType<typeof authSuEnd>>,
		TError,
		void,
		TContext
	>;
	request?: SecondParameter<typeof orvalMutator>;
}): CreateMutationOptions<
	Awaited<ReturnType<typeof authSuEnd>>,
	TError,
	void,
	TContext
> => {
	const mutationKey = ['authSuEnd'];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			'mutationKey' in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof authSuEnd>>,
		void
	> = () => {
		return authSuEnd(requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type AuthSuEndMutationResult = NonNullable<
	Awaited<ReturnType<typeof authSuEnd>>
>;

export type AuthSuEndMutationError =
	| BadRequestResponse
	| UnauthorizedResponse
	| ErrorResponseResponse;

/**
 * @summary End Su session
 */
export const createAuthSuEnd = <
	TError = BadRequestResponse | UnauthorizedResponse | ErrorResponseResponse,
	TContext = unknown,
>(
	options?: () => {
		mutation?: CreateMutationOptions<
			Awaited<ReturnType<typeof authSuEnd>>,
			TError,
			void,
			TContext
		>;
		request?: SecondParameter<typeof orvalMutator>;
	},
	queryClient?: () => QueryClient,
): CreateMutationResult<
	Awaited<ReturnType<typeof authSuEnd>>,
	TError,
	void,
	TContext
> => {
	return createMutation(
		() => ({ ...getAuthSuEndMutationOptions(options?.()) }),
		queryClient,
	);
};

/**
 * Registers a new user.
 * @summary Register
 */
export type authRegisterResponse200 = {
	data: void;
	status: 200;
};

export type authRegisterResponse401 = {
	data: UnauthorizedResponse;
	status: 401;
};

export type authRegisterResponse500 = {
	data: ErrorResponseResponse;
	status: 500;
};

export type authRegisterResponseSuccess = authRegisterResponse200 & {
	headers: Headers;
};
export type authRegisterResponseError = (
	| authRegisterResponse401
	| authRegisterResponse500
) & {
	headers: Headers;
};

export type authRegisterResponse =
	| authRegisterResponseSuccess
	| authRegisterResponseError;

export const getAuthRegisterUrl = () => {
	return `/v1/auth/register`;
};

export const authRegister = async (
	registerRequest: RegisterRequest,
	options?: RequestInit,
): Promise<authRegisterResponse> => {
	return orvalMutator<authRegisterResponse>(getAuthRegisterUrl(), {
		credentials: 'include',
		...options,
		method: 'POST',
		headers: { 'Content-Type': 'application/json', ...options?.headers },
		body: JSON.stringify(registerRequest),
	});
};

export const getAuthRegisterMutationOptions = <
	TError = UnauthorizedResponse | ErrorResponseResponse,
	TContext = unknown,
>(options?: {
	mutation?: CreateMutationOptions<
		Awaited<ReturnType<typeof authRegister>>,
		TError,
		{ data: RegisterRequest },
		TContext
	>;
	request?: SecondParameter<typeof orvalMutator>;
}): CreateMutationOptions<
	Awaited<ReturnType<typeof authRegister>>,
	TError,
	{ data: RegisterRequest },
	TContext
> => {
	const mutationKey = ['authRegister'];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			'mutationKey' in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof authRegister>>,
		{ data: RegisterRequest }
	> = (props) => {
		const { data } = props ?? {};

		return authRegister(data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type AuthRegisterMutationResult = NonNullable<
	Awaited<ReturnType<typeof authRegister>>
>;
export type AuthRegisterMutationBody = RegisterRequest;
export type AuthRegisterMutationError =
	| UnauthorizedResponse
	| ErrorResponseResponse;

/**
 * @summary Register
 */
export const createAuthRegister = <
	TError = UnauthorizedResponse | ErrorResponseResponse,
	TContext = unknown,
>(
	options?: () => {
		mutation?: CreateMutationOptions<
			Awaited<ReturnType<typeof authRegister>>,
			TError,
			{ data: RegisterRequest },
			TContext
		>;
		request?: SecondParameter<typeof orvalMutator>;
	},
	queryClient?: () => QueryClient,
): CreateMutationResult<
	Awaited<ReturnType<typeof authRegister>>,
	TError,
	{ data: RegisterRequest },
	TContext
> => {
	return createMutation(
		() => ({ ...getAuthRegisterMutationOptions(options?.()) }),
		queryClient,
	);
};

/**
 * returns an array of ads
 * @summary Get ads
 */
export type restAdsResponse200 = {
	data: RestAds200Item[];
	status: 200;
};

export type restAdsResponse401 = {
	data: UnauthorizedResponse;
	status: 401;
};

export type restAdsResponse500 = {
	data: ErrorResponseResponse;
	status: 500;
};

export type restAdsResponseDefault = {
	data: ErrorResponseResponse;
	status: Exclude<HTTPStatusCodes, 200 | 401 | 500>;
};

export type restAdsResponseSuccess = restAdsResponse200 & {
	headers: Headers;
};
export type restAdsResponseError = (
	| restAdsResponse401
	| restAdsResponse500
	| restAdsResponseDefault
) & {
	headers: Headers;
};

export type restAdsResponse = restAdsResponseSuccess | restAdsResponseError;

export const getRestAdsUrl = () => {
	return `/v1/rest/ads`;
};

export const restAds = async (
	options?: RequestInit,
): Promise<restAdsResponse> => {
	return orvalMutator<restAdsResponse>(getRestAdsUrl(), {
		credentials: 'include',
		...options,
		method: 'GET',
	});
};

export const getRestAdsInfiniteQueryKey = () => {
	return ['infinite', `/v1/rest/ads`] as const;
};

export const getRestAdsQueryKey = () => {
	return [`/v1/rest/ads`] as const;
};

export const getRestAdsInfiniteQueryOptions = <
	TData = InfiniteData<Awaited<ReturnType<typeof restAds>>>,
	TError = UnauthorizedResponse | ErrorResponseResponse,
>(options?: {
	query?: Partial<
		CreateInfiniteQueryOptions<
			Awaited<ReturnType<typeof restAds>>,
			TError,
			TData
		>
	>;
	request?: SecondParameter<typeof orvalMutator>;
}) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getRestAdsInfiniteQueryKey();

	const queryFn: QueryFunction<Awaited<ReturnType<typeof restAds>>> = ({
		signal,
	}) => restAds({ signal, ...requestOptions });

	return { queryKey, queryFn, ...queryOptions } as CreateInfiniteQueryOptions<
		Awaited<ReturnType<typeof restAds>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type RestAdsInfiniteQueryResult = NonNullable<
	Awaited<ReturnType<typeof restAds>>
>;
export type RestAdsInfiniteQueryError =
	| UnauthorizedResponse
	| ErrorResponseResponse;

/**
 * @summary Get ads
 */

export function createRestAdsInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof restAds>>>,
	TError = UnauthorizedResponse | ErrorResponseResponse,
>(
	options?: () => {
		query?: Partial<
			CreateInfiniteQueryOptions<
				Awaited<ReturnType<typeof restAds>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof orvalMutator>;
	},
	queryClient?: () => QueryClient,
): CreateInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const query = createInfiniteQuery(
		() => getRestAdsInfiniteQueryOptions(options?.()),
		queryClient,
	) as CreateInfiniteQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return query;
}

export const getRestAdsQueryOptions = <
	TData = Awaited<ReturnType<typeof restAds>>,
	TError = UnauthorizedResponse | ErrorResponseResponse,
>(options?: {
	query?: Partial<
		CreateQueryOptions<Awaited<ReturnType<typeof restAds>>, TError, TData>
	>;
	request?: SecondParameter<typeof orvalMutator>;
}) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getRestAdsQueryKey();

	const queryFn: QueryFunction<Awaited<ReturnType<typeof restAds>>> = ({
		signal,
	}) => restAds({ signal, ...requestOptions });

	return { queryKey, queryFn, ...queryOptions } as CreateQueryOptions<
		Awaited<ReturnType<typeof restAds>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type RestAdsQueryResult = NonNullable<
	Awaited<ReturnType<typeof restAds>>
>;
export type RestAdsQueryError = UnauthorizedResponse | ErrorResponseResponse;

/**
 * @summary Get ads
 */

export function createRestAds<
	TData = Awaited<ReturnType<typeof restAds>>,
	TError = UnauthorizedResponse | ErrorResponseResponse,
>(
	options?: () => {
		query?: Partial<
			CreateQueryOptions<
				Awaited<ReturnType<typeof restAds>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof orvalMutator>;
	},
	queryClient?: () => QueryClient,
): CreateQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const query = createQuery(
		() => getRestAdsQueryOptions(options?.()),
		queryClient,
	) as CreateQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return query;
}

/**
 * gets the active circuits for the current school year
 * @summary get active circuits
 */
export type restCircuitsActiveResponse200 = {
	data: RestCircuitsActive200Item[];
	status: 200;
};

export type restCircuitsActiveResponse401 = {
	data: UnauthorizedResponse;
	status: 401;
};

export type restCircuitsActiveResponse500 = {
	data: ErrorResponseResponse;
	status: 500;
};

export type restCircuitsActiveResponseSuccess =
	restCircuitsActiveResponse200 & {
		headers: Headers;
	};
export type restCircuitsActiveResponseError = (
	| restCircuitsActiveResponse401
	| restCircuitsActiveResponse500
) & {
	headers: Headers;
};

export type restCircuitsActiveResponse =
	| restCircuitsActiveResponseSuccess
	| restCircuitsActiveResponseError;

export const getRestCircuitsActiveUrl = (params?: RestCircuitsActiveParams) => {
	const normalizedParams = new URLSearchParams();

	Object.entries(params || {}).forEach(([key, value]) => {
		if (value !== undefined) {
			normalizedParams.append(
				key,
				value === null ? 'null' : value.toString(),
			);
		}
	});

	const stringifiedParams = normalizedParams.toString();

	return stringifiedParams.length > 0
		? `/v1/rest/circuits/active?${stringifiedParams}`
		: `/v1/rest/circuits/active`;
};

export const restCircuitsActive = async (
	params?: RestCircuitsActiveParams,
	options?: RequestInit,
): Promise<restCircuitsActiveResponse> => {
	return orvalMutator<restCircuitsActiveResponse>(
		getRestCircuitsActiveUrl(params),
		{
			credentials: 'include',
			...options,
			method: 'GET',
		},
	);
};

export const getRestCircuitsActiveInfiniteQueryKey = (
	params?: RestCircuitsActiveParams,
) => {
	return [
		'infinite',
		`/v1/rest/circuits/active`,
		...(params ? [params] : []),
	] as const;
};

export const getRestCircuitsActiveQueryKey = (
	params?: RestCircuitsActiveParams,
) => {
	return [`/v1/rest/circuits/active`, ...(params ? [params] : [])] as const;
};

export const getRestCircuitsActiveInfiniteQueryOptions = <
	TData = InfiniteData<
		Awaited<ReturnType<typeof restCircuitsActive>>,
		RestCircuitsActiveParams['offset']
	>,
	TError = UnauthorizedResponse | ErrorResponseResponse,
>(
	params?: RestCircuitsActiveParams,
	options?: {
		query?: Partial<
			CreateInfiniteQueryOptions<
				Awaited<ReturnType<typeof restCircuitsActive>>,
				TError,
				TData,
				QueryKey,
				RestCircuitsActiveParams['offset']
			>
		>;
		request?: SecondParameter<typeof orvalMutator>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getRestCircuitsActiveInfiniteQueryKey(params);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof restCircuitsActive>>,
		QueryKey,
		RestCircuitsActiveParams['offset']
	> = ({ signal, pageParam }) =>
		restCircuitsActive(
			{ ...params, offset: pageParam || params?.['offset'] },
			{ signal, ...requestOptions },
		);

	return { queryKey, queryFn, ...queryOptions } as CreateInfiniteQueryOptions<
		Awaited<ReturnType<typeof restCircuitsActive>>,
		TError,
		TData,
		QueryKey,
		RestCircuitsActiveParams['offset']
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type RestCircuitsActiveInfiniteQueryResult = NonNullable<
	Awaited<ReturnType<typeof restCircuitsActive>>
>;
export type RestCircuitsActiveInfiniteQueryError =
	| UnauthorizedResponse
	| ErrorResponseResponse;

/**
 * @summary get active circuits
 */

export function createRestCircuitsActiveInfinite<
	TData = InfiniteData<
		Awaited<ReturnType<typeof restCircuitsActive>>,
		RestCircuitsActiveParams['offset']
	>,
	TError = UnauthorizedResponse | ErrorResponseResponse,
>(
	params?: () => RestCircuitsActiveParams,
	options?: () => {
		query?: Partial<
			CreateInfiniteQueryOptions<
				Awaited<ReturnType<typeof restCircuitsActive>>,
				TError,
				TData,
				QueryKey,
				RestCircuitsActiveParams['offset']
			>
		>;
		request?: SecondParameter<typeof orvalMutator>;
	},
	queryClient?: () => QueryClient,
): CreateInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const query = createInfiniteQuery(
		() =>
			getRestCircuitsActiveInfiniteQueryOptions(params?.(), options?.()),
		queryClient,
	) as CreateInfiniteQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return query;
}

export const getRestCircuitsActiveQueryOptions = <
	TData = Awaited<ReturnType<typeof restCircuitsActive>>,
	TError = UnauthorizedResponse | ErrorResponseResponse,
>(
	params?: RestCircuitsActiveParams,
	options?: {
		query?: Partial<
			CreateQueryOptions<
				Awaited<ReturnType<typeof restCircuitsActive>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof orvalMutator>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getRestCircuitsActiveQueryKey(params);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof restCircuitsActive>>
	> = ({ signal }) =>
		restCircuitsActive(params, { signal, ...requestOptions });

	return { queryKey, queryFn, ...queryOptions } as CreateQueryOptions<
		Awaited<ReturnType<typeof restCircuitsActive>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type RestCircuitsActiveQueryResult = NonNullable<
	Awaited<ReturnType<typeof restCircuitsActive>>
>;
export type RestCircuitsActiveQueryError =
	| UnauthorizedResponse
	| ErrorResponseResponse;

/**
 * @summary get active circuits
 */

export function createRestCircuitsActive<
	TData = Awaited<ReturnType<typeof restCircuitsActive>>,
	TError = UnauthorizedResponse | ErrorResponseResponse,
>(
	params?: () => RestCircuitsActiveParams,
	options?: () => {
		query?: Partial<
			CreateQueryOptions<
				Awaited<ReturnType<typeof restCircuitsActive>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof orvalMutator>;
	},
	queryClient?: () => QueryClient,
): CreateQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const query = createQuery(
		() => getRestCircuitsActiveQueryOptions(params?.(), options?.()),
		queryClient,
	) as CreateQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return query;
}

/**
 * gets a circuit by ID
 * @summary get a circuit
 */
export type restCircuitResponse200 = {
	data: RestCircuit;
	status: 200;
};

export type restCircuitResponse401 = {
	data: UnauthorizedResponse;
	status: 401;
};

export type restCircuitResponse404 = {
	data: void;
	status: 404;
};

export type restCircuitResponse500 = {
	data: ErrorResponseResponse;
	status: 500;
};

export type restCircuitResponseSuccess = restCircuitResponse200 & {
	headers: Headers;
};
export type restCircuitResponseError = (
	| restCircuitResponse401
	| restCircuitResponse404
	| restCircuitResponse500
) & {
	headers: Headers;
};

export type restCircuitResponse =
	| restCircuitResponseSuccess
	| restCircuitResponseError;

export const getRestCircuitUrl = (circuitId: number) => {
	return `/v1/rest/circuits/${circuitId}`;
};

export const restCircuit = async (
	circuitId: number,
	options?: RequestInit,
): Promise<restCircuitResponse> => {
	return orvalMutator<restCircuitResponse>(getRestCircuitUrl(circuitId), {
		credentials: 'include',
		...options,
		method: 'GET',
	});
};

export const getRestCircuitInfiniteQueryKey = (circuitId: number) => {
	return ['infinite', `/v1/rest/circuits/${circuitId}`] as const;
};

export const getRestCircuitQueryKey = (circuitId: number) => {
	return [`/v1/rest/circuits/${circuitId}`] as const;
};

export const getRestCircuitInfiniteQueryOptions = <
	TData = InfiniteData<Awaited<ReturnType<typeof restCircuit>>>,
	TError = UnauthorizedResponse | void | ErrorResponseResponse,
>(
	circuitId: number,
	options?: {
		query?: Partial<
			CreateInfiniteQueryOptions<
				Awaited<ReturnType<typeof restCircuit>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof orvalMutator>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getRestCircuitInfiniteQueryKey(circuitId);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof restCircuit>>> = ({
		signal,
	}) => restCircuit(circuitId, { signal, ...requestOptions });

	return {
		queryKey,
		queryFn,
		enabled: !!circuitId,
		...queryOptions,
	} as CreateInfiniteQueryOptions<
		Awaited<ReturnType<typeof restCircuit>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type RestCircuitInfiniteQueryResult = NonNullable<
	Awaited<ReturnType<typeof restCircuit>>
>;
export type RestCircuitInfiniteQueryError =
	| UnauthorizedResponse
	| void
	| ErrorResponseResponse;

/**
 * @summary get a circuit
 */

export function createRestCircuitInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof restCircuit>>>,
	TError = UnauthorizedResponse | void | ErrorResponseResponse,
>(
	circuitId: () => number,
	options?: () => {
		query?: Partial<
			CreateInfiniteQueryOptions<
				Awaited<ReturnType<typeof restCircuit>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof orvalMutator>;
	},
	queryClient?: () => QueryClient,
): CreateInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const query = createInfiniteQuery(
		() => getRestCircuitInfiniteQueryOptions(circuitId(), options?.()),
		queryClient,
	) as CreateInfiniteQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return query;
}

export const getRestCircuitQueryOptions = <
	TData = Awaited<ReturnType<typeof restCircuit>>,
	TError = UnauthorizedResponse | void | ErrorResponseResponse,
>(
	circuitId: number,
	options?: {
		query?: Partial<
			CreateQueryOptions<
				Awaited<ReturnType<typeof restCircuit>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof orvalMutator>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getRestCircuitQueryKey(circuitId);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof restCircuit>>> = ({
		signal,
	}) => restCircuit(circuitId, { signal, ...requestOptions });

	return {
		queryKey,
		queryFn,
		enabled: !!circuitId,
		...queryOptions,
	} as CreateQueryOptions<
		Awaited<ReturnType<typeof restCircuit>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type RestCircuitQueryResult = NonNullable<
	Awaited<ReturnType<typeof restCircuit>>
>;
export type RestCircuitQueryError =
	| UnauthorizedResponse
	| void
	| ErrorResponseResponse;

/**
 * @summary get a circuit
 */

export function createRestCircuit<
	TData = Awaited<ReturnType<typeof restCircuit>>,
	TError = UnauthorizedResponse | void | ErrorResponseResponse,
>(
	circuitId: () => number,
	options?: () => {
		query?: Partial<
			CreateQueryOptions<
				Awaited<ReturnType<typeof restCircuit>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof orvalMutator>;
	},
	queryClient?: () => QueryClient,
): CreateQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const query = createQuery(
		() => getRestCircuitQueryOptions(circuitId(), options?.()),
		queryClient,
	) as CreateQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return query;
}

/**
 * Retrieve public information about tournaments.
 * @summary Get Public Tournaments
 */
export type restTournsResponse200 = {
	data: Tourn[];
	status: 200;
};

export type restTournsResponse401 = {
	data: UnauthorizedResponse;
	status: 401;
};

export type restTournsResponse404 = {
	data: NotFoundResponse;
	status: 404;
};

export type restTournsResponse500 = {
	data: ErrorResponseResponse;
	status: 500;
};

export type restTournsResponseSuccess = restTournsResponse200 & {
	headers: Headers;
};
export type restTournsResponseError = (
	| restTournsResponse401
	| restTournsResponse404
	| restTournsResponse500
) & {
	headers: Headers;
};

export type restTournsResponse =
	| restTournsResponseSuccess
	| restTournsResponseError;

export const getRestTournsUrl = (params?: RestTournsParams) => {
	const normalizedParams = new URLSearchParams();

	Object.entries(params || {}).forEach(([key, value]) => {
		if (value !== undefined) {
			normalizedParams.append(
				key,
				value === null ? 'null' : value.toString(),
			);
		}
	});

	const stringifiedParams = normalizedParams.toString();

	return stringifiedParams.length > 0
		? `/v1/rest/tourns?${stringifiedParams}`
		: `/v1/rest/tourns`;
};

export const restTourns = async (
	params?: RestTournsParams,
	options?: RequestInit,
): Promise<restTournsResponse> => {
	return orvalMutator<restTournsResponse>(getRestTournsUrl(params), {
		credentials: 'include',
		...options,
		method: 'GET',
	});
};

export const getRestTournsInfiniteQueryKey = (params?: RestTournsParams) => {
	return [
		'infinite',
		`/v1/rest/tourns`,
		...(params ? [params] : []),
	] as const;
};

export const getRestTournsQueryKey = (params?: RestTournsParams) => {
	return [`/v1/rest/tourns`, ...(params ? [params] : [])] as const;
};

export const getRestTournsInfiniteQueryOptions = <
	TData = InfiniteData<
		Awaited<ReturnType<typeof restTourns>>,
		RestTournsParams['offset']
	>,
	TError = UnauthorizedResponse | NotFoundResponse | ErrorResponseResponse,
>(
	params?: RestTournsParams,
	options?: {
		query?: Partial<
			CreateInfiniteQueryOptions<
				Awaited<ReturnType<typeof restTourns>>,
				TError,
				TData,
				QueryKey,
				RestTournsParams['offset']
			>
		>;
		request?: SecondParameter<typeof orvalMutator>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getRestTournsInfiniteQueryKey(params);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof restTourns>>,
		QueryKey,
		RestTournsParams['offset']
	> = ({ signal, pageParam }) =>
		restTourns(
			{ ...params, offset: pageParam || params?.['offset'] },
			{ signal, ...requestOptions },
		);

	return { queryKey, queryFn, ...queryOptions } as CreateInfiniteQueryOptions<
		Awaited<ReturnType<typeof restTourns>>,
		TError,
		TData,
		QueryKey,
		RestTournsParams['offset']
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type RestTournsInfiniteQueryResult = NonNullable<
	Awaited<ReturnType<typeof restTourns>>
>;
export type RestTournsInfiniteQueryError =
	| UnauthorizedResponse
	| NotFoundResponse
	| ErrorResponseResponse;

/**
 * @summary Get Public Tournaments
 */

export function createRestTournsInfinite<
	TData = InfiniteData<
		Awaited<ReturnType<typeof restTourns>>,
		RestTournsParams['offset']
	>,
	TError = UnauthorizedResponse | NotFoundResponse | ErrorResponseResponse,
>(
	params?: () => RestTournsParams,
	options?: () => {
		query?: Partial<
			CreateInfiniteQueryOptions<
				Awaited<ReturnType<typeof restTourns>>,
				TError,
				TData,
				QueryKey,
				RestTournsParams['offset']
			>
		>;
		request?: SecondParameter<typeof orvalMutator>;
	},
	queryClient?: () => QueryClient,
): CreateInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const query = createInfiniteQuery(
		() => getRestTournsInfiniteQueryOptions(params?.(), options?.()),
		queryClient,
	) as CreateInfiniteQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return query;
}

export const getRestTournsQueryOptions = <
	TData = Awaited<ReturnType<typeof restTourns>>,
	TError = UnauthorizedResponse | NotFoundResponse | ErrorResponseResponse,
>(
	params?: RestTournsParams,
	options?: {
		query?: Partial<
			CreateQueryOptions<
				Awaited<ReturnType<typeof restTourns>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof orvalMutator>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getRestTournsQueryKey(params);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof restTourns>>> = ({
		signal,
	}) => restTourns(params, { signal, ...requestOptions });

	return { queryKey, queryFn, ...queryOptions } as CreateQueryOptions<
		Awaited<ReturnType<typeof restTourns>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type RestTournsQueryResult = NonNullable<
	Awaited<ReturnType<typeof restTourns>>
>;
export type RestTournsQueryError =
	| UnauthorizedResponse
	| NotFoundResponse
	| ErrorResponseResponse;

/**
 * @summary Get Public Tournaments
 */

export function createRestTourns<
	TData = Awaited<ReturnType<typeof restTourns>>,
	TError = UnauthorizedResponse | NotFoundResponse | ErrorResponseResponse,
>(
	params?: () => RestTournsParams,
	options?: () => {
		query?: Partial<
			CreateQueryOptions<
				Awaited<ReturnType<typeof restTourns>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof orvalMutator>;
	},
	queryClient?: () => QueryClient,
): CreateQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const query = createQuery(
		() => getRestTournsQueryOptions(params?.(), options?.()),
		queryClient,
	) as CreateQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return query;
}

/**
 * GET /rest/paradigms is undocumented. Need to add .openapi to handler
 * @summary Search paradigms
 */
export type restParadigmsResponse200 = {
	data: RestParadigms200Item[];
	status: 200;
};

export type restParadigmsResponse401 = {
	data: UnauthorizedResponse;
	status: 401;
};

export type restParadigmsResponse500 = {
	data: ErrorResponseResponse;
	status: 500;
};

export type restParadigmsResponseSuccess = restParadigmsResponse200 & {
	headers: Headers;
};
export type restParadigmsResponseError = (
	| restParadigmsResponse401
	| restParadigmsResponse500
) & {
	headers: Headers;
};

export type restParadigmsResponse =
	| restParadigmsResponseSuccess
	| restParadigmsResponseError;

export const getRestParadigmsUrl = (params?: RestParadigmsParams) => {
	const normalizedParams = new URLSearchParams();

	Object.entries(params || {}).forEach(([key, value]) => {
		if (value !== undefined) {
			normalizedParams.append(
				key,
				value === null ? 'null' : value.toString(),
			);
		}
	});

	const stringifiedParams = normalizedParams.toString();

	return stringifiedParams.length > 0
		? `/v1/rest/paradigms?${stringifiedParams}`
		: `/v1/rest/paradigms`;
};

export const restParadigms = async (
	params?: RestParadigmsParams,
	options?: RequestInit,
): Promise<restParadigmsResponse> => {
	return orvalMutator<restParadigmsResponse>(getRestParadigmsUrl(params), {
		credentials: 'include',
		...options,
		method: 'GET',
	});
};

export const getRestParadigmsInfiniteQueryKey = (
	params?: RestParadigmsParams,
) => {
	return [
		'infinite',
		`/v1/rest/paradigms`,
		...(params ? [params] : []),
	] as const;
};

export const getRestParadigmsQueryKey = (params?: RestParadigmsParams) => {
	return [`/v1/rest/paradigms`, ...(params ? [params] : [])] as const;
};

export const getRestParadigmsInfiniteQueryOptions = <
	TData = InfiniteData<
		Awaited<ReturnType<typeof restParadigms>>,
		RestParadigmsParams['offset']
	>,
	TError = UnauthorizedResponse | ErrorResponseResponse,
>(
	params?: RestParadigmsParams,
	options?: {
		query?: Partial<
			CreateInfiniteQueryOptions<
				Awaited<ReturnType<typeof restParadigms>>,
				TError,
				TData,
				QueryKey,
				RestParadigmsParams['offset']
			>
		>;
		request?: SecondParameter<typeof orvalMutator>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getRestParadigmsInfiniteQueryKey(params);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof restParadigms>>,
		QueryKey,
		RestParadigmsParams['offset']
	> = ({ signal, pageParam }) =>
		restParadigms(
			{ ...params, offset: pageParam || params?.['offset'] },
			{ signal, ...requestOptions },
		);

	return { queryKey, queryFn, ...queryOptions } as CreateInfiniteQueryOptions<
		Awaited<ReturnType<typeof restParadigms>>,
		TError,
		TData,
		QueryKey,
		RestParadigmsParams['offset']
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type RestParadigmsInfiniteQueryResult = NonNullable<
	Awaited<ReturnType<typeof restParadigms>>
>;
export type RestParadigmsInfiniteQueryError =
	| UnauthorizedResponse
	| ErrorResponseResponse;

/**
 * @summary Search paradigms
 */

export function createRestParadigmsInfinite<
	TData = InfiniteData<
		Awaited<ReturnType<typeof restParadigms>>,
		RestParadigmsParams['offset']
	>,
	TError = UnauthorizedResponse | ErrorResponseResponse,
>(
	params?: () => RestParadigmsParams,
	options?: () => {
		query?: Partial<
			CreateInfiniteQueryOptions<
				Awaited<ReturnType<typeof restParadigms>>,
				TError,
				TData,
				QueryKey,
				RestParadigmsParams['offset']
			>
		>;
		request?: SecondParameter<typeof orvalMutator>;
	},
	queryClient?: () => QueryClient,
): CreateInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const query = createInfiniteQuery(
		() => getRestParadigmsInfiniteQueryOptions(params?.(), options?.()),
		queryClient,
	) as CreateInfiniteQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return query;
}

export const getRestParadigmsQueryOptions = <
	TData = Awaited<ReturnType<typeof restParadigms>>,
	TError = UnauthorizedResponse | ErrorResponseResponse,
>(
	params?: RestParadigmsParams,
	options?: {
		query?: Partial<
			CreateQueryOptions<
				Awaited<ReturnType<typeof restParadigms>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof orvalMutator>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getRestParadigmsQueryKey(params);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof restParadigms>>> = ({
		signal,
	}) => restParadigms(params, { signal, ...requestOptions });

	return { queryKey, queryFn, ...queryOptions } as CreateQueryOptions<
		Awaited<ReturnType<typeof restParadigms>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type RestParadigmsQueryResult = NonNullable<
	Awaited<ReturnType<typeof restParadigms>>
>;
export type RestParadigmsQueryError =
	| UnauthorizedResponse
	| ErrorResponseResponse;

/**
 * @summary Search paradigms
 */

export function createRestParadigms<
	TData = Awaited<ReturnType<typeof restParadigms>>,
	TError = UnauthorizedResponse | ErrorResponseResponse,
>(
	params?: () => RestParadigmsParams,
	options?: () => {
		query?: Partial<
			CreateQueryOptions<
				Awaited<ReturnType<typeof restParadigms>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof orvalMutator>;
	},
	queryClient?: () => QueryClient,
): CreateQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const query = createQuery(
		() => getRestParadigmsQueryOptions(params?.(), options?.()),
		queryClient,
	) as CreateQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return query;
}

/**
 * GET /rest/paradigms/{personId} is undocumented. Need to add .openapi to handler
 * @summary Get paradigm details by person ID
 */
export type restParadigmResponse200 = {
	data: ParadigmDetails;
	status: 200;
};

export type restParadigmResponse401 = {
	data: UnauthorizedResponse;
	status: 401;
};

export type restParadigmResponse404 = {
	data: NotFoundResponse;
	status: 404;
};

export type restParadigmResponse500 = {
	data: ErrorResponseResponse;
	status: 500;
};

export type restParadigmResponseDefault = {
	data: ErrorResponseResponse;
	status: Exclude<HTTPStatusCodes, 200 | 401 | 404 | 500>;
};

export type restParadigmResponseSuccess = restParadigmResponse200 & {
	headers: Headers;
};
export type restParadigmResponseError = (
	| restParadigmResponse401
	| restParadigmResponse404
	| restParadigmResponse500
	| restParadigmResponseDefault
) & {
	headers: Headers;
};

export type restParadigmResponse =
	| restParadigmResponseSuccess
	| restParadigmResponseError;

export const getRestParadigmUrl = (personId: number) => {
	return `/v1/rest/paradigms/${personId}`;
};

export const restParadigm = async (
	personId: number,
	options?: RequestInit,
): Promise<restParadigmResponse> => {
	return orvalMutator<restParadigmResponse>(getRestParadigmUrl(personId), {
		credentials: 'include',
		...options,
		method: 'GET',
	});
};

export const getRestParadigmInfiniteQueryKey = (personId: number) => {
	return ['infinite', `/v1/rest/paradigms/${personId}`] as const;
};

export const getRestParadigmQueryKey = (personId: number) => {
	return [`/v1/rest/paradigms/${personId}`] as const;
};

export const getRestParadigmInfiniteQueryOptions = <
	TData = InfiniteData<Awaited<ReturnType<typeof restParadigm>>>,
	TError = UnauthorizedResponse | NotFoundResponse | ErrorResponseResponse,
>(
	personId: number,
	options?: {
		query?: Partial<
			CreateInfiniteQueryOptions<
				Awaited<ReturnType<typeof restParadigm>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof orvalMutator>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getRestParadigmInfiniteQueryKey(personId);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof restParadigm>>> = ({
		signal,
	}) => restParadigm(personId, { signal, ...requestOptions });

	return {
		queryKey,
		queryFn,
		enabled: !!personId,
		...queryOptions,
	} as CreateInfiniteQueryOptions<
		Awaited<ReturnType<typeof restParadigm>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type RestParadigmInfiniteQueryResult = NonNullable<
	Awaited<ReturnType<typeof restParadigm>>
>;
export type RestParadigmInfiniteQueryError =
	| UnauthorizedResponse
	| NotFoundResponse
	| ErrorResponseResponse;

/**
 * @summary Get paradigm details by person ID
 */

export function createRestParadigmInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof restParadigm>>>,
	TError = UnauthorizedResponse | NotFoundResponse | ErrorResponseResponse,
>(
	personId: () => number,
	options?: () => {
		query?: Partial<
			CreateInfiniteQueryOptions<
				Awaited<ReturnType<typeof restParadigm>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof orvalMutator>;
	},
	queryClient?: () => QueryClient,
): CreateInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const query = createInfiniteQuery(
		() => getRestParadigmInfiniteQueryOptions(personId(), options?.()),
		queryClient,
	) as CreateInfiniteQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return query;
}

export const getRestParadigmQueryOptions = <
	TData = Awaited<ReturnType<typeof restParadigm>>,
	TError = UnauthorizedResponse | NotFoundResponse | ErrorResponseResponse,
>(
	personId: number,
	options?: {
		query?: Partial<
			CreateQueryOptions<
				Awaited<ReturnType<typeof restParadigm>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof orvalMutator>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getRestParadigmQueryKey(personId);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof restParadigm>>> = ({
		signal,
	}) => restParadigm(personId, { signal, ...requestOptions });

	return {
		queryKey,
		queryFn,
		enabled: !!personId,
		...queryOptions,
	} as CreateQueryOptions<
		Awaited<ReturnType<typeof restParadigm>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type RestParadigmQueryResult = NonNullable<
	Awaited<ReturnType<typeof restParadigm>>
>;
export type RestParadigmQueryError =
	| UnauthorizedResponse
	| NotFoundResponse
	| ErrorResponseResponse;

/**
 * @summary Get paradigm details by person ID
 */

export function createRestParadigm<
	TData = Awaited<ReturnType<typeof restParadigm>>,
	TError = UnauthorizedResponse | NotFoundResponse | ErrorResponseResponse,
>(
	personId: () => number,
	options?: () => {
		query?: Partial<
			CreateQueryOptions<
				Awaited<ReturnType<typeof restParadigm>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof orvalMutator>;
	},
	queryClient?: () => QueryClient,
): CreateQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const query = createQuery(
		() => getRestParadigmQueryOptions(personId(), options?.()),
		queryClient,
	) as CreateQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return query;
}

/**
 * GET /rest/paradigms/{personId}/record is undocumented. Need to add .openapi to handler
 * @summary Get judging record by person ID
 */
export type restParadigmsRecordResponse200 = {
	data: JudgeRecord[];
	status: 200;
};

export type restParadigmsRecordResponse401 = {
	data: UnauthorizedResponse;
	status: 401;
};

export type restParadigmsRecordResponse500 = {
	data: ErrorResponseResponse;
	status: 500;
};

export type restParadigmsRecordResponseSuccess =
	restParadigmsRecordResponse200 & {
		headers: Headers;
	};
export type restParadigmsRecordResponseError = (
	| restParadigmsRecordResponse401
	| restParadigmsRecordResponse500
) & {
	headers: Headers;
};

export type restParadigmsRecordResponse =
	| restParadigmsRecordResponseSuccess
	| restParadigmsRecordResponseError;

export const getRestParadigmsRecordUrl = (personId: number) => {
	return `/v1/rest/paradigms/${personId}/record`;
};

export const restParadigmsRecord = async (
	personId: number,
	options?: RequestInit,
): Promise<restParadigmsRecordResponse> => {
	return orvalMutator<restParadigmsRecordResponse>(
		getRestParadigmsRecordUrl(personId),
		{
			credentials: 'include',
			...options,
			method: 'GET',
		},
	);
};

export const getRestParadigmsRecordInfiniteQueryKey = (personId: number) => {
	return ['infinite', `/v1/rest/paradigms/${personId}/record`] as const;
};

export const getRestParadigmsRecordQueryKey = (personId: number) => {
	return [`/v1/rest/paradigms/${personId}/record`] as const;
};

export const getRestParadigmsRecordInfiniteQueryOptions = <
	TData = InfiniteData<Awaited<ReturnType<typeof restParadigmsRecord>>>,
	TError = UnauthorizedResponse | ErrorResponseResponse,
>(
	personId: number,
	options?: {
		query?: Partial<
			CreateInfiniteQueryOptions<
				Awaited<ReturnType<typeof restParadigmsRecord>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof orvalMutator>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ??
		getRestParadigmsRecordInfiniteQueryKey(personId);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof restParadigmsRecord>>
	> = ({ signal }) =>
		restParadigmsRecord(personId, { signal, ...requestOptions });

	return {
		queryKey,
		queryFn,
		enabled: !!personId,
		...queryOptions,
	} as CreateInfiniteQueryOptions<
		Awaited<ReturnType<typeof restParadigmsRecord>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type RestParadigmsRecordInfiniteQueryResult = NonNullable<
	Awaited<ReturnType<typeof restParadigmsRecord>>
>;
export type RestParadigmsRecordInfiniteQueryError =
	| UnauthorizedResponse
	| ErrorResponseResponse;

/**
 * @summary Get judging record by person ID
 */

export function createRestParadigmsRecordInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof restParadigmsRecord>>>,
	TError = UnauthorizedResponse | ErrorResponseResponse,
>(
	personId: () => number,
	options?: () => {
		query?: Partial<
			CreateInfiniteQueryOptions<
				Awaited<ReturnType<typeof restParadigmsRecord>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof orvalMutator>;
	},
	queryClient?: () => QueryClient,
): CreateInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const query = createInfiniteQuery(
		() =>
			getRestParadigmsRecordInfiniteQueryOptions(personId(), options?.()),
		queryClient,
	) as CreateInfiniteQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return query;
}

export const getRestParadigmsRecordQueryOptions = <
	TData = Awaited<ReturnType<typeof restParadigmsRecord>>,
	TError = UnauthorizedResponse | ErrorResponseResponse,
>(
	personId: number,
	options?: {
		query?: Partial<
			CreateQueryOptions<
				Awaited<ReturnType<typeof restParadigmsRecord>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof orvalMutator>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getRestParadigmsRecordQueryKey(personId);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof restParadigmsRecord>>
	> = ({ signal }) =>
		restParadigmsRecord(personId, { signal, ...requestOptions });

	return {
		queryKey,
		queryFn,
		enabled: !!personId,
		...queryOptions,
	} as CreateQueryOptions<
		Awaited<ReturnType<typeof restParadigmsRecord>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type RestParadigmsRecordQueryResult = NonNullable<
	Awaited<ReturnType<typeof restParadigmsRecord>>
>;
export type RestParadigmsRecordQueryError =
	| UnauthorizedResponse
	| ErrorResponseResponse;

/**
 * @summary Get judging record by person ID
 */

export function createRestParadigmsRecord<
	TData = Awaited<ReturnType<typeof restParadigmsRecord>>,
	TError = UnauthorizedResponse | ErrorResponseResponse,
>(
	personId: () => number,
	options?: () => {
		query?: Partial<
			CreateQueryOptions<
				Awaited<ReturnType<typeof restParadigmsRecord>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof orvalMutator>;
	},
	queryClient?: () => QueryClient,
): CreateQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const query = createQuery(
		() => getRestParadigmsRecordQueryOptions(personId(), options?.()),
		queryClient,
	) as CreateQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return query;
}

/**
 * GET /user/inbox/unread is undocumented. Need to add .openapi to handler
 * @summary GET /user/inbox/unread
 */
export type userInboxUnreadResponse200 = {
	data: UserInboxUnread200;
	status: 200;
};

export type userInboxUnreadResponse401 = {
	data: UnauthorizedResponse;
	status: 401;
};

export type userInboxUnreadResponse500 = {
	data: ErrorResponseResponse;
	status: 500;
};

export type userInboxUnreadResponseSuccess = userInboxUnreadResponse200 & {
	headers: Headers;
};
export type userInboxUnreadResponseError = (
	| userInboxUnreadResponse401
	| userInboxUnreadResponse500
) & {
	headers: Headers;
};

export type userInboxUnreadResponse =
	| userInboxUnreadResponseSuccess
	| userInboxUnreadResponseError;

export const getUserInboxUnreadUrl = () => {
	return `/v1/user/inbox/unread`;
};

export const userInboxUnread = async (
	options?: RequestInit,
): Promise<userInboxUnreadResponse> => {
	return orvalMutator<userInboxUnreadResponse>(getUserInboxUnreadUrl(), {
		credentials: 'include',
		...options,
		method: 'GET',
	});
};

export const getUserInboxUnreadInfiniteQueryKey = () => {
	return ['infinite', `/v1/user/inbox/unread`] as const;
};

export const getUserInboxUnreadQueryKey = () => {
	return [`/v1/user/inbox/unread`] as const;
};

export const getUserInboxUnreadInfiniteQueryOptions = <
	TData = InfiniteData<Awaited<ReturnType<typeof userInboxUnread>>>,
	TError = UnauthorizedResponse | ErrorResponseResponse,
>(options?: {
	query?: Partial<
		CreateInfiniteQueryOptions<
			Awaited<ReturnType<typeof userInboxUnread>>,
			TError,
			TData
		>
	>;
	request?: SecondParameter<typeof orvalMutator>;
}) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getUserInboxUnreadInfiniteQueryKey();

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof userInboxUnread>>
	> = ({ signal }) => userInboxUnread({ signal, ...requestOptions });

	return { queryKey, queryFn, ...queryOptions } as CreateInfiniteQueryOptions<
		Awaited<ReturnType<typeof userInboxUnread>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type UserInboxUnreadInfiniteQueryResult = NonNullable<
	Awaited<ReturnType<typeof userInboxUnread>>
>;
export type UserInboxUnreadInfiniteQueryError =
	| UnauthorizedResponse
	| ErrorResponseResponse;

/**
 * @summary GET /user/inbox/unread
 */

export function createUserInboxUnreadInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof userInboxUnread>>>,
	TError = UnauthorizedResponse | ErrorResponseResponse,
>(
	options?: () => {
		query?: Partial<
			CreateInfiniteQueryOptions<
				Awaited<ReturnType<typeof userInboxUnread>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof orvalMutator>;
	},
	queryClient?: () => QueryClient,
): CreateInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const query = createInfiniteQuery(
		() => getUserInboxUnreadInfiniteQueryOptions(options?.()),
		queryClient,
	) as CreateInfiniteQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return query;
}

export const getUserInboxUnreadQueryOptions = <
	TData = Awaited<ReturnType<typeof userInboxUnread>>,
	TError = UnauthorizedResponse | ErrorResponseResponse,
>(options?: {
	query?: Partial<
		CreateQueryOptions<
			Awaited<ReturnType<typeof userInboxUnread>>,
			TError,
			TData
		>
	>;
	request?: SecondParameter<typeof orvalMutator>;
}) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getUserInboxUnreadQueryKey();

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof userInboxUnread>>
	> = ({ signal }) => userInboxUnread({ signal, ...requestOptions });

	return { queryKey, queryFn, ...queryOptions } as CreateQueryOptions<
		Awaited<ReturnType<typeof userInboxUnread>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type UserInboxUnreadQueryResult = NonNullable<
	Awaited<ReturnType<typeof userInboxUnread>>
>;
export type UserInboxUnreadQueryError =
	| UnauthorizedResponse
	| ErrorResponseResponse;

/**
 * @summary GET /user/inbox/unread
 */

export function createUserInboxUnread<
	TData = Awaited<ReturnType<typeof userInboxUnread>>,
	TError = UnauthorizedResponse | ErrorResponseResponse,
>(
	options?: () => {
		query?: Partial<
			CreateQueryOptions<
				Awaited<ReturnType<typeof userInboxUnread>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof orvalMutator>;
	},
	queryClient?: () => QueryClient,
): CreateQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const query = createQuery(
		() => getUserInboxUnreadQueryOptions(options?.()),
		queryClient,
	) as CreateQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return query;
}

/**
 * GET /user/session is undocumented. Need to add .openapi to handler
 * @summary GET /user/session
 */
export type userSessionResponse200 = {
	data: Session;
	status: 200;
};

export type userSessionResponse401 = {
	data: UnauthorizedResponse;
	status: 401;
};

export type userSessionResponse500 = {
	data: ErrorResponseResponse;
	status: 500;
};

export type userSessionResponseDefault = {
	data: ErrorResponseResponse;
	status: Exclude<HTTPStatusCodes, 200 | 401 | 500>;
};

export type userSessionResponseSuccess = userSessionResponse200 & {
	headers: Headers;
};
export type userSessionResponseError = (
	| userSessionResponse401
	| userSessionResponse500
	| userSessionResponseDefault
) & {
	headers: Headers;
};

export type userSessionResponse =
	| userSessionResponseSuccess
	| userSessionResponseError;

export const getUserSessionUrl = () => {
	return `/v1/user/session`;
};

export const userSession = async (
	options?: RequestInit,
): Promise<userSessionResponse> => {
	return orvalMutator<userSessionResponse>(getUserSessionUrl(), {
		credentials: 'include',
		...options,
		method: 'GET',
	});
};

export const getUserSessionInfiniteQueryKey = () => {
	return ['infinite', `/v1/user/session`] as const;
};

export const getUserSessionQueryKey = () => {
	return [`/v1/user/session`] as const;
};

export const getUserSessionInfiniteQueryOptions = <
	TData = InfiniteData<Awaited<ReturnType<typeof userSession>>>,
	TError = UnauthorizedResponse | ErrorResponseResponse,
>(options?: {
	query?: Partial<
		CreateInfiniteQueryOptions<
			Awaited<ReturnType<typeof userSession>>,
			TError,
			TData
		>
	>;
	request?: SecondParameter<typeof orvalMutator>;
}) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getUserSessionInfiniteQueryKey();

	const queryFn: QueryFunction<Awaited<ReturnType<typeof userSession>>> = ({
		signal,
	}) => userSession({ signal, ...requestOptions });

	return { queryKey, queryFn, ...queryOptions } as CreateInfiniteQueryOptions<
		Awaited<ReturnType<typeof userSession>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type UserSessionInfiniteQueryResult = NonNullable<
	Awaited<ReturnType<typeof userSession>>
>;
export type UserSessionInfiniteQueryError =
	| UnauthorizedResponse
	| ErrorResponseResponse;

/**
 * @summary GET /user/session
 */

export function createUserSessionInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof userSession>>>,
	TError = UnauthorizedResponse | ErrorResponseResponse,
>(
	options?: () => {
		query?: Partial<
			CreateInfiniteQueryOptions<
				Awaited<ReturnType<typeof userSession>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof orvalMutator>;
	},
	queryClient?: () => QueryClient,
): CreateInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const query = createInfiniteQuery(
		() => getUserSessionInfiniteQueryOptions(options?.()),
		queryClient,
	) as CreateInfiniteQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return query;
}

export const getUserSessionQueryOptions = <
	TData = Awaited<ReturnType<typeof userSession>>,
	TError = UnauthorizedResponse | ErrorResponseResponse,
>(options?: {
	query?: Partial<
		CreateQueryOptions<
			Awaited<ReturnType<typeof userSession>>,
			TError,
			TData
		>
	>;
	request?: SecondParameter<typeof orvalMutator>;
}) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getUserSessionQueryKey();

	const queryFn: QueryFunction<Awaited<ReturnType<typeof userSession>>> = ({
		signal,
	}) => userSession({ signal, ...requestOptions });

	return { queryKey, queryFn, ...queryOptions } as CreateQueryOptions<
		Awaited<ReturnType<typeof userSession>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type UserSessionQueryResult = NonNullable<
	Awaited<ReturnType<typeof userSession>>
>;
export type UserSessionQueryError =
	| UnauthorizedResponse
	| ErrorResponseResponse;

/**
 * @summary GET /user/session
 */

export function createUserSession<
	TData = Awaited<ReturnType<typeof userSession>>,
	TError = UnauthorizedResponse | ErrorResponseResponse,
>(
	options?: () => {
		query?: Partial<
			CreateQueryOptions<
				Awaited<ReturnType<typeof userSession>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof orvalMutator>;
	},
	queryClient?: () => QueryClient,
): CreateQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const query = createQuery(
		() => getUserSessionQueryOptions(options?.()),
		queryClient,
	) as CreateQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return query;
}
