/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */
import { faker } from '@faker-js/faker';

import { HttpResponse, http } from 'msw';
import type { RequestHandlerOptions } from 'msw';

import type {
	ParadigmDetails,
	RestCircuitsActive200Item,
	RestParadigms200Item,
	Session,
	Tourn,
	UserInboxUnread200,
} from './schemas';

export const getRestCircuitsActiveResponseMock =
	(): RestCircuitsActive200Item[] =>
		Array.from(
			{ length: faker.number.int({ min: 1, max: 10 }) },
			(_, i) => i + 1,
		).map(() => ({
			id: faker.helpers.arrayElement([faker.number.int(), undefined]),
			abbr: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				undefined,
			]),
			name: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				undefined,
			]),
			state: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				undefined,
			]),
			country: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				undefined,
			]),
			tournCount: faker.helpers.arrayElement([
				faker.number.int(),
				undefined,
			]),
		}));

export const getRestTournsResponseMock = (): Tourn[] =>
	Array.from(
		{ length: faker.number.int({ min: 1, max: 10 }) },
		(_, i) => i + 1,
	).map(() => ({
		id: faker.helpers.arrayElement([faker.number.int(), undefined]),
		name: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			undefined,
		]),
		city: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			undefined,
		]),
		state: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			undefined,
		]),
		country: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			undefined,
		]),
		tz: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			undefined,
		]),
		webName: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			undefined,
		]),
		start: faker.helpers.arrayElement([
			faker.date.past().toISOString().slice(0, 19) + 'Z',
			undefined,
		]),
		end: faker.helpers.arrayElement([
			faker.date.past().toISOString().slice(0, 19) + 'Z',
			undefined,
		]),
		regStart: faker.helpers.arrayElement([
			faker.date.past().toISOString().slice(0, 19) + 'Z',
			undefined,
		]),
		regEnd: faker.helpers.arrayElement([
			faker.date.past().toISOString().slice(0, 19) + 'Z',
			undefined,
		]),
	}));

export const getRestParadigmsResponseMock = (): RestParadigms200Item[] =>
	Array.from(
		{ length: faker.number.int({ min: 1, max: 10 }) },
		(_, i) => i + 1,
	).map(() => ({
		id: faker.helpers.arrayElement([faker.number.int(), undefined]),
		name: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			undefined,
		]),
		tournJudged: faker.helpers.arrayElement([
			faker.number.int(),
			undefined,
		]),
		schools: faker.helpers.arrayElement([
			Array.from(
				{ length: faker.number.int({ min: 1, max: 10 }) },
				(_, i) => i + 1,
			).map(() => ({
				id: faker.helpers.arrayElement([faker.number.int(), undefined]),
				name: faker.helpers.arrayElement([
					faker.string.alpha({ length: { min: 10, max: 20 } }),
					undefined,
				]),
			})),
			undefined,
		]),
	}));

export const getRestParadigmResponseMock = (
	overrideResponse: Partial<Extract<ParadigmDetails, object>> = {},
): ParadigmDetails => ({
	id: faker.number.int(),
	name: faker.string.alpha({ length: { min: 10, max: 20 } }),
	lastReviewed: faker.date.past().toISOString().slice(0, 19) + 'Z',
	paradigm: faker.string.alpha({ length: { min: 10, max: 20 } }),
	record: Array.from(
		{ length: faker.number.int({ min: 1, max: 10 }) },
		(_, i) => i + 1,
	).map(() => ({
		tournName: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			undefined,
		]),
		roundDate: faker.helpers.arrayElement([
			faker.date.past().toISOString().slice(0, 19) + 'Z',
			undefined,
		]),
		roundLabel: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			undefined,
		]),
		eventAbbr: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			undefined,
		]),
		affTeam: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			undefined,
		]),
		affLabel: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			undefined,
		]),
		negTeam: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			undefined,
		]),
		negLabel: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			undefined,
		]),
		vote: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			undefined,
		]),
		panelVote: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			undefined,
		]),
		record: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			undefined,
		]),
	})),
	certifications: Array.from(
		{ length: faker.number.int({ min: 1, max: 10 }) },
		(_, i) => i + 1,
	).map(() => ({
		title: faker.string.alpha({ length: { min: 10, max: 20 } }),
		description: faker.string.alpha({ length: { min: 10, max: 20 } }),
		updatedAt: faker.helpers.arrayElement([
			faker.date.past().toISOString().slice(0, 19) + 'Z',
			undefined,
		]),
		badge: faker.helpers.arrayElement([
			{
				altText: faker.helpers.arrayElement([
					faker.string.alpha({ length: { min: 10, max: 20 } }),
					undefined,
				]),
				link: faker.helpers.arrayElement([
					faker.internet.url(),
					undefined,
				]),
				imageUrl: faker.helpers.arrayElement([
					faker.internet.url(),
					undefined,
				]),
			},
			undefined,
		]),
	})),
	...overrideResponse,
});

export const getUserInboxUnreadResponseMock = (
	overrideResponse: Partial<Extract<UserInboxUnread200, object>> = {},
): UserInboxUnread200 => ({
	count: faker.helpers.arrayElement([faker.number.int(), undefined]),
	...overrideResponse,
});

export const getUserSessionResponseMock = (
	overrideResponse: Partial<Extract<Session, object>> = {},
): Session => ({
	id: faker.helpers.arrayElement([faker.number.int(), undefined]),
	personId: faker.helpers.arrayElement([faker.number.int(), undefined]),
	suId: faker.helpers.arrayElement([faker.number.int(), null]),
	Su: faker.helpers.arrayElement([
		{
			id: faker.helpers.arrayElement([faker.number.int(), undefined]),
			email: faker.helpers.arrayElement([
				faker.internet.email(),
				undefined,
			]),
			firstName: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				undefined,
			]),
			middleName: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				null,
			]),
			lastName: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				undefined,
			]),
			state: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				undefined,
			]),
			country: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				undefined,
			]),
			tz: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				undefined,
			]),
		},
		null,
	]),
	Person: faker.helpers.arrayElement([
		{
			id: faker.helpers.arrayElement([faker.number.int(), undefined]),
			email: faker.helpers.arrayElement([
				faker.internet.email(),
				undefined,
			]),
			firstName: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				undefined,
			]),
			middleName: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				null,
			]),
			lastName: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				undefined,
			]),
			state: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				undefined,
			]),
			country: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				undefined,
			]),
			tz: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				undefined,
			]),
		},
		undefined,
	]),
	...overrideResponse,
});

export const getAuthLoginMockHandler = (
	overrideResponse?:
		| void
		| ((
				info: Parameters<Parameters<typeof http.post>[1]>[0],
		  ) => Promise<void> | void),
	options?: RequestHandlerOptions,
) => {
	return http.post(
		'*/auth/login',
		async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
			if (typeof overrideResponse === 'function') {
				await overrideResponse(info);
			}

			return new HttpResponse(null, { status: 200 });
		},
		options,
	);
};

export const getAuthLogoutMockHandler = (
	overrideResponse?:
		| void
		| ((
				info: Parameters<Parameters<typeof http.post>[1]>[0],
		  ) => Promise<void> | void),
	options?: RequestHandlerOptions,
) => {
	return http.post(
		'*/auth/logout',
		async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
			if (typeof overrideResponse === 'function') {
				await overrideResponse(info);
			}

			return new HttpResponse(null, { status: 200 });
		},
		options,
	);
};

export const getAuthRegisterMockHandler = (
	overrideResponse?:
		| void
		| ((
				info: Parameters<Parameters<typeof http.post>[1]>[0],
		  ) => Promise<void> | void),
	options?: RequestHandlerOptions,
) => {
	return http.post(
		'*/auth/register',
		async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
			if (typeof overrideResponse === 'function') {
				await overrideResponse(info);
			}

			return new HttpResponse(null, { status: 200 });
		},
		options,
	);
};

export const getRestCircuitsActiveMockHandler = (
	overrideResponse?:
		| RestCircuitsActive200Item[]
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) =>
				| Promise<RestCircuitsActive200Item[]>
				| RestCircuitsActive200Item[]),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		'*/rest/circuits/active',
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === 'function'
						? await overrideResponse(info)
						: overrideResponse
					: getRestCircuitsActiveResponseMock(),
				{ status: 200 },
			);
		},
		options,
	);
};

export const getRestTournsMockHandler = (
	overrideResponse?:
		| Tourn[]
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<Tourn[]> | Tourn[]),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		'*/rest/tourns',
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === 'function'
						? await overrideResponse(info)
						: overrideResponse
					: getRestTournsResponseMock(),
				{ status: 200 },
			);
		},
		options,
	);
};

export const getRestParadigmsMockHandler = (
	overrideResponse?:
		| RestParadigms200Item[]
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<RestParadigms200Item[]> | RestParadigms200Item[]),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		'*/rest/paradigms',
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === 'function'
						? await overrideResponse(info)
						: overrideResponse
					: getRestParadigmsResponseMock(),
				{ status: 200 },
			);
		},
		options,
	);
};

export const getRestParadigmMockHandler = (
	overrideResponse?:
		| ParadigmDetails
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<ParadigmDetails> | ParadigmDetails),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		'*/rest/paradigms/:personId',
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === 'function'
						? await overrideResponse(info)
						: overrideResponse
					: getRestParadigmResponseMock(),
				{ status: 200 },
			);
		},
		options,
	);
};

export const getUserInboxUnreadMockHandler = (
	overrideResponse?:
		| UserInboxUnread200
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<UserInboxUnread200> | UserInboxUnread200),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		'*/user/inbox/unread',
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === 'function'
						? await overrideResponse(info)
						: overrideResponse
					: getUserInboxUnreadResponseMock(),
				{ status: 200 },
			);
		},
		options,
	);
};

export const getUserSessionMockHandler = (
	overrideResponse?:
		| Session
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<Session> | Session),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		'*/user/session',
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === 'function'
						? await overrideResponse(info)
						: overrideResponse
					: getUserSessionResponseMock(),
				{ status: 200 },
			);
		},
		options,
	);
};
export const getIndexCardsAPIMock = () => [
	getAuthLoginMockHandler(),
	getAuthLogoutMockHandler(),
	getAuthRegisterMockHandler(),
	getRestCircuitsActiveMockHandler(),
	getRestTournsMockHandler(),
	getRestParadigmsMockHandler(),
	getRestParadigmMockHandler(),
	getUserInboxUnreadMockHandler(),
	getUserSessionMockHandler(),
];
