/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */
import { faker } from '@faker-js/faker';

import { HttpResponse, http } from 'msw';
import type { RequestHandlerOptions } from 'msw';

import type {
	ParadigmDetails,
	RestParadigms200Item,
	TournInvite,
} from './schemas';

export const getGetTournInviteResponseMock = (): TournInvite => ({
	...{
		id: faker.helpers.arrayElement([faker.number.int(), undefined]),
		name: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			undefined,
		]),
		city: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			undefined,
		]),
		state: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			undefined,
		]),
		country: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			undefined,
		]),
		tz: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			undefined,
		]),
		webName: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			undefined,
		]),
		start: faker.helpers.arrayElement([
			faker.date.past().toISOString().slice(0, 19) + 'Z',
			undefined,
		]),
		end: faker.helpers.arrayElement([
			faker.date.past().toISOString().slice(0, 19) + 'Z',
			undefined,
		]),
		regStart: faker.helpers.arrayElement([
			faker.date.past().toISOString().slice(0, 19) + 'Z',
			undefined,
		]),
		regEnd: faker.helpers.arrayElement([
			faker.date.past().toISOString().slice(0, 19) + 'Z',
			undefined,
		]),
	},
	...{
		webpages: faker.helpers.arrayElement([
			Array.from(
				{ length: faker.number.int({ min: 1, max: 10 }) },
				(_, i) => i + 1,
			).map(() => ({
				id: faker.helpers.arrayElement([faker.number.int(), undefined]),
				title: faker.helpers.arrayElement([
					faker.string.alpha({ length: { min: 10, max: 63 } }),
					null,
				]),
				content: faker.helpers.arrayElement([
					faker.string.alpha({ length: { min: 10, max: 20 } }),
					null,
				]),
				published: faker.helpers.arrayElement([
					faker.datatype.boolean(),
					undefined,
				]),
				sitewide: faker.helpers.arrayElement([
					faker.datatype.boolean(),
					undefined,
				]),
				special: faker.helpers.arrayElement([
					faker.string.alpha({ length: { min: 10, max: 15 } }),
					null,
				]),
				slug: faker.helpers.arrayElement([
					faker.string.alpha({ length: { min: 10, max: 63 } }),
					null,
				]),
				pageOrder: faker.helpers.arrayElement([
					faker.number.int(),
					null,
				]),
				parentId: faker.helpers.arrayElement([
					faker.number.int(),
					null,
				]),
				updatedAt: faker.helpers.arrayElement([
					faker.date.past().toISOString().slice(0, 19) + 'Z',
					undefined,
				]),
			})),
			undefined,
		]),
		files: faker.helpers.arrayElement([
			Array.from(
				{ length: faker.number.int({ min: 1, max: 10 }) },
				(_, i) => i + 1,
			).map(() => ({
				id: faker.helpers.arrayElement([faker.number.int(), undefined]),
				tag: faker.helpers.arrayElement([
					faker.string.alpha({ length: { min: 10, max: 20 } }),
					null,
				]),
				type: faker.helpers.arrayElement([
					faker.string.alpha({ length: { min: 10, max: 20 } }),
					null,
				]),
				label: faker.helpers.arrayElement([
					faker.string.alpha({ length: { min: 10, max: 20 } }),
					null,
				]),
				filename: faker.helpers.arrayElement([
					faker.string.alpha({ length: { min: 10, max: 255 } }),
					undefined,
				]),
				published: faker.helpers.arrayElement([
					faker.datatype.boolean(),
					undefined,
				]),
				pageOrder: faker.helpers.arrayElement([
					faker.number.int(),
					null,
				]),
				uploaded: faker.helpers.arrayElement([
					faker.date.past().toISOString().slice(0, 19) + 'Z',
					null,
				]),
				updatedAt: faker.helpers.arrayElement([
					faker.date.past().toISOString().slice(0, 19) + 'Z',
					undefined,
				]),
			})),
			undefined,
		]),
		events: faker.helpers.arrayElement([
			Array.from(
				{ length: faker.number.int({ min: 1, max: 10 }) },
				(_, i) => i + 1,
			).map(() => ({
				id: faker.helpers.arrayElement([faker.number.int(), undefined]),
				abbr: faker.helpers.arrayElement([
					faker.string.alpha({ length: { min: 10, max: 20 } }),
					undefined,
				]),
				name: faker.helpers.arrayElement([
					faker.string.alpha({ length: { min: 10, max: 20 } }),
					undefined,
				]),
				fee: faker.helpers.arrayElement([
					faker.number.float({ fractionDigits: 2 }),
					undefined,
				]),
				type: faker.helpers.arrayElement([
					faker.string.alpha({ length: { min: 10, max: 20 } }),
					undefined,
				]),
				categoryId: faker.helpers.arrayElement([
					faker.number.int(),
					undefined,
				]),
				categoryName: faker.helpers.arrayElement([
					faker.string.alpha({ length: { min: 10, max: 20 } }),
					undefined,
				]),
				categoryAbbr: faker.helpers.arrayElement([
					faker.string.alpha({ length: { min: 10, max: 20 } }),
					undefined,
				]),
				judgeFieldReport: faker.helpers.arrayElement([
					faker.string.alpha({ length: { min: 10, max: 20 } }),
					undefined,
				]),
				cap: faker.helpers.arrayElement([faker.number.int(), null]),
				schoolCap: faker.helpers.arrayElement([
					faker.number.int(),
					null,
				]),
				topicSource: faker.helpers.arrayElement([
					faker.string.alpha({ length: { min: 10, max: 20 } }),
					null,
				]),
				topicEventType: faker.helpers.arrayElement([
					faker.string.alpha({ length: { min: 10, max: 20 } }),
					null,
				]),
				topicTag: faker.helpers.arrayElement([
					faker.string.alpha({ length: { min: 10, max: 20 } }),
					null,
				]),
				topicText: faker.helpers.arrayElement([
					faker.string.alpha({ length: { min: 10, max: 20 } }),
					null,
				]),
				fieldReport: faker.helpers.arrayElement([
					faker.string.alpha({ length: { min: 10, max: 20 } }),
					null,
				]),
				anonymousPublic: faker.helpers.arrayElement([
					faker.datatype.boolean(),
					null,
				]),
				liveUpdates: faker.helpers.arrayElement([
					faker.string.alpha({ length: { min: 10, max: 20 } }),
					undefined,
				]),
				description: faker.helpers.arrayElement([
					faker.string.alpha({ length: { min: 10, max: 20 } }),
					null,
				]),
				currency: faker.helpers.arrayElement([
					faker.string.alpha({ length: { min: 10, max: 20 } }),
					undefined,
				]),
				entryCount: faker.helpers.arrayElement([
					faker.number.int(),
					undefined,
				]),
				nsdaCode: faker.helpers.arrayElement([
					faker.string.alpha({ length: { min: 10, max: 20 } }),
					undefined,
				]),
				nsdaName: faker.helpers.arrayElement([
					faker.string.alpha({ length: { min: 10, max: 20 } }),
					undefined,
				]),
			})),
			undefined,
		]),
		contacts: faker.helpers.arrayElement([
			Array.from(
				{ length: faker.number.int({ min: 1, max: 10 }) },
				(_, i) => i + 1,
			).map(() => ({
				id: faker.helpers.arrayElement([faker.number.int(), undefined]),
				first: faker.helpers.arrayElement([
					faker.string.alpha({ length: { min: 10, max: 20 } }),
					undefined,
				]),
				middle: faker.helpers.arrayElement([
					faker.string.alpha({ length: { min: 10, max: 20 } }),
					null,
				]),
				last: faker.helpers.arrayElement([
					faker.string.alpha({ length: { min: 10, max: 20 } }),
					undefined,
				]),
				email: faker.helpers.arrayElement([
					faker.internet.email(),
					undefined,
				]),
			})),
			undefined,
		]),
	},
});

export const getRestParadigmsResponseMock = (): RestParadigms200Item[] =>
	Array.from(
		{ length: faker.number.int({ min: 1, max: 10 }) },
		(_, i) => i + 1,
	).map(() => ({
		id: faker.helpers.arrayElement([faker.number.int(), undefined]),
		name: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			undefined,
		]),
		tournJudged: faker.helpers.arrayElement([
			faker.number.int(),
			undefined,
		]),
		schools: faker.helpers.arrayElement([
			Array.from(
				{ length: faker.number.int({ min: 1, max: 10 }) },
				(_, i) => i + 1,
			).map(() => ({
				id: faker.helpers.arrayElement([faker.number.int(), undefined]),
				name: faker.helpers.arrayElement([
					faker.string.alpha({ length: { min: 10, max: 20 } }),
					undefined,
				]),
			})),
			undefined,
		]),
	}));

export const getRestParadigmResponseMock = (
	overrideResponse: Partial<Extract<ParadigmDetails, object>> = {},
): ParadigmDetails => ({
	id: faker.number.int(),
	name: faker.string.alpha({ length: { min: 10, max: 20 } }),
	lastReviewed: faker.date.past().toISOString().slice(0, 19) + 'Z',
	paradigm: faker.string.alpha({ length: { min: 10, max: 20 } }),
	record: Array.from(
		{ length: faker.number.int({ min: 1, max: 10 }) },
		(_, i) => i + 1,
	).map(() => ({
		tournName: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			undefined,
		]),
		roundDate: faker.helpers.arrayElement([
			faker.date.past().toISOString().slice(0, 19) + 'Z',
			undefined,
		]),
		roundLabel: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			undefined,
		]),
		eventAbbr: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			undefined,
		]),
		affTeam: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			undefined,
		]),
		affLabel: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			undefined,
		]),
		negTeam: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			undefined,
		]),
		negLabel: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			undefined,
		]),
		vote: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			undefined,
		]),
		panelVote: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			undefined,
		]),
		record: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			undefined,
		]),
	})),
	certifications: Array.from(
		{ length: faker.number.int({ min: 1, max: 10 }) },
		(_, i) => i + 1,
	).map(() => ({
		title: faker.string.alpha({ length: { min: 10, max: 20 } }),
		description: faker.string.alpha({ length: { min: 10, max: 20 } }),
		updatedAt: faker.helpers.arrayElement([
			faker.date.past().toISOString().slice(0, 19) + 'Z',
			undefined,
		]),
		badge: faker.helpers.arrayElement([
			{
				altText: faker.helpers.arrayElement([
					faker.string.alpha({ length: { min: 10, max: 20 } }),
					undefined,
				]),
				link: faker.helpers.arrayElement([
					faker.internet.url(),
					undefined,
				]),
				imageUrl: faker.helpers.arrayElement([
					faker.internet.url(),
					undefined,
				]),
			},
			undefined,
		]),
	})),
	...overrideResponse,
});

export const getAuthLoginMockHandler = (
	overrideResponse?:
		| void
		| ((
				info: Parameters<Parameters<typeof http.post>[1]>[0],
		  ) => Promise<void> | void),
	options?: RequestHandlerOptions,
) => {
	return http.post(
		'*/auth/login',
		async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
			if (typeof overrideResponse === 'function') {
				await overrideResponse(info);
			}

			return new HttpResponse(null, { status: 200 });
		},
		options,
	);
};

export const getAuthLogoutMockHandler = (
	overrideResponse?:
		| void
		| ((
				info: Parameters<Parameters<typeof http.post>[1]>[0],
		  ) => Promise<void> | void),
	options?: RequestHandlerOptions,
) => {
	return http.post(
		'*/auth/logout',
		async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
			if (typeof overrideResponse === 'function') {
				await overrideResponse(info);
			}

			return new HttpResponse(null, { status: 200 });
		},
		options,
	);
};

export const getAuthRegisterMockHandler = (
	overrideResponse?:
		| void
		| ((
				info: Parameters<Parameters<typeof http.post>[1]>[0],
		  ) => Promise<void> | void),
	options?: RequestHandlerOptions,
) => {
	return http.post(
		'*/auth/register',
		async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
			if (typeof overrideResponse === 'function') {
				await overrideResponse(info);
			}

			return new HttpResponse(null, { status: 200 });
		},
		options,
	);
};

export const getGetTournInviteMockHandler = (
	overrideResponse?:
		| TournInvite
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<TournInvite> | TournInvite),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		'*/rest/tourns/:tournId/invite',
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === 'function'
						? await overrideResponse(info)
						: overrideResponse
					: getGetTournInviteResponseMock(),
				{ status: 200 },
			);
		},
		options,
	);
};

export const getRestParadigmsMockHandler = (
	overrideResponse?:
		| RestParadigms200Item[]
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<RestParadigms200Item[]> | RestParadigms200Item[]),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		'*/rest/paradigms',
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === 'function'
						? await overrideResponse(info)
						: overrideResponse
					: getRestParadigmsResponseMock(),
				{ status: 200 },
			);
		},
		options,
	);
};

export const getRestParadigmMockHandler = (
	overrideResponse?:
		| ParadigmDetails
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<ParadigmDetails> | ParadigmDetails),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		'*/rest/paradigms/:personId',
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === 'function'
						? await overrideResponse(info)
						: overrideResponse
					: getRestParadigmResponseMock(),
				{ status: 200 },
			);
		},
		options,
	);
};
export const getIndexCardsAPIMock = () => [
	getAuthLoginMockHandler(),
	getAuthLogoutMockHandler(),
	getAuthRegisterMockHandler(),
	getGetTournInviteMockHandler(),
	getRestParadigmsMockHandler(),
	getRestParadigmMockHandler(),
];
