/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */
import { faker } from '@faker-js/faker';

import { HttpResponse, http } from 'msw';
import type { RequestHandlerOptions } from 'msw';

import type {
	ActiveCircuitsResponse,
	CurrentBallot,
	Fine,
	GetTournResultSets200,
	HomepageAd,
	InboxMessage,
	JudgeHistory,
	JudgeRecord,
	LoginResponse,
	ParadigmDetails,
	PersonTournSummary,
	QuizOutput,
	RestCircuit,
	RestParadigms200Item,
	ResultSet,
	Session,
	Student,
	Tourn,
	UnlinkedJudge,
	UnlinkedStudentSearch,
	UserChapter,
	UserInboxUnread200,
	UserJudgesClaim200,
	UserJudgesLiveDocs200Item,
	UserJudgesParadigm200,
	UserStudentsClaim200,
} from './schemas';

export const getRestAdsResponseMock = (): HomepageAd[] =>
	Array.from(
		{ length: faker.number.int({ min: 1, max: 10 }) },
		(_, i) => i + 1,
	).map(() => ({
		url: faker.internet.url(),
		imgSrc: faker.internet.url(),
		background: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			undefined,
		]),
	}));

export const getRestCircuitsActiveResponseMock = (): ActiveCircuitsResponse =>
	Array.from(
		{ length: faker.number.int({ min: 1, max: 10 }) },
		(_, i) => i + 1,
	).map(() => ({
		id: faker.number.int({ min: 0, max: 9007199254740991 }),
		name: faker.string.alpha({ length: { min: 10, max: 63 } }),
		abbr: faker.string.alpha({ length: { min: 10, max: 15 } }),
		state: faker.helpers.arrayElement([
			faker.helpers.fromRegExp('^[A-Z]{2}$'),
			null,
		]),
		country: faker.helpers.arrayElement([
			faker.helpers.fromRegExp('^[A-Z]{2}$'),
			null,
		]),
		tournCount: faker.number.int({ min: 0, max: 9007199254740991 }),
	}));

export const getRestCircuitResponseMock = (
	overrideResponse: Partial<Extract<RestCircuit, object>> = {},
): RestCircuit => ({
	id: faker.number.int({ min: 0, max: 9007199254740991 }),
	name: faker.helpers.arrayElement([
		faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 63 } }),
			null,
		]),
		undefined,
	]),
	abbr: faker.helpers.arrayElement([
		faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 15 } }),
			null,
		]),
		undefined,
	]),
	tz: faker.helpers.arrayElement([
		faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 63 } }),
			null,
		]),
		undefined,
	]),
	active: faker.helpers.arrayElement([
		faker.helpers.arrayElement([faker.datatype.boolean(), null]),
		undefined,
	]),
	state: faker.helpers.arrayElement([
		faker.helpers.arrayElement([
			faker.helpers.fromRegExp('^[A-Z]{2}$'),
			null,
		]),
		undefined,
	]),
	country: faker.helpers.arrayElement([
		faker.helpers.arrayElement([
			faker.helpers.fromRegExp('^[A-Z]{2}$'),
			null,
		]),
		undefined,
	]),
	webname: faker.helpers.arrayElement([
		faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 31 } }),
			null,
		]),
		undefined,
	]),
	...overrideResponse,
});

export const getRestJudgesUnlinkedSearchResponseMock = (): UnlinkedJudge[] =>
	Array.from(
		{ length: faker.number.int({ min: 1, max: 10 }) },
		(_, i) => i + 1,
	).map(() => ({
		id: faker.number.int({ min: 0, max: 9007199254740991 }),
		type: faker.helpers.arrayElement(['judge', 'chapter_judge'] as const),
		first: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			null,
		]),
		last: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			null,
		]),
		schoolName: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				null,
			]),
			undefined,
		]),
		tournName: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				null,
			]),
			undefined,
		]),
		tournCount: faker.helpers.arrayElement([
			faker.number.int({ min: 0, max: 9007199254740991 }),
			undefined,
		]),
	}));

export const getRestTournsResponseMock = (): Tourn[] =>
	Array.from(
		{ length: faker.number.int({ min: 1, max: 10 }) },
		(_, i) => i + 1,
	).map(() => ({
		id: faker.number.int({ min: 0, max: 9007199254740991 }),
		name: faker.string.alpha({ length: { min: 10, max: 63 } }),
		city: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 31 } }),
			null,
		]),
		state: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 6, max: 6 } }),
			null,
		]),
		country: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 4, max: 4 } }),
			null,
		]),
		tz: faker.string.alpha({ length: { min: 10, max: 31 } }),
		webname: faker.string.alpha({ length: { min: 10, max: 20 } }),
		hidden: faker.datatype.boolean(),
		start: faker.date.past().toISOString().slice(0, 19) + 'Z',
		end: faker.date.past().toISOString().slice(0, 19) + 'Z',
		regStart: faker.date.past().toISOString().slice(0, 19) + 'Z',
		regEnd: faker.date.past().toISOString().slice(0, 19) + 'Z',
	}));

export const getGetTournResultSetsResponseMock = (): GetTournResultSets200 => ({
	[faker.string.alphanumeric(5)]: {
		id: faker.number.int({ min: 0, max: 9007199254740991 }),
		nsdacategory: faker.number.int({ min: 0, max: 9007199254740991 }),
		name: faker.string.alpha({ length: { min: 10, max: 20 } }),
		abbr: faker.string.alpha({ length: { min: 10, max: 20 } }),
		level: faker.string.alpha({ length: { min: 10, max: 20 } }),
		type: faker.string.alpha({ length: { min: 10, max: 20 } }),
		ResultSets: Array.from(
			{ length: faker.number.int({ min: 1, max: 10 }) },
			(_, i) => i + 1,
		).map(() => ({
			id: faker.number.int({ min: 0, max: 9007199254740991 }),
			tag: faker.string.alpha({ length: { min: 10, max: 20 } }),
			label: faker.string.alpha({ length: { min: 10, max: 20 } }),
			entity: faker.string.alpha({ length: { min: 10, max: 20 } }),
			createdAt: faker.date.past().toISOString().slice(0, 19) + 'Z',
		})),
	},
});

export const getGetResultSetResponseMock = (): ResultSet[] =>
	Array.from(
		{ length: faker.number.int({ min: 1, max: 10 }) },
		(_, i) => i + 1,
	).map(() => ({
		id: faker.number.int({ min: 0, max: 9007199254740991 }),
		tag: faker.string.alpha({ length: { min: 10, max: 20 } }),
		label: faker.string.alpha({ length: { min: 10, max: 20 } }),
		entity: faker.string.alpha({ length: { min: 10, max: 20 } }),
		createdAt: faker.date.past().toISOString().slice(0, 19) + 'Z',
		noPlacement: faker.helpers.arrayElement([
			faker.datatype.boolean(),
			undefined,
		]),
		headers: {
			[faker.string.alphanumeric(5)]: {
				tag: faker.string.alpha({ length: { min: 10, max: 20 } }),
				description: faker.string.alpha({
					length: { min: 10, max: 20 },
				}),
				no_sort: faker.datatype.boolean(),
				sort_desc: faker.datatype.boolean(),
				Protocol: faker.helpers.arrayElement([
					{
						id: faker.number.int({ min: 0, max: 9007199254740991 }),
						name: faker.string.alpha({
							length: { min: 10, max: 20 },
						}),
					},
					undefined,
				]),
			},
		},
		Event: {
			id: faker.number.int({ min: 0, max: 9007199254740991 }),
			abbr: faker.string.alpha({ length: { min: 10, max: 20 } }),
			level: faker.string.alpha({ length: { min: 10, max: 20 } }),
			name: faker.string.alpha({ length: { min: 10, max: 20 } }),
			nsdacategory: faker.number.int({ min: 0, max: 9007199254740991 }),
			type: faker.string.alpha({ length: { min: 10, max: 20 } }),
		},
		results: Array.from(
			{ length: faker.number.int({ min: 1, max: 10 }) },
			(_, i) => i + 1,
		).map(() => ({})),
	}));

export const getRestParadigmsResponseMock = (): RestParadigms200Item[] =>
	Array.from(
		{ length: faker.number.int({ min: 1, max: 10 }) },
		(_, i) => i + 1,
	).map(() => ({
		id: faker.number.int({ min: 0, max: 9007199254740991 }),
		name: faker.string.alpha({ length: { min: 10, max: 20 } }),
		tournJudged: faker.number.int({ min: 0, max: 9007199254740991 }),
		schools: Array.from(
			{ length: faker.number.int({ min: 1, max: 10 }) },
			(_, i) => i + 1,
		).map(() => ({
			id: faker.number.int({ min: 0, max: 9007199254740991 }),
			name: faker.string.alpha({ length: { min: 10, max: 20 } }),
		})),
	}));

export const getRestParadigmResponseMock = (
	overrideResponse: Partial<Extract<ParadigmDetails, object>> = {},
): ParadigmDetails => ({
	id: faker.number.int({ min: 0, max: 9007199254740991 }),
	name: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		null,
	]),
	lastReviewed: faker.helpers.arrayElement([
		faker.date.past().toISOString().slice(0, 19) + 'Z',
		null,
	]),
	paradigm: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		null,
	]),
	certifications: faker.helpers.arrayElement([
		Array.from(
			{ length: faker.number.int({ min: 1, max: 10 }) },
			(_, i) => i + 1,
		).map(() => ({
			id: faker.number.int({ min: 0, max: 9007199254740991 }),
			tag: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 63 } }),
				null,
			]),
			label: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 255 } }),
				null,
			]),
			description: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 511 } }),
				null,
			]),
			sitewide: faker.datatype.boolean(),
			hidden: faker.datatype.boolean(),
			approval: faker.datatype.boolean(),
			show_answers: faker.datatype.boolean(),
			admin_only: faker.datatype.boolean(),
			circuit: faker.helpers.arrayElement([
				faker.number.int({ min: 0, max: 9007199254740991 }),
				null,
			]),
			Badge: {
				altText: faker.helpers.arrayElement([
					faker.string.alpha({ length: { min: 10, max: 20 } }),
					null,
				]),
				link: faker.helpers.arrayElement([faker.internet.url(), null]),
				imageUrl: faker.helpers.arrayElement([
					faker.internet.url(),
					null,
				]),
			},
			PersonQuizzes: faker.helpers.arrayElement([
				Array.from(
					{ length: faker.number.int({ min: 1, max: 10 }) },
					(_, i) => i + 1,
				).map(() => ({
					id: faker.number.int({ min: 0, max: 9007199254740991 }),
					person: faker.number.int({ min: 0, max: 9007199254740991 }),
					quiz: faker.number.int({ min: 0, max: 9007199254740991 }),
					approvedBy: faker.helpers.arrayElement([
						faker.number.int({ min: 0, max: 9007199254740991 }),
						null,
					]),
					pending: faker.datatype.boolean(),
					updatedAt:
						faker.date.past().toISOString().slice(0, 19) + 'Z',
				})),
				undefined,
			]),
		})),
		undefined,
	]),
	...overrideResponse,
});

export const getRestParadigmsRecordResponseMock = (): JudgeRecord[] =>
	Array.from(
		{ length: faker.number.int({ min: 1, max: 10 }) },
		(_, i) => i + 1,
	).map(() => ({
		Tourn: {
			id: faker.number.int({ min: 0, max: 9007199254740991 }),
			name: faker.string.alpha({ length: { min: 10, max: 20 } }),
		},
		roundDate: faker.date.past().toISOString().slice(0, 19) + 'Z',
		roundLabel: faker.string.alpha({ length: { min: 10, max: 20 } }),
		eventAbbr: faker.string.alpha({ length: { min: 10, max: 20 } }),
		affTeam: faker.string.alpha({ length: { min: 10, max: 20 } }),
		affLabel: faker.string.alpha({ length: { min: 10, max: 20 } }),
		negTeam: faker.string.alpha({ length: { min: 10, max: 20 } }),
		negLabel: faker.string.alpha({ length: { min: 10, max: 20 } }),
		vote: faker.string.alpha({ length: { min: 10, max: 20 } }),
		panelVote: faker.string.alpha({ length: { min: 10, max: 20 } }),
		record: faker.string.alpha({ length: { min: 10, max: 20 } }),
	}));

export const getRestQuizzesResponseMock = (): QuizOutput[] =>
	Array.from(
		{ length: faker.number.int({ min: 1, max: 10 }) },
		(_, i) => i + 1,
	).map(() => ({
		id: faker.number.int({ min: 0, max: 9007199254740991 }),
		tag: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 63 } }),
			null,
		]),
		label: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 255 } }),
			null,
		]),
		description: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 511 } }),
			null,
		]),
		sitewide: faker.datatype.boolean(),
		hidden: faker.datatype.boolean(),
		approval: faker.datatype.boolean(),
		show_answers: faker.datatype.boolean(),
		admin_only: faker.datatype.boolean(),
		circuit: faker.helpers.arrayElement([
			faker.number.int({ min: 0, max: 9007199254740991 }),
			null,
		]),
		Badge: {
			altText: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				null,
			]),
			link: faker.helpers.arrayElement([faker.internet.url(), null]),
			imageUrl: faker.helpers.arrayElement([faker.internet.url(), null]),
		},
		PersonQuizzes: faker.helpers.arrayElement([
			Array.from(
				{ length: faker.number.int({ min: 1, max: 10 }) },
				(_, i) => i + 1,
			).map(() => ({
				id: faker.number.int({ min: 0, max: 9007199254740991 }),
				person: faker.number.int({ min: 0, max: 9007199254740991 }),
				quiz: faker.number.int({ min: 0, max: 9007199254740991 }),
				approvedBy: faker.helpers.arrayElement([
					faker.number.int({ min: 0, max: 9007199254740991 }),
					null,
				]),
				pending: faker.datatype.boolean(),
				updatedAt: faker.date.past().toISOString().slice(0, 19) + 'Z',
			})),
			undefined,
		]),
	}));

export const getRestStudentsUnlinkedSearchResponseMock =
	(): UnlinkedStudentSearch[] =>
		Array.from(
			{ length: faker.number.int({ min: 1, max: 10 }) },
			(_, i) => i + 1,
		).map(() => ({
			id: faker.number.int({ min: 0, max: 9007199254740991 }),
			first: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				null,
			]),
			middle: faker.helpers.arrayElement([
				faker.helpers.arrayElement([
					faker.string.alpha({ length: { min: 10, max: 20 } }),
					null,
				]),
				undefined,
			]),
			last: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				null,
			]),
			gradYear: faker.helpers.arrayElement([
				faker.helpers.arrayElement([
					faker.number.float({ fractionDigits: 2 }),
					null,
				]),
				undefined,
			]),
			Chapter: faker.helpers.arrayElement([
				{
					name: faker.helpers.arrayElement([
						faker.string.alpha({ length: { min: 10, max: 20 } }),
						null,
					]),
					state: faker.helpers.arrayElement([
						faker.string.alpha({ length: { min: 10, max: 20 } }),
						null,
					]),
				},
				null,
			]),
			tournCount: faker.helpers.arrayElement([
				faker.number.float({ fractionDigits: 2 }),
				null,
			]),
		}));

export const getAuthLoginResponseMock = (
	overrideResponse: Partial<Extract<LoginResponse, object>> = {},
): LoginResponse => ({
	token: faker.string.alpha({ length: { min: 10, max: 20 } }),
	Person: {
		id: faker.number.int({ min: -9007199254740991, max: 9007199254740991 }),
		email: faker.string.alpha({ length: { min: 10, max: 20 } }),
	},
	...overrideResponse,
});

export const getUserTournsResponseMock = (): Tourn[] =>
	Array.from(
		{ length: faker.number.int({ min: 1, max: 10 }) },
		(_, i) => i + 1,
	).map(() => ({
		id: faker.number.int({ min: 0, max: 9007199254740991 }),
		name: faker.string.alpha({ length: { min: 10, max: 63 } }),
		city: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 31 } }),
			null,
		]),
		state: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 6, max: 6 } }),
			null,
		]),
		country: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 4, max: 4 } }),
			null,
		]),
		tz: faker.string.alpha({ length: { min: 10, max: 31 } }),
		webname: faker.string.alpha({ length: { min: 10, max: 20 } }),
		hidden: faker.datatype.boolean(),
		start: faker.date.past().toISOString().slice(0, 19) + 'Z',
		end: faker.date.past().toISOString().slice(0, 19) + 'Z',
		regStart: faker.date.past().toISOString().slice(0, 19) + 'Z',
		regEnd: faker.date.past().toISOString().slice(0, 19) + 'Z',
	}));

export const getUserTournsSummaryResponseMock = (
	overrideResponse: Partial<Extract<PersonTournSummary, object>> = {},
): PersonTournSummary => ({
	id: faker.number.int({ min: 0, max: 9007199254740991 }),
	name: faker.string.alpha({ length: { min: 10, max: 63 } }),
	webname: faker.string.alpha({ length: { min: 10, max: 20 } }),
	start: faker.date.past().toISOString().slice(0, 19) + 'Z',
	end: faker.date.past().toISOString().slice(0, 19) + 'Z',
	tz: faker.string.alpha({ length: { min: 10, max: 31 } }),
	roles: faker.helpers.arrayElements(['student', 'coach', 'judge'] as const),
	livedocs: Array.from(
		{ length: faker.number.int({ min: 1, max: 10 }) },
		(_, i) => i + 1,
	).map(() => ({
		url: faker.string.alpha({ length: { min: 10, max: 20 } }),
		caption: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			null,
		]),
	})),
	Judge: faker.helpers.arrayElement([
		{
			categoryName: faker.string.alpha({ length: { min: 10, max: 20 } }),
			schoolName: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				null,
			]),
		},
		null,
	]),
	...overrideResponse,
});

export const getUserTournsFinesResponseMock = (): Fine[] =>
	Array.from(
		{ length: faker.number.int({ min: 1, max: 10 }) },
		(_, i) => i + 1,
	).map(() => ({
		id: faker.number.int({ min: 0, max: 9007199254740991 }),
		reason: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 255 } }),
			null,
		]),
		amount: faker.helpers.arrayElement([
			faker.number.float({ fractionDigits: 2 }),
			null,
		]),
		school: faker.number.int({ min: 0, max: 9007199254740991 }),
		leviedAt: faker.date.past().toISOString().slice(0, 19) + 'Z',
	}));

export const getUserTournsBallotsResponseMock = (): CurrentBallot[] =>
	Array.from(
		{ length: faker.number.int({ min: 1, max: 10 }) },
		(_, i) => i + 1,
	).map(() => ({
		id: faker.number.int({ min: 0, max: 9007199254740991 }),
		flipStatus: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			null,
		]),
		flight: faker.helpers.arrayElement([
			faker.number.int({ min: 0, max: 9007199254740991 }),
			null,
		]),
		show_async: faker.datatype.boolean(),
		legion: faker.datatype.boolean(),
		start: faker.date.past().toISOString().slice(0, 19) + 'Z',
		deadline: faker.date.past().toISOString().slice(0, 19) + 'Z',
		roomId: faker.helpers.arrayElement([
			faker.number.int({ min: 0, max: 9007199254740991 }),
			null,
		]),
		roomName: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 127 } }),
			null,
		]),
		roomUrl: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 255 } }),
				null,
			]),
			null,
		]),
		roomNotes: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 63 } }),
				null,
			]),
			null,
		]),
		JudgeId: faker.number.int({ min: 0, max: 9007199254740991 }),
		status: faker.helpers.arrayElement([
			'not_started',
			'started',
			'scored',
		] as const),
		startText: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 127 } }),
			null,
		]),
		ballotText: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 127 } }),
			null,
		]),
		chair: faker.datatype.boolean(),
		audited: faker.datatype.boolean(),
		Tourn: {
			id: faker.number.int({ min: 0, max: 9007199254740991 }),
			name: faker.string.alpha({ length: { min: 10, max: 63 } }),
			tz: faker.string.alpha({ length: { min: 10, max: 31 } }),
		},
		Category: {
			id: faker.number.int({ min: 0, max: 9007199254740991 }),
			name: faker.string.alpha({ length: { min: 10, max: 20 } }),
			abbr: faker.string.alpha({ length: { min: 10, max: 20 } }),
		},
		Event: {
			id: faker.number.int({ min: 0, max: 9007199254740991 }),
			name: faker.string.alpha({ length: { min: 10, max: 20 } }),
			abbr: faker.string.alpha({ length: { min: 10, max: 20 } }),
			type: faker.helpers.arrayElement([
				'debate',
				'speech',
				'mock_trial',
				'congress',
				'wsdc',
				'wudc',
				'attendee',
				'academic',
			] as const),
			settings: {
				online_mode: faker.helpers.arrayElement([
					faker.string.alpha({ length: { min: 10, max: 20 } }),
					null,
				]),
				online_ballots: faker.datatype.boolean(),
			},
		},
		Round: {
			id: faker.number.int({ min: 0, max: 9007199254740991 }),
			name: faker.helpers.arrayElement([
				faker.number.int({
					min: -9007199254740991,
					max: 9007199254740991,
				}),
				null,
			]),
			label: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 31 } }),
				null,
			]),
		},
		Ballots: Array.from(
			{ length: faker.number.int({ min: 1, max: 10 }) },
			(_, i) => i + 1,
		).map(() => ({
			id: faker.number.int({ min: 0, max: 9007199254740991 }),
			side: faker.datatype.boolean(),
			speakerOrder: faker.number.int({ min: 0, max: 9007199254740991 }),
		})),
		Entries: Array.from(
			{ length: faker.number.int({ min: 1, max: 10 }) },
			(_, i) => i + 1,
		).map(() => ({
			id: faker.number.int({ min: 0, max: 9007199254740991 }),
			code: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				null,
			]),
		})),
	}));

export const getUserTournsBallotsCurrentResponseMock = (): CurrentBallot[] =>
	Array.from(
		{ length: faker.number.int({ min: 1, max: 10 }) },
		(_, i) => i + 1,
	).map(() => ({
		id: faker.number.int({ min: 0, max: 9007199254740991 }),
		flipStatus: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			null,
		]),
		flight: faker.helpers.arrayElement([
			faker.number.int({ min: 0, max: 9007199254740991 }),
			null,
		]),
		show_async: faker.datatype.boolean(),
		legion: faker.datatype.boolean(),
		start: faker.date.past().toISOString().slice(0, 19) + 'Z',
		deadline: faker.date.past().toISOString().slice(0, 19) + 'Z',
		roomId: faker.helpers.arrayElement([
			faker.number.int({ min: 0, max: 9007199254740991 }),
			null,
		]),
		roomName: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 127 } }),
			null,
		]),
		roomUrl: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 255 } }),
				null,
			]),
			null,
		]),
		roomNotes: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 63 } }),
				null,
			]),
			null,
		]),
		JudgeId: faker.number.int({ min: 0, max: 9007199254740991 }),
		status: faker.helpers.arrayElement([
			'not_started',
			'started',
			'scored',
		] as const),
		startText: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 127 } }),
			null,
		]),
		ballotText: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 127 } }),
			null,
		]),
		chair: faker.datatype.boolean(),
		audited: faker.datatype.boolean(),
		Tourn: {
			id: faker.number.int({ min: 0, max: 9007199254740991 }),
			name: faker.string.alpha({ length: { min: 10, max: 63 } }),
			tz: faker.string.alpha({ length: { min: 10, max: 31 } }),
		},
		Category: {
			id: faker.number.int({ min: 0, max: 9007199254740991 }),
			name: faker.string.alpha({ length: { min: 10, max: 20 } }),
			abbr: faker.string.alpha({ length: { min: 10, max: 20 } }),
		},
		Event: {
			id: faker.number.int({ min: 0, max: 9007199254740991 }),
			name: faker.string.alpha({ length: { min: 10, max: 20 } }),
			abbr: faker.string.alpha({ length: { min: 10, max: 20 } }),
			type: faker.helpers.arrayElement([
				'debate',
				'speech',
				'mock_trial',
				'congress',
				'wsdc',
				'wudc',
				'attendee',
				'academic',
			] as const),
			settings: {
				online_mode: faker.helpers.arrayElement([
					faker.string.alpha({ length: { min: 10, max: 20 } }),
					null,
				]),
				online_ballots: faker.datatype.boolean(),
			},
		},
		Round: {
			id: faker.number.int({ min: 0, max: 9007199254740991 }),
			name: faker.helpers.arrayElement([
				faker.number.int({
					min: -9007199254740991,
					max: 9007199254740991,
				}),
				null,
			]),
			label: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 31 } }),
				null,
			]),
		},
		Ballots: Array.from(
			{ length: faker.number.int({ min: 1, max: 10 }) },
			(_, i) => i + 1,
		).map(() => ({
			id: faker.number.int({ min: 0, max: 9007199254740991 }),
			side: faker.datatype.boolean(),
			speakerOrder: faker.number.int({ min: 0, max: 9007199254740991 }),
		})),
		Entries: Array.from(
			{ length: faker.number.int({ min: 1, max: 10 }) },
			(_, i) => i + 1,
		).map(() => ({
			id: faker.number.int({ min: 0, max: 9007199254740991 }),
			code: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				null,
			]),
		})),
	}));

export const getUserInboxResponseMock = (): InboxMessage[] =>
	Array.from(
		{ length: faker.number.int({ min: 1, max: 10 }) },
		(_, i) => i + 1,
	).map(() => ({
		id: faker.number.int({ min: 0, max: 9007199254740991 }),
		subject: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 255 } }),
			null,
		]),
		body: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 65535 } }),
			null,
		]),
		url: faker.helpers.arrayElement([faker.internet.url(), null]),
		visibleAt: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			null,
		]),
		readAt: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			null,
		]),
		Tourn: faker.helpers.arrayElement([
			{
				id: faker.number.int({ min: 0, max: 9007199254740991 }),
				name: faker.helpers.arrayElement([
					faker.string.alpha({ length: { min: 10, max: 63 } }),
					null,
				]),
				webname: faker.helpers.arrayElement([
					faker.string.alpha({ length: { min: 10, max: 64 } }),
					null,
				]),
			},
			null,
		]),
		Sender: faker.helpers.arrayElement([
			{
				name: faker.helpers.arrayElement([
					faker.string.alpha({ length: { min: 10, max: 20 } }),
					null,
				]),
				email: faker.helpers.arrayElement([
					faker.string.alpha({ length: { min: 10, max: 127 } }),
					null,
				]),
			},
			null,
		]),
		Email: faker.helpers.arrayElement([
			{
				content: faker.helpers.arrayElement([
					faker.string.alpha({ length: { min: 10, max: 20 } }),
					null,
				]),
			},
			null,
		]),
	}));

export const getUserInboxUnreadResponseMock = (
	overrideResponse: Partial<Extract<UserInboxUnread200, object>> = {},
): UserInboxUnread200 => ({
	count: faker.helpers.arrayElement([faker.number.int(), undefined]),
	...overrideResponse,
});

export const getUserInboxGetMessageResponseMock = (
	overrideResponse: Partial<Extract<InboxMessage, object>> = {},
): InboxMessage => ({
	id: faker.number.int({ min: 0, max: 9007199254740991 }),
	subject: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 255 } }),
		null,
	]),
	body: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 65535 } }),
		null,
	]),
	url: faker.helpers.arrayElement([faker.internet.url(), null]),
	visibleAt: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		null,
	]),
	readAt: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		null,
	]),
	Tourn: faker.helpers.arrayElement([
		{
			id: faker.number.int({ min: 0, max: 9007199254740991 }),
			name: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 63 } }),
				null,
			]),
			webname: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 64 } }),
				null,
			]),
		},
		null,
	]),
	Sender: faker.helpers.arrayElement([
		{
			name: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				null,
			]),
			email: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 127 } }),
				null,
			]),
		},
		null,
	]),
	Email: faker.helpers.arrayElement([
		{
			content: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				null,
			]),
		},
		null,
	]),
	...overrideResponse,
});

export const getUserSessionResponseMock = (
	overrideResponse: Partial<Extract<Session, object>> = {},
): Session => ({
	id: faker.number.int({ min: 0, max: 9007199254740991 }),
	person: faker.number.int({ min: 0, max: 9007199254740991 }),
	su: faker.helpers.arrayElement([
		faker.number.int({ min: 0, max: 9007199254740991 }),
		null,
	]),
	Su: faker.helpers.arrayElement([
		{
			id: faker.number.int({ min: 0, max: 9007199254740991 }),
			email: faker.internet.email(),
			first: faker.string.alpha({ length: { min: 10, max: 20 } }),
			middle: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				null,
			]),
			last: faker.string.alpha({ length: { min: 10, max: 20 } }),
			state: faker.helpers.arrayElement([
				faker.helpers.arrayElement([
					faker.helpers.fromRegExp('^[A-Z]{2}$'),
					null,
				]),
				undefined,
			]),
			country: faker.helpers.arrayElement([
				faker.helpers.arrayElement([
					faker.string.alpha({ length: { min: 10, max: 20 } }),
					null,
				]),
				undefined,
			]),
			tz: faker.helpers.arrayElement([
				faker.helpers.arrayElement([
					faker.string.alpha({ length: { min: 10, max: 20 } }),
					null,
				]),
				undefined,
			]),
			createdAt: faker.date.past().toISOString().slice(0, 19) + 'Z',
			settings: faker.helpers.arrayElement([{}, undefined]),
			metadata: faker.helpers.arrayElement([{}, undefined]),
		},
		null,
	]),
	Person: {
		id: faker.number.int({ min: 0, max: 9007199254740991 }),
		email: faker.internet.email(),
		first: faker.string.alpha({ length: { min: 10, max: 20 } }),
		middle: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			null,
		]),
		last: faker.string.alpha({ length: { min: 10, max: 20 } }),
		state: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				faker.helpers.fromRegExp('^[A-Z]{2}$'),
				null,
			]),
			undefined,
		]),
		country: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				null,
			]),
			undefined,
		]),
		tz: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				null,
			]),
			undefined,
		]),
		createdAt: faker.date.past().toISOString().slice(0, 19) + 'Z',
		settings: faker.helpers.arrayElement([{}, undefined]),
		metadata: faker.helpers.arrayElement([{}, undefined]),
	},
	...overrideResponse,
});

export const getUserJudgesLinkRequestsResponseMock = (): UnlinkedJudge[] =>
	Array.from(
		{ length: faker.number.int({ min: 1, max: 10 }) },
		(_, i) => i + 1,
	).map(() => ({
		id: faker.number.int({ min: 0, max: 9007199254740991 }),
		type: faker.helpers.arrayElement(['judge', 'chapter_judge'] as const),
		first: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			null,
		]),
		last: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			null,
		]),
		schoolName: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				null,
			]),
			undefined,
		]),
		tournName: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				null,
			]),
			undefined,
		]),
		tournCount: faker.helpers.arrayElement([
			faker.number.int({ min: 0, max: 9007199254740991 }),
			undefined,
		]),
	}));

export const getUserJudgesClaimResponseMock = (
	overrideResponse: Partial<Extract<UserJudgesClaim200, object>> = {},
): UserJudgesClaim200 => ({
	message: faker.string.alpha({ length: { min: 10, max: 20 } }),
	detail: faker.string.alpha({ length: { min: 10, max: 20 } }),
	...overrideResponse,
});

export const getUserJudgesHistoryResponseMock = (
	overrideResponse: Partial<Extract<JudgeHistory, object>> = {},
): JudgeHistory => ({
	Tourn: {
		id: faker.number.int({ min: 0, max: 9007199254740991 }),
		name: faker.string.alpha({ length: { min: 10, max: 20 } }),
		start: faker.date.past().toISOString().slice(0, 19) + 'Z',
		end: faker.date.past().toISOString().slice(0, 19) + 'Z',
	},
	division: faker.string.alpha({ length: { min: 10, max: 20 } }),
	roundsJudged: faker.number.int({ min: 0, max: 9007199254740991 }),
	roundsObligated: faker.number.int({ min: 0, max: 9007199254740991 }),
	...overrideResponse,
});

export const getUserJudgesParadigmResponseMock = (
	overrideResponse: Partial<Extract<UserJudgesParadigm200, object>> = {},
): UserJudgesParadigm200 => ({
	paradigm: faker.string.alpha({ length: { min: 10, max: 20 } }),
	...overrideResponse,
});

export const getUserJudgesLiveDocsResponseMock =
	(): UserJudgesLiveDocs200Item[] =>
		Array.from(
			{ length: faker.number.int({ min: 1, max: 10 }) },
			(_, i) => i + 1,
		).map(() => ({
			judgeId: faker.number.int({ min: 0, max: 9007199254740991 }),
			categoryAbbr: faker.string.alpha({ length: { min: 10, max: 20 } }),
			tournName: faker.string.alpha({ length: { min: 10, max: 20 } }),
			tournEnd: faker.date.past().toISOString().slice(0, 19) + 'Z',
			tournTz: faker.string.alpha({ length: { min: 10, max: 20 } }),
			url: faker.string.alpha({ length: { min: 10, max: 20 } }),
			caption: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				null,
			]),
		}));

export const getUserStudentsLinkRequestsResponseMock = (): Student[] =>
	Array.from(
		{ length: faker.number.int({ min: 1, max: 10 }) },
		(_, i) => i + 1,
	).map(() => ({
		id: faker.number.int({ min: 0, max: 9007199254740991 }),
		first: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				null,
			]),
			undefined,
		]),
		middle: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				null,
			]),
			undefined,
		]),
		last: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				null,
			]),
			undefined,
		]),
		phonetic: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				null,
			]),
			undefined,
		]),
		gradYear: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				faker.number.float({ fractionDigits: 2 }),
				null,
			]),
			undefined,
		]),
		novice: faker.helpers.arrayElement([
			faker.datatype.boolean(),
			undefined,
		]),
		retired: faker.helpers.arrayElement([
			faker.datatype.boolean(),
			undefined,
		]),
		gender: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				null,
			]),
			undefined,
		]),
		nsda: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				faker.number.float({ fractionDigits: 2 }),
				null,
			]),
			undefined,
		]),
		chapterId: faker.number.int({ min: 0, max: 9007199254740991 }),
		personId: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				faker.number.int({ min: 0, max: 9007199254740991 }),
				null,
			]),
			undefined,
		]),
		Chapter: faker.helpers.arrayElement([
			{
				id: faker.number.int({ min: 0, max: 9007199254740991 }),
				name: faker.string.alpha({ length: { min: 10, max: 20 } }),
				formal: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						faker.string.alpha({ length: { min: 10, max: 20 } }),
						null,
					]),
					undefined,
				]),
				street: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						faker.string.alpha({ length: { min: 10, max: 20 } }),
						null,
					]),
					undefined,
				]),
				city: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						faker.string.alpha({ length: { min: 10, max: 20 } }),
						null,
					]),
					undefined,
				]),
				state: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						faker.string.alpha({ length: { min: 4, max: 4 } }),
						null,
					]),
					undefined,
				]),
				zip: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						faker.number.float({ fractionDigits: 2 }),
						null,
					]),
					undefined,
				]),
				postal: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						faker.string.alpha({ length: { min: 10, max: 15 } }),
						null,
					]),
					undefined,
				]),
				country: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						faker.string.alpha({ length: { min: 4, max: 4 } }),
						null,
					]),
					undefined,
				]),
				coaches: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						faker.string.alpha({ length: { min: 10, max: 20 } }),
						null,
					]),
					undefined,
				]),
				self_prefs: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						faker.datatype.boolean(),
						null,
					]),
					undefined,
				]),
				level: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						faker.string.alpha({ length: { min: 10, max: 20 } }),
						null,
					]),
					undefined,
				]),
				nsda: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						faker.number.float({ fractionDigits: 2 }),
						null,
					]),
					undefined,
				]),
				district: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						faker.number.float({ fractionDigits: 2 }),
						null,
					]),
					undefined,
				]),
				naudl: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						faker.datatype.boolean(),
						null,
					]),
					undefined,
				]),
				ipeds: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						faker.string.alpha({ length: { min: 10, max: 20 } }),
						null,
					]),
					undefined,
				]),
				nces: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						faker.string.alpha({ length: { min: 10, max: 20 } }),
						null,
					]),
					undefined,
				]),
				ceeb: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						faker.string.alpha({ length: { min: 10, max: 20 } }),
						null,
					]),
					undefined,
				]),
				timestamp: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						faker.string.alpha({ length: { min: 10, max: 20 } }),
						null,
					]),
					undefined,
				]),
				created_at: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						faker.string.alpha({ length: { min: 10, max: 20 } }),
						null,
					]),
					undefined,
				]),
			},
			undefined,
		]),
		Person: faker.helpers.arrayElement([
			{
				id: faker.number.int({ min: 0, max: 9007199254740991 }),
				email: faker.internet.email(),
				first: faker.string.alpha({ length: { min: 10, max: 20 } }),
				middle: faker.helpers.arrayElement([
					faker.string.alpha({ length: { min: 10, max: 20 } }),
					null,
				]),
				last: faker.string.alpha({ length: { min: 10, max: 20 } }),
				state: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						faker.helpers.fromRegExp('^[A-Z]{2}$'),
						null,
					]),
					undefined,
				]),
				country: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						faker.string.alpha({ length: { min: 10, max: 20 } }),
						null,
					]),
					undefined,
				]),
				tz: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						faker.string.alpha({ length: { min: 10, max: 20 } }),
						null,
					]),
					undefined,
				]),
				createdAt: faker.date.past().toISOString().slice(0, 19) + 'Z',
				settings: faker.helpers.arrayElement([{}, undefined]),
				metadata: faker.helpers.arrayElement([{}, undefined]),
			},
			undefined,
		]),
		createdAt: faker.string.alpha({ length: { min: 10, max: 20 } }),
		settings: faker.helpers.arrayElement([{}, undefined]),
		metadata: faker.helpers.arrayElement([{}, undefined]),
	}));

export const getUserStudentsClaimResponseMock = (
	overrideResponse: Partial<Extract<UserStudentsClaim200, object>> = {},
): UserStudentsClaim200 => ({
	message: faker.string.alpha({ length: { min: 10, max: 20 } }),
	detail: faker.string.alpha({ length: { min: 10, max: 20 } }),
	...overrideResponse,
});

export const getUserChaptersResponseMock = (): UserChapter[] =>
	Array.from(
		{ length: faker.number.int({ min: 1, max: 10 }) },
		(_, i) => i + 1,
	).map(() => ({
		id: faker.number.int({ min: 0, max: 9007199254740991 }),
		name: faker.string.alpha({ length: { min: 10, max: 20 } }),
		formal: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				null,
			]),
			undefined,
		]),
		street: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				null,
			]),
			undefined,
		]),
		city: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				null,
			]),
			undefined,
		]),
		state: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 4, max: 4 } }),
				null,
			]),
			undefined,
		]),
		zip: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				faker.number.float({ fractionDigits: 2 }),
				null,
			]),
			undefined,
		]),
		postal: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 15 } }),
				null,
			]),
			undefined,
		]),
		country: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 4, max: 4 } }),
				null,
			]),
			undefined,
		]),
		coaches: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				null,
			]),
			undefined,
		]),
		self_prefs: faker.helpers.arrayElement([
			faker.helpers.arrayElement([faker.datatype.boolean(), null]),
			undefined,
		]),
		level: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				null,
			]),
			undefined,
		]),
		nsda: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				faker.number.float({ fractionDigits: 2 }),
				null,
			]),
			undefined,
		]),
		district: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				faker.number.float({ fractionDigits: 2 }),
				null,
			]),
			undefined,
		]),
		naudl: faker.helpers.arrayElement([
			faker.helpers.arrayElement([faker.datatype.boolean(), null]),
			undefined,
		]),
		ipeds: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				null,
			]),
			undefined,
		]),
		nces: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				null,
			]),
			undefined,
		]),
		ceeb: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				null,
			]),
			undefined,
		]),
		timestamp: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				null,
			]),
			undefined,
		]),
		created_at: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				null,
			]),
			undefined,
		]),
		permission: faker.string.alpha({ length: { min: 10, max: 20 } }),
	}));

export const getRestAdsMockHandler = (
	overrideResponse?:
		| HomepageAd[]
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<HomepageAd[]> | HomepageAd[]),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		'*/rest/ads',
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === 'function'
						? await overrideResponse(info)
						: overrideResponse
					: getRestAdsResponseMock(),
				{ status: 200 },
			);
		},
		options,
	);
};

export const getRestCircuitsActiveMockHandler = (
	overrideResponse?:
		| ActiveCircuitsResponse
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<ActiveCircuitsResponse> | ActiveCircuitsResponse),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		'*/rest/circuits/active',
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === 'function'
						? await overrideResponse(info)
						: overrideResponse
					: getRestCircuitsActiveResponseMock(),
				{ status: 200 },
			);
		},
		options,
	);
};

export const getRestCircuitMockHandler = (
	overrideResponse?:
		| RestCircuit
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<RestCircuit> | RestCircuit),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		'*/rest/circuits/:circuitId',
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === 'function'
						? await overrideResponse(info)
						: overrideResponse
					: getRestCircuitResponseMock(),
				{ status: 200 },
			);
		},
		options,
	);
};

export const getRestJudgesUnlinkedSearchMockHandler = (
	overrideResponse?:
		| UnlinkedJudge[]
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<UnlinkedJudge[]> | UnlinkedJudge[]),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		'*/rest/judges/unlinked/search',
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === 'function'
						? await overrideResponse(info)
						: overrideResponse
					: getRestJudgesUnlinkedSearchResponseMock(),
				{ status: 200 },
			);
		},
		options,
	);
};

export const getRestTournsMockHandler = (
	overrideResponse?:
		| Tourn[]
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<Tourn[]> | Tourn[]),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		'*/rest/tourns',
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === 'function'
						? await overrideResponse(info)
						: overrideResponse
					: getRestTournsResponseMock(),
				{ status: 200 },
			);
		},
		options,
	);
};

export const getGetTournResultSetsMockHandler = (
	overrideResponse?:
		| GetTournResultSets200
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<GetTournResultSets200> | GetTournResultSets200),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		'*/rest/tourns/:tournId/results',
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === 'function'
						? await overrideResponse(info)
						: overrideResponse
					: getGetTournResultSetsResponseMock(),
				{ status: 200 },
			);
		},
		options,
	);
};

export const getGetResultSetMockHandler = (
	overrideResponse?:
		| ResultSet[]
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<ResultSet[]> | ResultSet[]),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		'*/rest/tourns/:tournId/results/:resultSetId',
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === 'function'
						? await overrideResponse(info)
						: overrideResponse
					: getGetResultSetResponseMock(),
				{ status: 200 },
			);
		},
		options,
	);
};

export const getRestParadigmsMockHandler = (
	overrideResponse?:
		| RestParadigms200Item[]
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<RestParadigms200Item[]> | RestParadigms200Item[]),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		'*/rest/paradigms',
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === 'function'
						? await overrideResponse(info)
						: overrideResponse
					: getRestParadigmsResponseMock(),
				{ status: 200 },
			);
		},
		options,
	);
};

export const getRestParadigmMockHandler = (
	overrideResponse?:
		| ParadigmDetails
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<ParadigmDetails> | ParadigmDetails),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		'*/rest/paradigms/:personId',
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === 'function'
						? await overrideResponse(info)
						: overrideResponse
					: getRestParadigmResponseMock(),
				{ status: 200 },
			);
		},
		options,
	);
};

export const getRestParadigmsRecordMockHandler = (
	overrideResponse?:
		| JudgeRecord[]
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<JudgeRecord[]> | JudgeRecord[]),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		'*/rest/paradigms/:personId/record',
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === 'function'
						? await overrideResponse(info)
						: overrideResponse
					: getRestParadigmsRecordResponseMock(),
				{ status: 200 },
			);
		},
		options,
	);
};

export const getRestQuizzesMockHandler = (
	overrideResponse?:
		| QuizOutput[]
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<QuizOutput[]> | QuizOutput[]),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		'*/rest/quizzes',
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === 'function'
						? await overrideResponse(info)
						: overrideResponse
					: getRestQuizzesResponseMock(),
				{ status: 200 },
			);
		},
		options,
	);
};

export const getRestStudentsUnlinkedSearchMockHandler = (
	overrideResponse?:
		| UnlinkedStudentSearch[]
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<UnlinkedStudentSearch[]> | UnlinkedStudentSearch[]),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		'*/rest/students/unlinked/search',
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === 'function'
						? await overrideResponse(info)
						: overrideResponse
					: getRestStudentsUnlinkedSearchResponseMock(),
				{ status: 200 },
			);
		},
		options,
	);
};

export const getAuthLoginMockHandler = (
	overrideResponse?:
		| LoginResponse
		| ((
				info: Parameters<Parameters<typeof http.post>[1]>[0],
		  ) => Promise<LoginResponse> | LoginResponse),
	options?: RequestHandlerOptions,
) => {
	return http.post(
		'*/auth/login',
		async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === 'function'
						? await overrideResponse(info)
						: overrideResponse
					: getAuthLoginResponseMock(),
				{ status: 200 },
			);
		},
		options,
	);
};

export const getAuthLogoutMockHandler = (
	overrideResponse?:
		| void
		| ((
				info: Parameters<Parameters<typeof http.post>[1]>[0],
		  ) => Promise<void> | void),
	options?: RequestHandlerOptions,
) => {
	return http.post(
		'*/auth/logout',
		async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
			if (typeof overrideResponse === 'function') {
				await overrideResponse(info);
			}

			return new HttpResponse(null, { status: 204 });
		},
		options,
	);
};

export const getAuthSuMockHandler = (
	overrideResponse?:
		| void
		| ((
				info: Parameters<Parameters<typeof http.post>[1]>[0],
		  ) => Promise<void> | void),
	options?: RequestHandlerOptions,
) => {
	return http.post(
		'*/auth/su',
		async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
			if (typeof overrideResponse === 'function') {
				await overrideResponse(info);
			}

			return new HttpResponse(null, { status: 204 });
		},
		options,
	);
};

export const getAuthSuEndMockHandler = (
	overrideResponse?:
		| void
		| ((
				info: Parameters<Parameters<typeof http.post>[1]>[0],
		  ) => Promise<void> | void),
	options?: RequestHandlerOptions,
) => {
	return http.post(
		'*/auth/suend',
		async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
			if (typeof overrideResponse === 'function') {
				await overrideResponse(info);
			}

			return new HttpResponse(null, { status: 204 });
		},
		options,
	);
};

export const getAuthRegisterMockHandler = (
	overrideResponse?:
		| void
		| ((
				info: Parameters<Parameters<typeof http.post>[1]>[0],
		  ) => Promise<void> | void),
	options?: RequestHandlerOptions,
) => {
	return http.post(
		'*/auth/register',
		async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
			if (typeof overrideResponse === 'function') {
				await overrideResponse(info);
			}

			return new HttpResponse(null, { status: 200 });
		},
		options,
	);
};

export const getUserTournsMockHandler = (
	overrideResponse?:
		| Tourn[]
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<Tourn[]> | Tourn[]),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		'*/user/tourns',
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === 'function'
						? await overrideResponse(info)
						: overrideResponse
					: getUserTournsResponseMock(),
				{ status: 200 },
			);
		},
		options,
	);
};

export const getUserTournsSummaryMockHandler = (
	overrideResponse?:
		| PersonTournSummary
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<PersonTournSummary> | PersonTournSummary),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		'*/user/tourns/:tournId/summary',
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === 'function'
						? await overrideResponse(info)
						: overrideResponse
					: getUserTournsSummaryResponseMock(),
				{ status: 200 },
			);
		},
		options,
	);
};

export const getUserTournsFinesMockHandler = (
	overrideResponse?:
		| Fine[]
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<Fine[]> | Fine[]),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		'*/user/tourns/:tournId/fines',
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === 'function'
						? await overrideResponse(info)
						: overrideResponse
					: getUserTournsFinesResponseMock(),
				{ status: 200 },
			);
		},
		options,
	);
};

export const getUserTournsBallotsMockHandler = (
	overrideResponse?:
		| CurrentBallot[]
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<CurrentBallot[]> | CurrentBallot[]),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		'*/user/tourns/:tournId/ballots',
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === 'function'
						? await overrideResponse(info)
						: overrideResponse
					: getUserTournsBallotsResponseMock(),
				{ status: 200 },
			);
		},
		options,
	);
};

export const getUserTournsBallotsCurrentMockHandler = (
	overrideResponse?:
		| CurrentBallot[]
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<CurrentBallot[]> | CurrentBallot[]),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		'*/user/tourns/:tournId/ballots/current',
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === 'function'
						? await overrideResponse(info)
						: overrideResponse
					: getUserTournsBallotsCurrentResponseMock(),
				{ status: 200 },
			);
		},
		options,
	);
};

export const getUserInboxMockHandler = (
	overrideResponse?:
		| InboxMessage[]
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<InboxMessage[]> | InboxMessage[]),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		'*/user/inbox',
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === 'function'
						? await overrideResponse(info)
						: overrideResponse
					: getUserInboxResponseMock(),
				{ status: 200 },
			);
		},
		options,
	);
};

export const getUserInboxUnreadMockHandler = (
	overrideResponse?:
		| UserInboxUnread200
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<UserInboxUnread200> | UserInboxUnread200),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		'*/user/inbox/unread',
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === 'function'
						? await overrideResponse(info)
						: overrideResponse
					: getUserInboxUnreadResponseMock(),
				{ status: 200 },
			);
		},
		options,
	);
};

export const getUserInboxMarkAllReadMockHandler = (
	overrideResponse?:
		| void
		| ((
				info: Parameters<Parameters<typeof http.post>[1]>[0],
		  ) => Promise<void> | void),
	options?: RequestHandlerOptions,
) => {
	return http.post(
		'*/user/inbox/markAllRead',
		async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
			if (typeof overrideResponse === 'function') {
				await overrideResponse(info);
			}

			return new HttpResponse(null, { status: 204 });
		},
		options,
	);
};

export const getUserInboxGetMessageMockHandler = (
	overrideResponse?:
		| InboxMessage
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<InboxMessage> | InboxMessage),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		'*/user/inbox/:messageId',
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === 'function'
						? await overrideResponse(info)
						: overrideResponse
					: getUserInboxGetMessageResponseMock(),
				{ status: 200 },
			);
		},
		options,
	);
};

export const getUserInboxMarkDeletedMockHandler = (
	overrideResponse?:
		| void
		| ((
				info: Parameters<Parameters<typeof http.delete>[1]>[0],
		  ) => Promise<void> | void),
	options?: RequestHandlerOptions,
) => {
	return http.delete(
		'*/user/inbox/:messageId',
		async (info: Parameters<Parameters<typeof http.delete>[1]>[0]) => {
			if (typeof overrideResponse === 'function') {
				await overrideResponse(info);
			}

			return new HttpResponse(null, { status: 204 });
		},
		options,
	);
};

export const getUserInboxMarkReadMockHandler = (
	overrideResponse?:
		| void
		| ((
				info: Parameters<Parameters<typeof http.post>[1]>[0],
		  ) => Promise<void> | void),
	options?: RequestHandlerOptions,
) => {
	return http.post(
		'*/user/inbox/:messageId/markRead',
		async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
			if (typeof overrideResponse === 'function') {
				await overrideResponse(info);
			}

			return new HttpResponse(null, { status: 204 });
		},
		options,
	);
};

export const getUserInboxMarkUnreadMockHandler = (
	overrideResponse?:
		| void
		| ((
				info: Parameters<Parameters<typeof http.post>[1]>[0],
		  ) => Promise<void> | void),
	options?: RequestHandlerOptions,
) => {
	return http.post(
		'*/user/inbox/:messageId/markUnread',
		async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
			if (typeof overrideResponse === 'function') {
				await overrideResponse(info);
			}

			return new HttpResponse(null, { status: 204 });
		},
		options,
	);
};

export const getUserSessionMockHandler = (
	overrideResponse?:
		| Session
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<Session> | Session),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		'*/user/session',
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === 'function'
						? await overrideResponse(info)
						: overrideResponse
					: getUserSessionResponseMock(),
				{ status: 200 },
			);
		},
		options,
	);
};

export const getUserJudgesLinkRequestsMockHandler = (
	overrideResponse?:
		| UnlinkedJudge[]
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<UnlinkedJudge[]> | UnlinkedJudge[]),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		'*/user/judges/linkRequests',
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === 'function'
						? await overrideResponse(info)
						: overrideResponse
					: getUserJudgesLinkRequestsResponseMock(),
				{ status: 200 },
			);
		},
		options,
	);
};

export const getUserJudgesClaimMockHandler = (
	overrideResponse?:
		| UserJudgesClaim200
		| ((
				info: Parameters<Parameters<typeof http.post>[1]>[0],
		  ) => Promise<UserJudgesClaim200> | UserJudgesClaim200),
	options?: RequestHandlerOptions,
) => {
	return http.post(
		'*/user/judges/claim',
		async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === 'function'
						? await overrideResponse(info)
						: overrideResponse
					: getUserJudgesClaimResponseMock(),
				{ status: 200 },
			);
		},
		options,
	);
};

export const getUserJudgesHistoryMockHandler = (
	overrideResponse?:
		| JudgeHistory
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<JudgeHistory> | JudgeHistory),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		'*/user/judges/history',
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === 'function'
						? await overrideResponse(info)
						: overrideResponse
					: getUserJudgesHistoryResponseMock(),
				{ status: 200 },
			);
		},
		options,
	);
};

export const getUserJudgesParadigmMockHandler = (
	overrideResponse?:
		| UserJudgesParadigm200
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<UserJudgesParadigm200> | UserJudgesParadigm200),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		'*/user/judges/paradigm',
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === 'function'
						? await overrideResponse(info)
						: overrideResponse
					: getUserJudgesParadigmResponseMock(),
				{ status: 200 },
			);
		},
		options,
	);
};

export const getPostUserJudgesParadigmMockHandler = (
	overrideResponse?:
		| void
		| ((
				info: Parameters<Parameters<typeof http.post>[1]>[0],
		  ) => Promise<void> | void),
	options?: RequestHandlerOptions,
) => {
	return http.post(
		'*/user/judges/paradigm',
		async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
			if (typeof overrideResponse === 'function') {
				await overrideResponse(info);
			}

			return new HttpResponse(null, { status: 204 });
		},
		options,
	);
};

export const getUserJudgesLiveDocsMockHandler = (
	overrideResponse?:
		| UserJudgesLiveDocs200Item[]
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) =>
				| Promise<UserJudgesLiveDocs200Item[]>
				| UserJudgesLiveDocs200Item[]),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		'*/user/judges/livedocs',
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === 'function'
						? await overrideResponse(info)
						: overrideResponse
					: getUserJudgesLiveDocsResponseMock(),
				{ status: 200 },
			);
		},
		options,
	);
};

export const getUserStudentsLinkRequestsMockHandler = (
	overrideResponse?:
		| Student[]
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<Student[]> | Student[]),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		'*/user/students/linkRequests',
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === 'function'
						? await overrideResponse(info)
						: overrideResponse
					: getUserStudentsLinkRequestsResponseMock(),
				{ status: 200 },
			);
		},
		options,
	);
};

export const getUserStudentsClaimMockHandler = (
	overrideResponse?:
		| UserStudentsClaim200
		| ((
				info: Parameters<Parameters<typeof http.post>[1]>[0],
		  ) => Promise<UserStudentsClaim200> | UserStudentsClaim200),
	options?: RequestHandlerOptions,
) => {
	return http.post(
		'*/user/students/claim',
		async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === 'function'
						? await overrideResponse(info)
						: overrideResponse
					: getUserStudentsClaimResponseMock(),
				{ status: 200 },
			);
		},
		options,
	);
};

export const getUserChaptersMockHandler = (
	overrideResponse?:
		| UserChapter[]
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<UserChapter[]> | UserChapter[]),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		'*/user/chapters',
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === 'function'
						? await overrideResponse(info)
						: overrideResponse
					: getUserChaptersResponseMock(),
				{ status: 200 },
			);
		},
		options,
	);
};
export const getIndexCardsAPIMock = () => [
	getRestAdsMockHandler(),
	getRestCircuitsActiveMockHandler(),
	getRestCircuitMockHandler(),
	getRestJudgesUnlinkedSearchMockHandler(),
	getRestTournsMockHandler(),
	getGetTournResultSetsMockHandler(),
	getGetResultSetMockHandler(),
	getRestParadigmsMockHandler(),
	getRestParadigmMockHandler(),
	getRestParadigmsRecordMockHandler(),
	getRestQuizzesMockHandler(),
	getRestStudentsUnlinkedSearchMockHandler(),
	getAuthLoginMockHandler(),
	getAuthLogoutMockHandler(),
	getAuthSuMockHandler(),
	getAuthSuEndMockHandler(),
	getAuthRegisterMockHandler(),
	getUserTournsMockHandler(),
	getUserTournsSummaryMockHandler(),
	getUserTournsFinesMockHandler(),
	getUserTournsBallotsMockHandler(),
	getUserTournsBallotsCurrentMockHandler(),
	getUserInboxMockHandler(),
	getUserInboxUnreadMockHandler(),
	getUserInboxMarkAllReadMockHandler(),
	getUserInboxGetMessageMockHandler(),
	getUserInboxMarkDeletedMockHandler(),
	getUserInboxMarkReadMockHandler(),
	getUserInboxMarkUnreadMockHandler(),
	getUserSessionMockHandler(),
	getUserJudgesLinkRequestsMockHandler(),
	getUserJudgesClaimMockHandler(),
	getUserJudgesHistoryMockHandler(),
	getUserJudgesParadigmMockHandler(),
	getPostUserJudgesParadigmMockHandler(),
	getUserJudgesLiveDocsMockHandler(),
	getUserStudentsLinkRequestsMockHandler(),
	getUserStudentsClaimMockHandler(),
	getUserChaptersMockHandler(),
];
