
export type Tournament = {
		id           : number  ,
		webname      : string  ,
		name         : string  ,
		tz           : string  ,
		tzCode       : string  ,
		districts?   : number  ,
		weekendName? : string  ,
		location?    : string  ,
		state?       : string  ,
		country?     : string  ,
		site?        : string  ,
		start        : string  ,
		end          : string  ,
		reg_end      : string  ,
		reg_start    : string  ,
		schoolcount  : number  ,
		year         : number  ,
		week         : number  ,
		sortweek     : string  ,
		sortnumeric  : number  ,
		signup?      : string  ,
		online       : number ,
		in_person    : number ,
		hybrid       : number ,
		closed       : boolean ,
		nats?        : boolean ,
		msnats?      : boolean ,
		dates?       : string  ,
};