name: Tabroom Schemats CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
    CI: true
    HUSKY: 0
    TZ: "America/Chicago"
    SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Get node
      uses: actions/setup-node@v1
      with:
        node-version: 24.13.1

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

    - name: Install packages
      run: npm install
      working-directory: .

    - name: Lint
      run: npm run lint
      working-directory: .

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Get node
      uses: actions/setup-node@v1
      with:
        node-version: 24.13.1

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

    - name: Install packages
      run: npm install
      working-directory: .

    - name: Tests
      run: npm run test:ci
      working-directory: .

    # - name: If tests succeed, change icon
    #   if: success()
    #   run: echo "SLACK_ICON=:white_check_mark:" >> $GITHUB_ENV

    # - name: Send slack notification
    #   if: always()
    #   uses: speechanddebate/action-slack-notify@master
